#ifdef NDEBUG
#undef NDEBUG
#endif
#include "../fresh_inventory_owned_v4.hpp"
#include <fstream>
#include <iostream>
#include <cstring>
extern "C" {
#include "../../random/random.h"
}
using namespace dh2::data;using Raw=std::vector<std::uint8_t>;
static unsigned checks;
static void ck(bool b){if(!b)throw std::runtime_error("Owned V4 check "+std::to_string(checks));++checks;}
static Raw file(const std::string& p){std::ifstream f(p,std::ios::binary);ck(bool(f));return {std::istreambuf_iterator<char>(f),{}};}
static void w(Raw& b,std::uint32_t n){for(int i=0;i<4;++i)b.push_back(std::uint8_t(n>>(8*i)));}
static std::int32_t si(std::uint32_t n){std::int32_t x;std::memcpy(&x,&n,4);return x;}
static std::uint32_t rd(const Raw& b,std::size_t& at){ck(at<=b.size()&&b.size()-at>=4);std::uint32_t n;std::memcpy(&n,b.data()+at,4);at+=4;return n;}
struct BorrowedRandom{dh2_random_state live{{1,0x98765432u},{0,3}};LootRandom8V2 fixture{1,0};unsigned draws{};};
static bool live_random(void* context,std::int32_t bound,std::uint32_t stream,std::int32_t& value,std::string& error){if(!context){error="missing live random state";return false;}auto& r=*static_cast<BorrowedRandom*>(context);if(stream!=0){error="V4 fixture requested an unsupported RNG stream";return false;}auto live_value=dh2_random_next(&r.live,std::uint32_t(bound),stream);std::int32_t fixture_value{};if(dh2_loot_v2_random(&r.fixture,bound,&fixture_value)!=0||live_value!=fixture_value||r.live.seeds[0]!=r.fixture.seed||r.live.counters[0]!=r.fixture.calls){error="borrowed RNG diverged from fixture stream";return false;}value=live_value;++r.draws;return true;}
static void seed_borrowed_random(BorrowedRandom& r,std::uint32_t seed,std::uint32_t calls){r.live.seeds[0]=seed;r.live.seeds[1]=0x98765432u;r.live.counters[0]=calls;r.live.counters[1]=3;r.fixture={seed,calls};r.draws=0;}
static Raw snap(const FreshInventoryOwnedV4& o){Raw b;w(b,std::uint32_t(o.gold()));w(b,o.current_equipment());w(b,o.items().size());std::uint32_t potion=UINT32_MAX;for(std::size_t i=0;i<o.items().size();++i){const auto& s=*o.items()[i];const auto& p=*s.item;if(o.potion()==&p)potion=std::uint32_t(i);for(auto n:{std::uint32_t(p.id),std::uint32_t(p.quantity),std::uint32_t(p.value),std::uint32_t(p.identified),std::uint32_t(std::uint8_t(s.slots[0])),std::uint32_t(std::uint8_t(s.slots[1])),std::uint32_t(p.powers.size())})w(b,n);for(auto n:p.powers)w(b,n);}w(b,potion);for(const auto& set:o.equipment())for(auto* p:set){std::uint32_t n=UINT32_MAX;for(std::size_t i=0;i<o.items().size();++i)if(p==o.items()[i].get())n=std::uint32_t(i);w(b,n);}return b;}
struct Context{Raw requests;unsigned delivered{},reentries{},destroyed{},fullness{};int fail{-1},minimal{},mutation{},infinite{};bool toggle_stats{};bool legacy{};};
static bool service(void* p,FreshInventoryOwnedV4& o,const OwnedInventoryRequestV4& q,OwnedInventoryResponseV4& out,std::string& e){auto& c=*static_cast<Context*>(p);if(int(c.delivered++)==c.fail){e="Missing genuine effect fixture";return false;}auto op=std::uint32_t(q.operation);if(op==0x3fdfd8||op==0x3ff7a8)return true;auto caller=(op==0x337888||op==0x337a88||op==0x31f594||op==0x3e08a8||op==0x3a999c||op==0x3bd140)?q.source_caller:0;
 // V2's controlled fullness result is not an original fullness proof. The new
 // Debug prefix is independently gold-compared in V4, omitted ONLY in the old
 // regression request normalization so old frozen receipts stay untouched.
 if(c.legacy&&(q.source_caller==0x3fe364||q.source_caller==0x3fe3a8)){out.value=0;return true;}
 auto* i=q.item;auto arg=op==0x337a88&&q.source_caller==0x40411c&&c.minimal?1:op==0x337a88&&q.source_caller==0x3fe3a8?c.infinite:0;
 for(auto v:{op,caller,i?std::uint32_t(i->id):0,i?std::uint32_t(i->quantity):0,i?std::uint32_t(i->value):0,std::uint32_t(arg),q.index})w(c.requests,v);
 if(op==0x337a88){ck(q.name);out.value=arg;}else if(op==0x3fb290&&c.mutation==1)i->id=925;else if(op==0x3fb754&&c.mutation==2&&i->value)i->id=925;
 if(op==0x3fb290&&c.toggle_stats&&i->signed_quantity()>1){o.swap_equipment();o.properties()->resolved[202]^=1;}
 if(op==0x3fb290){std::string nested;ck(!o.add_fixed_loot(165,{&c,service},nested)&&!nested.empty());++c.reentries;}
 return true;}
static void observed(void* p,FreshInventoryOwnedV4&,const OwnedInventoryRequestV4& q){auto& c=*static_cast<Context*>(p);if(q.operation==OwnedInventoryOperationV4::destroy_item)++c.destroyed;if(q.operation==OwnedInventoryOperationV4::inventory_full)++c.fullness;if(c.legacy){auto* i=q.item;for(auto v:{std::uint32_t(q.operation),0u,i?std::uint32_t(i->id):0,i?std::uint32_t(i->quantity):0,i?std::uint32_t(i->value):0,0u,q.index})w(c.requests,v);}}
static Raw synthetic_records(const Raw& records,const ItemTable& table,std::uint32_t id){Raw next=records;if(id==UINT32_MAX)return next;std::size_t at=table.data_begin+4;for(std::uint32_t i=0;i<=id;++i){ck(at+4<=next.size());std::uint32_t length;std::memcpy(&length,next.data()+at,4);at+=4+length+16;ck(at<next.size());if(i==id){next[at]=1;return next;}at+=1+44;ck(at+4<=next.size());std::memcpy(&length,next.data()+at,4);at+=4+length+80;}throw std::runtime_error("Synthetic record index");}
static std::uint32_t perform(FreshInventoryOwnedV4& o,const OwnedInventoryServicesV4& s,std::uint32_t op,std::uint32_t a,std::uint32_t b,std::uint32_t c,std::string& e){std::int32_t result=0;bool ok=true;switch(op){case 0:ok=o.add_fixed_loot(si(a),s,e);break;case 1:{std::unique_ptr<ItemInstanceV1> p;ok=o.create_item(si(a),b,p,s,e)&&o.add_item(p,c&1,c&2,result,s,e);break;}case 2:ok=o.character_auto_equip(a,result,s,e);break;case 3:ok=o.equip_to_slot(a,b,c,s,e);break;case 4:ok=o.unequip_from_slot(a,si(b),s,e);break;case 5:o.swap_equipment();break;case 6:ok=o.add_gold(si(a),s,e);break;case 7:{std::unique_ptr<ItemInstanceV1> p;ok=a<o.items().size()&&o.split_item(*o.items()[a]->item,si(b),p,s,e);if(ok){if(p)ok=o.add_item(p,c&1,c&2,result,s,e);else result=-1;}break;}case 8:o.project_potion_capacity(std::int8_t(a));break;case 9:o.properties()->resolved[202]=si(a);o.properties()->resolved[203]=si(b);break;case 10:o.project_gold_limit(si(a));break;case 11:{bool eq=false,two=false;ok=o.is_equipped(a,eq,e)&&o.has_two_hander(b!=0,two,e);result=int(eq)|(int(two)<<1);break;}case 12:{bool full;ok=o.inventory_full(full,s,e);result=full;break;}case 13:o.project_unlimited(a!=0);break;case 14:static_cast<Context*>(s.context)->infinite=si(a);break;default:ok=false;}if(!ok)throw std::runtime_error("Required V4 step failed "+std::to_string(op)+": "+e);return std::uint32_t(result);}
static void random_and_item_checks(){
 for(const auto quantity:std::array<std::uint16_t,4>{{0,1,0x7fff,0xfffe}}){ItemInstanceV1 instance;instance.quantity=quantity;std::int16_t signed_value;std::memcpy(&signed_value,&quantity,2);ck(instance.signed_quantity()==signed_value);}
 for(const std::uint32_t seed:std::array<std::uint32_t,5>{{0,1,0x7fffffff,0x80000000,0xffffffff}})for(const std::int32_t bound:std::array<std::int32_t,5>{{0,1,7,100,-1}}){LootRandom8V2 fixture_rng{seed,9};dh2_random_state live_rng{{seed,0x98765432},{9,3}};std::int32_t fixture_value=0;ck(dh2_loot_v2_random(&fixture_rng,bound,&fixture_value)==0);auto live_value=dh2_random_next(&live_rng,std::uint32_t(bound),0);ck(fixture_value==live_value&&fixture_rng.seed==live_rng.seeds[0]&&fixture_rng.calls==live_rng.counters[0]&&live_rng.seeds[1]==0x98765432&&live_rng.counters[1]==3);}
}
static void borrowed_corpus(const char* gold_path,const char* legacy_path,const char* cache_path){
 auto records=file(std::string(cache_path)+"/loot_table_pyarray.bin"),names=file(std::string(cache_path)+"/loot_table_pyarraynames.bin"),schema=file(std::string(cache_path)+"/loot_table_pystructnames.bin");LootTablesV2 table;std::string e;ck(table.load({records.data(),records.size()},{names.data(),names.size()},{schema.data(),schema.size()},e));
 auto gold=file(gold_path);std::size_t at=0;ck(rd(gold,at)==0x34564f49);auto cases=rd(gold,at);unsigned steps=0,requests=0,draws=0;std::uint32_t owner_cases=0;
 for(unsigned k=0;k<cases;++k){auto cap=std::int8_t(rd(gold,at));auto flags=rd(gold,at),selected=rd(gold,at),synthetic=rd(gold,at),n=rd(gold,at);auto rec=synthetic_records(records,table.borrow().items(),synthetic);LootTablesV2 selected_table;ck(selected_table.load({rec.data(),rec.size()},{names.data(),names.size()},{schema.data(),schema.size()},e));PropertyState props{};props.resolved[202]=flags&1;props.resolved[203]=flags>>1;BorrowedRandom random;seed_borrowed_random(random,1,0);FreshInventoryOwnedV4 o(UINT64_C(0x123400005678),selected_table.borrow(),{&random,live_random},cap,props);ck(o.properties()==&props);o.project_gold_limit(10000);if(selected)o.swap_equipment();Context ctx;ctx.toggle_stats=flags&0x100;OwnedInventoryServicesV4 svc{&ctx,service,observed,true};
  for(unsigned j=0;j<n;++j){auto op=rd(gold,at),a=rd(gold,at),b=rd(gold,at),c=rd(gold,at),expected=rd(gold,at),size=rd(gold,at);ck(size<=gold.size()-at);Raw state(gold.begin()+at,gold.begin()+at+size);at+=size;auto nr=rd(gold,at);ck(nr*28<=gold.size()-at);Raw req(gold.begin()+at,gold.begin()+at+nr*28);at+=nr*28;ctx.requests.clear();auto result=perform(o,svc,op,a,b,c,e);ck(o.properties()==&props);if(result!=expected||snap(o)!=state)throw std::runtime_error("Borrowed original V4 state mismatch case "+std::to_string(k)+" step "+std::to_string(j)+" op "+std::to_string(op));if(ctx.requests!=req)throw std::runtime_error("Borrowed original V4 request mismatch case "+std::to_string(k)+" step "+std::to_string(j));ck(random.live.seeds[0]==random.fixture.seed&&random.live.counters[0]==random.fixture.calls&&random.live.seeds[1]==0x98765432u&&random.live.counters[1]==3);++steps;requests+=nr;}
  draws+=random.draws;++owner_cases;
 }
 ck(at==gold.size());auto legacy=file(legacy_path);at=0;ck(rd(legacy,at)==0x32564946);auto prior=rd(legacy,at);for(unsigned k=0;k<prior;++k){LootRandom8V2 initial{rd(legacy,at),rd(legacy,at)};auto cap=std::int8_t(rd(legacy,at));Context ctx;ctx.legacy=true;ctx.minimal=rd(legacy,at);ctx.mutation=rd(legacy,at);auto loot=si(rd(legacy,at));auto expected_seed=rd(legacy,at),expected_calls=rd(legacy,at),size=rd(legacy,at);ck(size<=legacy.size()-at);Raw expected(legacy.begin()+at,legacy.begin()+at+size);at+=size;auto nr=rd(legacy,at);ck(nr*28<=legacy.size()-at);Raw req(legacy.begin()+at,legacy.begin()+at+nr*28);at+=nr*28;PropertyState props{};BorrowedRandom random;seed_borrowed_random(random,initial.seed,initial.calls);FreshInventoryOwnedV4 o(1,table.borrow(),{&random,live_random},cap,props);ck(o.properties()==&props);ck(o.add_fixed_loot(loot,{&ctx,service,observed,true},e));ck(o.properties()==&props);ck(snap(o)==expected);ck(ctx.requests==req);ck(random.live.seeds[0]==expected_seed&&random.live.counters[0]==expected_calls);ck(random.fixture.seed==expected_seed&&random.fixture.calls==expected_calls&&random.live.seeds[1]==0x98765432u&&random.live.counters[1]==3);draws+=random.draws;++owner_cases;}
 ck(at==legacy.size());std::cout<<"{\"validation\":\"PASS\",\"borrowed_mode\":true,\"borrowed_owner_cases\":"<<owner_cases<<",\"original_owned_cases\":"<<cases<<",\"original_owned_steps\":"<<steps<<",\"source_effect_requests\":"<<requests<<",\"legacy_loot_regressions\":"<<prior<<",\"borrowed_rng_draws\":"<<draws<<",\"property_alias_checks\":"<<owner_cases+steps*2<<",\"checks\":"<<checks<<",\"mismatches\":0}\n";
}
int main(int argc,char** argv){try{if(argc==2&&std::string(argv[1])=="--random-only"){random_and_item_checks();std::cout<<"{\"validation\":\"PASS\",\"checks\":"<<checks<<",\"source_rng_adapter\":true,\"cache_required\":false}\n";return 0;}if(argc==5&&std::string(argv[1])=="--borrowed"){borrowed_corpus(argv[2],argv[3],argv[4]);return 0;}ck(argc==4);auto records=file(std::string(argv[3])+"/loot_table_pyarray.bin"),names=file(std::string(argv[3])+"/loot_table_pyarraynames.bin"),schema=file(std::string(argv[3])+"/loot_table_pystructnames.bin");LootTablesV2 table;std::string e;ck(table.load({records.data(),records.size()},{names.data(),names.size()},{schema.data(),schema.size()},e));auto gold=file(argv[1]);std::size_t at=0;ck(rd(gold,at)==0x34564f49);auto cases=rd(gold,at);unsigned steps=0,requests=0,destroyed=0,fullness=0,guards=0;
 for(unsigned k=0;k<cases;++k){auto cap=std::int8_t(rd(gold,at));auto flags=rd(gold,at),selected=rd(gold,at),synthetic=rd(gold,at),n=rd(gold,at);auto rec=synthetic_records(records,table.borrow().items(),synthetic);LootTablesV2 selected_table;ck(selected_table.load({rec.data(),rec.size()},{names.data(),names.size()},{schema.data(),schema.size()},e));LootRandom8V2 r{1,0};auto props=std::make_shared<PropertyState>();props->resolved[202]=flags&1;props->resolved[203]=flags>>1;FreshInventoryOwnedV4 o(UINT64_C(0x123400005678),selected_table.borrow(),r,cap,props);o.project_gold_limit(10000);if(selected)o.swap_equipment();Context ctx;ctx.toggle_stats=flags&0x100;OwnedInventoryServicesV4 svc{&ctx,service,observed,true};
  for(unsigned j=0;j<n;++j){auto op=rd(gold,at),a=rd(gold,at),b=rd(gold,at),c=rd(gold,at),expected=rd(gold,at),size=rd(gold,at);ck(size<=gold.size()-at);Raw state(gold.begin()+at,gold.begin()+at+size);at+=size;auto nr=rd(gold,at);ck(nr*28<=gold.size()-at);Raw req(gold.begin()+at,gold.begin()+at+nr*28);at+=nr*28;ctx.requests.clear();auto result=perform(o,svc,op,a,b,c,e);if(result!=expected||snap(o)!=state)throw std::runtime_error("Original V4 state mismatch case "+std::to_string(k)+" step "+std::to_string(j)+" op "+std::to_string(op));if(ctx.requests!=req){std::size_t m=0;while(m<std::min(req.size(),ctx.requests.size())&&req[m]==ctx.requests[m])++m;throw std::runtime_error("Original V4 request mismatch "+std::to_string(k)+"/"+std::to_string(j)+" byte "+std::to_string(m));}++steps;requests+=nr;}
  destroyed+=ctx.destroyed;fullness+=ctx.fullness;guards+=ctx.reentries;
 }
 ck(at==gold.size());auto legacy=file(argv[2]);at=0;ck(rd(legacy,at)==0x32564946);auto prior=rd(legacy,at);for(unsigned k=0;k<prior;++k){LootRandom8V2 r{rd(legacy,at),rd(legacy,at)};auto cap=std::int8_t(rd(legacy,at));Context c;c.legacy=true;c.minimal=rd(legacy,at);c.mutation=rd(legacy,at);auto loot=si(rd(legacy,at));auto seed=rd(legacy,at),calls=rd(legacy,at),size=rd(legacy,at);ck(size<=legacy.size()-at);Raw expected(legacy.begin()+at,legacy.begin()+at+size);at+=size;auto nr=rd(legacy,at);ck(nr*28<=legacy.size()-at);Raw req(legacy.begin()+at,legacy.begin()+at+nr*28);at+=nr*28;FreshInventoryOwnedV4 o(1,table.borrow(),r,cap,std::make_shared<PropertyState>());ck(o.add_fixed_loot(loot,{&c,service,observed,true},e));ck(snap(o)==expected);ck(c.requests==req);ck(r.seed==seed&&r.calls==calls);guards+=c.reentries;}ck(at==legacy.size());
 for(int fail=0;fail<24;++fail){LootRandom8V2 r{1,0};FreshInventoryOwnedV4 o(1,table.borrow(),r,12,std::make_shared<PropertyState>());Context c;c.fail=fail;ck(!o.add_fixed_loot(165,{&c,service,nullptr,true},e));ck(e=="Missing genuine effect fixture");++guards;}
 {LootRandom8V2 r{1,0};FreshInventoryOwnedV4 o(1,table.borrow(),r,12,std::make_shared<PropertyState>());std::int32_t result;ck(!o.auto_equip(0,result,{},e));ck(!o.unequip_from_slot(9,-1,{},e));ck(!o.set_gold(-1,{},e));std::unique_ptr<ItemInstanceV1> p;ck(!o.create_item(-1,1,p,{},e)&&!p);ck(!o.add_fixed_loot(165,{},e)&&o.items().empty());guards+=5;}
 // The live constructor aliases the caller's PropertyState and RNG. The
 // callback adapter uses the existing two-stream DH2 random owner; this
 // regression checks it against the imported V4 fixture stream.
 random_and_item_checks();
 {LootRandom8V2 fixture_rng{1,0};BorrowedRandom live_rng;seed_borrowed_random(live_rng,1,0);auto fixture_properties=std::make_shared<PropertyState>();PropertyState live_properties;live_properties.resolved[202]=fixture_properties->resolved[202]=1;FreshInventoryOwnedV4 fixture(UINT64_C(0x123400005678),table.borrow(),fixture_rng,12,fixture_properties);FreshInventoryOwnedV4 live(UINT64_C(0x123400005678),table.borrow(),{&live_rng,live_random},12,live_properties);ck(live.properties()==&live_properties);Context a,b;OwnedInventoryServicesV4 fixture_services{&a,service,observed,true},live_services{&b,service,observed,true};ck(fixture.add_fixed_loot(165,fixture_services,e));ck(live.add_fixed_loot(165,live_services,e));ck(snap(fixture)==snap(live)&&a.requests==b.requests&&live.properties()==&live_properties);ck(fixture_rng.seed==live_rng.live.seeds[0]&&fixture_rng.calls==live_rng.live.counters[0]&&live_rng.live.seeds[1]==0x98765432u&&live_rng.live.counters[1]==3);}
 std::cout<<"{\"validation\":\"PASS\",\"original_owned_cases\":"<<cases<<",\"original_owned_steps\":"<<steps<<",\"source_effect_requests\":"<<requests<<",\"legacy_loot_regressions\":"<<prior<<",\"native_item_deletions\":"<<destroyed<<",\"native_fullness_queries\":"<<fullness<<",\"guards\":"<<guards<<",\"checks\":"<<checks<<",\"mismatches\":0}\n";return 0;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
