#ifdef NDEBUG
#undef NDEBUG
#endif
#include "../fresh_inventory_owned_v4.hpp"
#include <fstream>
#include <iostream>
#include <cstring>
extern "C" {
#include "../../random/random.h"
}
using namespace dh2::data;using Raw=std::vector<std::uint8_t>;
static unsigned checks;
static void ck(bool b){if(!b)throw std::runtime_error("Owned V4 check "+std::to_string(checks));++checks;}
static Raw file(const std::string& p){std::ifstream f(p,std::ios::binary);ck(bool(f));return {std::istreambuf_iterator<char>(f),{}};}
static void w(Raw& b,std::uint32_t n){for(int i=0;i<4;++i)b.push_back(std::uint8_t(n>>(8*i)));}
static std::int32_t si(std::uint32_t n){std::int32_t x;std::memcpy(&x,&n,4);return x;}
static std::uint32_t rd(const Raw& b,std::size_t& at){ck(at<=b.size()&&b.size()-at>=4);std::uint32_t n;std::memcpy(&n,b.data()+at,4);at+=4;return n;}
struct BorrowedRandom{dh2_random_state live{{1,0x98765432u},{0,3}};LootRandom8V2 fixture{1,0};unsigned draws{};};
static bool live_random(void* context,std::int32_t bound,std::uint32_t stream,std::int32_t& value,std::string& error){if(!context){error="missing live random state";return false;}auto& r=*static_cast<BorrowedRandom*>(context);if(stream!=0){error="V4 fixture requested an unsupported RNG stream";return false;}auto live_value=dh2_random_next(&r.live,std::uint32_t(bound),stream);std::int32_t fixture_value{};if(dh2_loot_v2_random(&r.fixture,bound,&fixture_value)!=0||live_value!=fixture_value||r.live.seeds[0]!=r.fixture.seed||r.live.counters[0]!=r.fixture.calls){error="borrowed RNG diverged from fixture stream";return false;}value=live_value;++r.draws;return true;}
static void seed_borrowed_random(BorrowedRandom& r,std::uint32_t seed,std::uint32_t calls){r.live.seeds[0]=seed;r.live.seeds[1]=0x98765432u;r.live.counters[0]=calls;r.live.counters[1]=3;r.fixture={seed,calls};r.draws=0;}
static Raw snap(const FreshInventoryOwnedV4& o){Raw b;w(b,std::uint32_t(o.gold()));w(b,o.current_equipment());w(b,o.items().size());std::uint32_t potion=UINT32_MAX;for(std::size_t i=0;i<o.items().size();++i){const auto& s=*o.items()[i];const auto& p=*s.item;if(o.potion()==&p)potion=std::uint32_t(i);for(auto n:{std::uint32_t(p.id),std::uint32_t(p.quantity),std::uint32_t(p.value),std::uint32_t(p.identified),std::uint32_t(std::uint8_t(s.slots[0])),std::uint32_t(std::uint8_t(s.slots[1])),std::uint32_t(p.powers.size())})w(b,n);for(auto n:p.powers)w(b,n);}w(b,potion);for(const auto& set:o.equipment())for(auto* p:set){std::uint32_t n=UINT32_MAX;for(std::size_t i=0;i<o.items().size();++i)if(p==o.items()[i].get())n=std::uint32_t(i);w(b,n);}return b;}
struct Context{Raw requests;unsigned delivered{},reentries{},destroyed{},fullness{},pickup_calls{};int fail{-1},minimal{},mutation{},infinite{},pickup_item_id{-1};bool toggle_stats{},copy_powers{},fail_pickup{};bool legacy{};FreshInventoryOwnedV4* pickup_owner{};};
static bool after_pickup(void* p,std::uintptr_t character,std::int32_t item_id,std::string& e){auto& c=*static_cast<Context*>(p);++c.pickup_calls;c.pickup_item_id=item_id;if(!c.pickup_owner||c.pickup_owner->character()!=character||!c.pickup_owner->world_items().empty()){e="pickup callback ran before world transfer committed";return false;}bool found=false;for(const auto& slot:c.pickup_owner->items())if(slot&&slot->item&&slot->item->id==item_id)found=true;if(!found){e="pickup callback did not observe transferred inventory Item";return false;}if(c.fail_pickup){e="fixture GatherLoot async failure";return false;}e.clear();return true;}
static bool service(void* p,FreshInventoryOwnedV4& o,const OwnedInventoryRequestV4& q,OwnedInventoryResponseV4& out,std::string& e){auto& c=*static_cast<Context*>(p);if(int(c.delivered++)==c.fail){e="Missing genuine effect fixture";return false;}auto op=std::uint32_t(q.operation);if(op==0x3fdfd8||op==0x3ff7a8)return true;auto caller=(op==0x337888||op==0x337a88||op==0x31f594||op==0x3e08a8||op==0x3a999c||op==0x3bd140)?q.source_caller:0;
 // V2's controlled fullness result is not an original fullness proof. The new
 // Debug prefix is independently gold-compared in V4, omitted ONLY in the old
 // regression request normalization so old frozen receipts stay untouched.
 if(c.legacy&&(q.source_caller==0x3fe364||q.source_caller==0x3fe3a8)){out.value=0;return true;}
 auto* i=q.item;auto arg=op==0x337a88&&q.source_caller==0x40411c&&c.minimal?1:op==0x337a88&&q.source_caller==0x3fe3a8?c.infinite:0;
 for(auto v:{op,caller,i?std::uint32_t(i->id):0,i?std::uint32_t(i->quantity):0,i?std::uint32_t(i->value):0,std::uint32_t(arg),q.index})w(c.requests,v);
 if(op==0x337a88){ck(q.name);out.value=arg;}else if(op==0x3fb290&&c.mutation==1)i->id=925;else if(op==0x3fb754&&c.mutation==2&&i->value)i->id=925;
 if(op==0x3fbc60&&c.copy_powers&&i)i->powers.push_back(q.argument);
 if(op==0x3fb290&&c.toggle_stats&&i->signed_quantity()>1){o.swap_equipment();o.properties()->resolved[202]^=1;}
 if(op==0x3fb290){std::string nested;ck(!o.add_fixed_loot(165,{&c,service},nested)&&!nested.empty());++c.reentries;}
 return true;}
static void observed(void* p,FreshInventoryOwnedV4&,const OwnedInventoryRequestV4& q){auto& c=*static_cast<Context*>(p);if(q.operation==OwnedInventoryOperationV4::destroy_item)++c.destroyed;if(q.operation==OwnedInventoryOperationV4::inventory_full)++c.fullness;if(c.legacy){auto* i=q.item;for(auto v:{std::uint32_t(q.operation),0u,i?std::uint32_t(i->id):0,i?std::uint32_t(i->quantity):0,i?std::uint32_t(i->value):0,0u,q.index})w(c.requests,v);}}
static Raw synthetic_records(const Raw& records,const ItemTable& table,std::uint32_t id){Raw next=records;if(id==UINT32_MAX)return next;std::size_t at=table.data_begin+4;for(std::uint32_t i=0;i<=id;++i){ck(at+4<=next.size());std::uint32_t length;std::memcpy(&length,next.data()+at,4);at+=4+length+16;ck(at<next.size());if(i==id){next[at]=1;return next;}at+=1+44;ck(at+4<=next.size());std::memcpy(&length,next.data()+at,4);at+=4+length+80;}throw std::runtime_error("Synthetic record index");}
static std::uint32_t perform(FreshInventoryOwnedV4& o,const OwnedInventoryServicesV4& s,std::uint32_t op,std::uint32_t a,std::uint32_t b,std::uint32_t c,std::string& e){std::int32_t result=0;bool ok=true;switch(op){case 0:ok=o.add_fixed_loot(si(a),s,e);break;case 1:{std::unique_ptr<ItemInstanceV1> p;ok=o.create_item(si(a),b,p,s,e)&&o.add_item(p,c&1,c&2,result,s,e);break;}case 2:ok=o.character_auto_equip(a,result,s,e);break;case 3:ok=o.equip_to_slot(a,b,c,s,e);break;case 4:ok=o.unequip_from_slot(a,si(b),s,e);break;case 5:o.swap_equipment();break;case 6:ok=o.add_gold(si(a),s,e);break;case 7:{std::unique_ptr<ItemInstanceV1> p;ok=a<o.items().size()&&o.split_item(*o.items()[a]->item,si(b),p,s,e);if(ok){if(p)ok=o.add_item(p,c&1,c&2,result,s,e);else result=-1;}break;}case 8:o.project_potion_capacity(std::int8_t(a));break;case 9:o.properties()->resolved[202]=si(a);o.properties()->resolved[203]=si(b);break;case 10:o.project_gold_limit(si(a));break;case 11:{bool eq=false,two=false;ok=o.is_equipped(a,eq,e)&&o.has_two_hander(b!=0,two,e);result=int(eq)|(int(two)<<1);break;}case 12:{bool full;ok=o.inventory_full(full,s,e);result=full;break;}case 13:o.project_unlimited(a!=0);break;case 14:static_cast<Context*>(s.context)->infinite=si(a);break;default:ok=false;}if(!ok)throw std::runtime_error("Required V4 step failed "+std::to_string(op)+": "+e);return std::uint32_t(result);}
static void random_and_item_checks(){
 for(const auto quantity:std::array<std::uint16_t,4>{{0,1,0x7fff,0xfffe}}){ItemInstanceV1 instance;instance.quantity=quantity;std::int16_t signed_value;std::memcpy(&signed_value,&quantity,2);ck(instance.signed_quantity()==signed_value);}
 for(const std::uint32_t seed:std::array<std::uint32_t,5>{{0,1,0x7fffffff,0x80000000,0xffffffff}})for(const std::int32_t bound:std::array<std::int32_t,5>{{0,1,7,100,-1}}){LootRandom8V2 fixture_rng{seed,9};dh2_random_state live_rng{{seed,0x98765432},{9,3}};std::int32_t fixture_value=0;ck(dh2_loot_v2_random(&fixture_rng,bound,&fixture_value)==0);auto live_value=dh2_random_next(&live_rng,std::uint32_t(bound),0);ck(fixture_value==live_value&&fixture_rng.seed==live_rng.seeds[0]&&fixture_rng.calls==live_rng.counters[0]&&live_rng.seeds[1]==0x98765432&&live_rng.counters[1]==3);}
}
struct DropContextV4{bool online{},fail_query{},fail_spawn{};unsigned queries{},spawns{};ItemInstanceV1* item{};std::size_t index=SIZE_MAX;bool owner_matches{};};
static bool drop_online(void* p,bool& online,std::string& error){auto& c=*static_cast<DropContextV4*>(p);++c.queries;if(c.fail_query){error="fixture online query failure";return false;}online=c.online;error.clear();return true;}
static bool drop_spawn(void* p,FreshInventoryOwnedV4& owner,std::size_t index,ItemInstanceV1* item,std::string& error){auto& c=*static_cast<DropContextV4*>(p);++c.spawns;c.item=item;c.index=index;c.owner_matches=index<owner.world_items().size()&&owner.world_items()[index]&&owner.world_items()[index]->item.get()==item;if(!c.owner_matches){error="fixture drop provider received a non-owned Item";return false;}if(c.fail_spawn){error="fixture source spawn/lock provider failure";return false;}error.clear();return true;}
static void gathering_id_registration_checks(const LootTablesV2::Borrow& tables){
 if(tables.items().rows.empty())throw std::runtime_error("Gathering-ID checks require at least one ItemTable row");
 LootRandom8V2 rng{1,0};FreshInventoryOwnedV4 owner(0x100000001,tables,rng,12,std::make_shared<PropertyState>());
 std::string error;bool registered=true;const std::int32_t first=0;
 ck(owner.has_quest_gathering_item_id(first,registered,error)&&!registered);
 ck(!owner.unregister_quest_gathering_item_id(first,error)&&!error.empty());
 ck(owner.register_quest_gathering_item_id(first,error)&&error.empty());
 ck(owner.register_quest_gathering_item_id(first,error)&&error.empty());
 ck(owner.has_quest_gathering_item_id(first,registered,error)&&registered);
 if(tables.items().rows.size()>1){
  LootRandom8V2 other_rng{1,0};FreshInventoryOwnedV4 other(0x100000002,tables,other_rng,12,std::make_shared<PropertyState>());
  ck(other.has_quest_gathering_item_id(first,registered,error)&&!registered);
  ck(owner.register_quest_gathering_item_id(1,error));
  ck(owner.has_quest_gathering_item_id(1,registered,error)&&registered);
 }
 ck(owner.unregister_quest_gathering_item_id(first,error));
 ck(owner.has_quest_gathering_item_id(first,registered,error)&&registered);
 ck(owner.unregister_quest_gathering_item_id(first,error));
 ck(owner.has_quest_gathering_item_id(first,registered,error)&&!registered);
 ck(!owner.unregister_quest_gathering_item_id(first,error)&&!error.empty());
 for(unsigned count=0;count<255;++count)ck(owner.register_quest_gathering_item_id(first,error));
 ck(!owner.register_quest_gathering_item_id(first,error)&&!error.empty());
 for(unsigned count=0;count<255;++count)ck(owner.unregister_quest_gathering_item_id(first,error));
 ck(owner.has_quest_gathering_item_id(first,registered,error)&&!registered);
 const auto invalid=std::int32_t(tables.items().rows.size());
 ck(!owner.register_quest_gathering_item_id(-1,error)&&!error.empty());
 ck(!owner.unregister_quest_gathering_item_id(invalid,error)&&!error.empty());
 registered=true;ck(!owner.has_quest_gathering_item_id(-1,registered,error)&&!registered&&!error.empty());
}
static void offline_world_transfer_checks(const char* cache_path){
 auto records=file(std::string(cache_path)+"/loot_table_pyarray.bin"),names=file(std::string(cache_path)+"/loot_table_pyarraynames.bin"),schema=file(std::string(cache_path)+"/loot_table_pystructnames.bin");LootTablesV2 table;std::string e;ck(table.load({records.data(),records.size()},{names.data(),names.size()},{schema.data(),schema.size()},e));
 gathering_id_registration_checks(table.borrow());
 const auto& rows=table.borrow().items().rows;std::int32_t stackable=-1,equippable=-1,potion=-1;std::int32_t equip_slot=-1;
 for(std::size_t i=0;i<rows.size();++i){const auto& row=rows[i];const auto id=std::int32_t(i),type=item_type(row),slot=row.record.words[26];if(stackable<0&&std::uint8_t(row.record.words[7])&&slot==-1&&type!=13&&type!=14)stackable=id;if(equippable<0&&!std::uint8_t(row.record.words[7])&&slot>=0&&slot<9&&type!=13&&type!=14){equippable=id;equip_slot=slot;}if(potion<0&&type==14)potion=id;}
 // The current asset cache only exposes a stackable potion, not the older
 // non-potion stack fixture. It still exercises source one-unit stack drops.
 if(stackable<0)stackable=potion;
 ck(stackable>=0&&equippable>=0&&potion>=0);
 auto services_for=[](Context& context){return OwnedInventoryServicesV4{&context,service,observed,true,after_pickup};};
 auto add_item=[&](FreshInventoryOwnedV4& owner,Context& context,std::int32_t id,std::uint16_t quantity,std::vector<std::int32_t> powers){auto value=std::make_unique<ItemInstanceV1>();value->id=id;value->quantity=quantity;value->value=321;value->identified=1;value->powers=std::move(powers);std::int32_t index=-1;ck(owner.add_item(value,true,false,index,services_for(context),e)&&!value&&index>=0);return std::uint32_t(index);};
 auto drop_services=[](DropContextV4& context){return OfflineWorldItemDropServicesV4{&context,drop_online,drop_spawn};};
 // Online status and both mandatory source providers are checked before the
 // owner mutates the inventory. Unsupported online mode cannot silently fall
 // through to a local-only world item.
 {LootRandom8V2 rng{1,0};FreshInventoryOwnedV4 owner(1,table.borrow(),rng,12,std::make_shared<PropertyState>());Context inventory;auto index=add_item(owner,inventory,stackable,1,{});auto* identity=owner.items()[index]->item.get();DropContextV4 provider;provider.online=true;std::int32_t world=-1;ck(!owner.drop_inventory_item_offline(index,services_for(inventory),drop_services(provider),world,e));ck(e.find("Online inventory drop is unsupported")!=std::string::npos&&owner.items().size()==1&&owner.items()[0]->item.get()==identity&&owner.world_items().empty()&&provider.spawns==0);}
 {LootRandom8V2 rng{1,0};FreshInventoryOwnedV4 owner(1,table.borrow(),rng,12,std::make_shared<PropertyState>());Context inventory;auto index=add_item(owner,inventory,stackable,1,{});auto* identity=owner.items()[index]->item.get();DropContextV4 provider;OfflineWorldItemDropServicesV4 missing{&provider,drop_online,nullptr};std::int32_t world=-1;ck(!owner.drop_inventory_item_offline(index,services_for(inventory),missing,world,e));ck(e.find("scatter/ItemManager/player-lock provider unavailable")!=std::string::npos&&owner.items().size()==1&&owner.items()[0]->item.get()==identity&&owner.world_items().empty()&&provider.queries==1);}
 {LootRandom8V2 rng{1,0};FreshInventoryOwnedV4 owner(1,table.borrow(),rng,12,std::make_shared<PropertyState>());Context inventory;auto index=add_item(owner,inventory,stackable,1,{});auto* identity=owner.items()[index]->item.get();OfflineWorldItemDropServicesV4 missing{};std::int32_t world=-1;ck(!owner.drop_inventory_item_offline(index,services_for(inventory),missing,world,e));ck(e.find("online-session query unavailable")!=std::string::npos&&owner.items()[0]->item.get()==identity&&owner.world_items().empty());}
 // A stacked item uses the source split path: one powered copy moves into the
 // same V4 owner's world vector while the original stack remains in inventory.
 {LootRandom8V2 rng{1,0};FreshInventoryOwnedV4 owner(1,table.borrow(),rng,12,std::make_shared<PropertyState>());Context inventory;inventory.copy_powers=true;auto index=add_item(owner,inventory,stackable,3,{7,19});auto* original=owner.items()[index]->item.get();DropContextV4 provider;std::int32_t world=-1;ck(owner.drop_inventory_item_offline(index,services_for(inventory),drop_services(provider),world,e));ck(world==0&&owner.items().size()==1&&owner.items()[0]->item.get()==original&&original->signed_quantity()==2&&owner.world_items().size()==1);auto* split=owner.world_items()[0]->item.get();const auto split_id=split->id;ck(split!=original&&split->id==original->id&&split->signed_quantity()==1&&split->value==original->value&&split->identified==original->identified&&split->powers==original->powers);ck(provider.queries==1&&provider.spawns==1&&provider.owner_matches&&provider.item==split&&provider.index==0);ck(provider.owner_matches&&provider.item==split&&provider.index==0);inventory.pickup_owner=&owner;std::int32_t inventory_index=-1;ck(owner.pickup_world_item(0,inventory_index,services_for(inventory),e));ck(inventory.pickup_calls==1&&inventory.pickup_item_id==split_id&&owner.world_items().empty()&&inventory_index==std::int32_t(index)&&original->signed_quantity()==3);}
 // A failed quest async tail occurs after TransferInventoryTo: retain the
 // accepted inventory prefix, retire the world drop, and never replay it.
 {LootRandom8V2 rng{1,0};FreshInventoryOwnedV4 owner(1,table.borrow(),rng,12,std::make_shared<PropertyState>());Context inventory;auto index=add_item(owner,inventory,stackable,2,{});DropContextV4 provider;std::int32_t world=-1;ck(owner.drop_inventory_item_offline(index,services_for(inventory),drop_services(provider),world,e));inventory.pickup_owner=&owner;inventory.fail_pickup=true;std::int32_t inventory_index=-1;ck(!owner.pickup_world_item(std::size_t(world),inventory_index,services_for(inventory),e));ck(e=="fixture GatherLoot async failure"&&inventory.pickup_calls==1&&owner.world_items().empty()&&owner.items().size()==1&&owner.items()[0]->item->signed_quantity()==2);ck(!owner.pickup_world_item(std::size_t(world),inventory_index,services_for(inventory),e)&&inventory.pickup_calls==1);}
 // AutoTransmute shares the V4 transfer/merge owner but bypasses the normal
 // GatherLoot tail. Return the retained merge target, never the destroyed
 // world Item pointer, so the subsequent consume targets the correct Item.
 {LootRandom8V2 rng{1,0};FreshInventoryOwnedV4 owner(1,table.borrow(),rng,12,std::make_shared<PropertyState>());Context inventory;const auto index=add_item(owner,inventory,stackable,2,{});auto* retained=owner.items()[index]->item.get();DropContextV4 provider;std::int32_t world=-1;ck(owner.drop_inventory_item_offline(index,services_for(inventory),drop_services(provider),world,e));auto* source=owner.world_items()[std::size_t(world)]->item.get();ck(source&&source!=retained&&source->signed_quantity()==1);inventory.pickup_owner=&owner;std::int32_t destination_index=-1;std::uintptr_t destination_identity=0;ck(owner.transfer_world_item_for_auto_transmute(std::size_t(world),destination_index,destination_identity,services_for(inventory),e)==WorldItemTransferResultV4::committed);ck(owner.world_items().empty()&&destination_index==std::int32_t(index)&&destination_identity==reinterpret_cast<std::uintptr_t>(retained)&&destination_identity!=reinterpret_cast<std::uintptr_t>(source)&&retained->signed_quantity()==3&&inventory.pickup_calls==0);}
 // Whole equipped-item transfer keeps the exact Item identity and clears both
 // V4 equipment pointers before moving its existing slot to world_items_.
 {LootRandom8V2 rng{1,0};FreshInventoryOwnedV4 owner(1,table.borrow(),rng,12,std::make_shared<PropertyState>());Context inventory;auto index=add_item(owner,inventory,equippable,1,{});auto* identity=owner.items()[index]->item.get();ck(owner.equip_to_slot(std::uint32_t(equip_slot),index,false,services_for(inventory),e));ck(owner.equipment()[0][std::size_t(equip_slot)]==owner.items()[index].get());DropContextV4 provider;std::int32_t world=-1;ck(owner.drop_inventory_item_offline(index,services_for(inventory),drop_services(provider),world,e));ck(world==0&&owner.items().empty()&&owner.world_items().size()==1&&owner.world_items()[0]->item.get()==identity);for(const auto& set:owner.equipment())for(auto* cell:set)ck(cell==nullptr);ck(owner.world_items()[0]->slots[0]==-1&&owner.world_items()[0]->slots[1]==-1&&provider.owner_matches);}
 // The source ItemManager/provider runs after ownership has moved. A failed
 // native spawn leaves that single world Item retained, reports its index and
 // never destroys or duplicates the inventory payload.
 {LootRandom8V2 rng{1,0};FreshInventoryOwnedV4 owner(1,table.borrow(),rng,12,std::make_shared<PropertyState>());Context inventory;auto index=add_item(owner,inventory,potion,1,{});auto* identity=owner.items()[index]->item.get();ck(owner.potion()==identity);DropContextV4 provider;provider.fail_spawn=true;std::int32_t world=-1;ck(!owner.drop_inventory_item_offline(index,services_for(inventory),drop_services(provider),world,e));ck(world==0&&owner.items().empty()&&owner.potion()==nullptr&&owner.world_items().size()==1&&owner.world_items()[0]->item.get()==identity&&provider.owner_matches&&e=="fixture source spawn/lock provider failure");}
 // Ctrl_UsePotion reaches RemoveOnePotion: AddQty(-1) for a stack, direct
 // source-item retirement for the last unit, with one canonical potion alias.
 {LootRandom8V2 rng{1,0};FreshInventoryOwnedV4 owner(1,table.borrow(),rng,12,std::make_shared<PropertyState>());Context inventory;auto index=add_item(owner,inventory,potion,3,{});auto* identity=owner.items()[index]->item.get();ck(owner.potion()==identity);ck(owner.remove_one_potion(services_for(inventory),e));ck(owner.potion()==identity&&owner.items().size()==1&&owner.items()[0]->item.get()==identity&&identity->signed_quantity()==2&&inventory.destroyed==0);}
 {LootRandom8V2 rng{1,0};FreshInventoryOwnedV4 owner(1,table.borrow(),rng,12,std::make_shared<PropertyState>());Context inventory;add_item(owner,inventory,potion,1,{});auto* identity=owner.potion();ck(identity&&owner.remove_one_potion(services_for(inventory),e));ck(owner.potion()==nullptr&&owner.items().empty()&&inventory.destroyed==1);}
 std::cout<<"{\"validation\":\"PASS\",\"offline_world_transfer_cases\":8,\"potion_removal_cases\":2,\"checks\":"<<checks<<",\"online_drops_rejected\":true,\"pickup_quest_tail_prefix_preserved\":true,\"auto_transmute_uses_canonical_merge_target_without_quest_tail\":true}\n";
}
static void borrowed_corpus(const char* gold_path,const char* legacy_path,const char* cache_path){
 auto records=file(std::string(cache_path)+"/loot_table_pyarray.bin"),names=file(std::string(cache_path)+"/loot_table_pyarraynames.bin"),schema=file(std::string(cache_path)+"/loot_table_pystructnames.bin");LootTablesV2 table;std::string e;ck(table.load({records.data(),records.size()},{names.data(),names.size()},{schema.data(),schema.size()},e));
 gathering_id_registration_checks(table.borrow());
 auto gold=file(gold_path);std::size_t at=0;ck(rd(gold,at)==0x34564f49);auto cases=rd(gold,at);unsigned steps=0,requests=0,draws=0;std::uint32_t owner_cases=0;
 for(unsigned k=0;k<cases;++k){auto cap=std::int8_t(rd(gold,at));auto flags=rd(gold,at),selected=rd(gold,at),synthetic=rd(gold,at),n=rd(gold,at);auto rec=synthetic_records(records,table.borrow().items(),synthetic);LootTablesV2 selected_table;ck(selected_table.load({rec.data(),rec.size()},{names.data(),names.size()},{schema.data(),schema.size()},e));PropertyState props{};props.resolved[202]=flags&1;props.resolved[203]=flags>>1;BorrowedRandom random;seed_borrowed_random(random,1,0);FreshInventoryOwnedV4 o(UINT64_C(0x123400005678),selected_table.borrow(),{&random,live_random},cap,props);ck(o.properties()==&props);o.project_gold_limit(10000);if(selected)o.swap_equipment();Context ctx;ctx.toggle_stats=flags&0x100;OwnedInventoryServicesV4 svc{&ctx,service,observed,true};
  for(unsigned j=0;j<n;++j){auto op=rd(gold,at),a=rd(gold,at),b=rd(gold,at),c=rd(gold,at),expected=rd(gold,at),size=rd(gold,at);ck(size<=gold.size()-at);Raw state(gold.begin()+at,gold.begin()+at+size);at+=size;auto nr=rd(gold,at);ck(nr*28<=gold.size()-at);Raw req(gold.begin()+at,gold.begin()+at+nr*28);at+=nr*28;ctx.requests.clear();auto result=perform(o,svc,op,a,b,c,e);ck(o.properties()==&props);if(result!=expected||snap(o)!=state)throw std::runtime_error("Borrowed original V4 state mismatch case "+std::to_string(k)+" step "+std::to_string(j)+" op "+std::to_string(op));if(ctx.requests!=req)throw std::runtime_error("Borrowed original V4 request mismatch case "+std::to_string(k)+" step "+std::to_string(j));ck(random.live.seeds[0]==random.fixture.seed&&random.live.counters[0]==random.fixture.calls&&random.live.seeds[1]==0x98765432u&&random.live.counters[1]==3);++steps;requests+=nr;}
  draws+=random.draws;++owner_cases;
 }
 ck(at==gold.size());auto legacy=file(legacy_path);at=0;ck(rd(legacy,at)==0x32564946);auto prior=rd(legacy,at);for(unsigned k=0;k<prior;++k){LootRandom8V2 initial{rd(legacy,at),rd(legacy,at)};auto cap=std::int8_t(rd(legacy,at));Context ctx;ctx.legacy=true;ctx.minimal=rd(legacy,at);ctx.mutation=rd(legacy,at);auto loot=si(rd(legacy,at));auto expected_seed=rd(legacy,at),expected_calls=rd(legacy,at),size=rd(legacy,at);ck(size<=legacy.size()-at);Raw expected(legacy.begin()+at,legacy.begin()+at+size);at+=size;auto nr=rd(legacy,at);ck(nr*28<=legacy.size()-at);Raw req(legacy.begin()+at,legacy.begin()+at+nr*28);at+=nr*28;PropertyState props{};BorrowedRandom random;seed_borrowed_random(random,initial.seed,initial.calls);FreshInventoryOwnedV4 o(1,table.borrow(),{&random,live_random},cap,props);ck(o.properties()==&props);ck(o.add_fixed_loot(loot,{&ctx,service,observed,true},e));ck(o.properties()==&props);ck(snap(o)==expected);ck(ctx.requests==req);ck(random.live.seeds[0]==expected_seed&&random.live.counters[0]==expected_calls);ck(random.fixture.seed==expected_seed&&random.fixture.calls==expected_calls&&random.live.seeds[1]==0x98765432u&&random.live.counters[1]==3);draws+=random.draws;++owner_cases;}
 ck(at==legacy.size());std::cout<<"{\"validation\":\"PASS\",\"borrowed_mode\":true,\"borrowed_owner_cases\":"<<owner_cases<<",\"original_owned_cases\":"<<cases<<",\"original_owned_steps\":"<<steps<<",\"source_effect_requests\":"<<requests<<",\"legacy_loot_regressions\":"<<prior<<",\"borrowed_rng_draws\":"<<draws<<",\"property_alias_checks\":"<<owner_cases+steps*2<<",\"checks\":"<<checks<<",\"mismatches\":0}\n";
}
int main(int argc,char** argv){try{if(argc==2&&std::string(argv[1])=="--random-only"){random_and_item_checks();std::cout<<"{\"validation\":\"PASS\",\"checks\":"<<checks<<",\"source_rng_adapter\":true,\"cache_required\":false}\n";return 0;}if(argc==3&&std::string(argv[1])=="--world-transfer-only"){offline_world_transfer_checks(argv[2]);return 0;}if(argc==5&&std::string(argv[1])=="--borrowed"){borrowed_corpus(argv[2],argv[3],argv[4]);return 0;}ck(argc==4);auto records=file(std::string(argv[3])+"/loot_table_pyarray.bin"),names=file(std::string(argv[3])+"/loot_table_pyarraynames.bin"),schema=file(std::string(argv[3])+"/loot_table_pystructnames.bin");LootTablesV2 table;std::string e;ck(table.load({records.data(),records.size()},{names.data(),names.size()},{schema.data(),schema.size()},e));gathering_id_registration_checks(table.borrow());auto gold=file(argv[1]);std::size_t at=0;ck(rd(gold,at)==0x34564f49);auto cases=rd(gold,at);unsigned steps=0,requests=0,destroyed=0,fullness=0,guards=0;
 for(unsigned k=0;k<cases;++k){auto cap=std::int8_t(rd(gold,at));auto flags=rd(gold,at),selected=rd(gold,at),synthetic=rd(gold,at),n=rd(gold,at);auto rec=synthetic_records(records,table.borrow().items(),synthetic);LootTablesV2 selected_table;ck(selected_table.load({rec.data(),rec.size()},{names.data(),names.size()},{schema.data(),schema.size()},e));LootRandom8V2 r{1,0};auto props=std::make_shared<PropertyState>();props->resolved[202]=flags&1;props->resolved[203]=flags>>1;FreshInventoryOwnedV4 o(UINT64_C(0x123400005678),selected_table.borrow(),r,cap,props);o.project_gold_limit(10000);if(selected)o.swap_equipment();Context ctx;ctx.toggle_stats=flags&0x100;OwnedInventoryServicesV4 svc{&ctx,service,observed,true};
  for(unsigned j=0;j<n;++j){auto op=rd(gold,at),a=rd(gold,at),b=rd(gold,at),c=rd(gold,at),expected=rd(gold,at),size=rd(gold,at);ck(size<=gold.size()-at);Raw state(gold.begin()+at,gold.begin()+at+size);at+=size;auto nr=rd(gold,at);ck(nr*28<=gold.size()-at);Raw req(gold.begin()+at,gold.begin()+at+nr*28);at+=nr*28;ctx.requests.clear();auto result=perform(o,svc,op,a,b,c,e);if(result!=expected||snap(o)!=state)throw std::runtime_error("Original V4 state mismatch case "+std::to_string(k)+" step "+std::to_string(j)+" op "+std::to_string(op));if(ctx.requests!=req){std::size_t m=0;while(m<std::min(req.size(),ctx.requests.size())&&req[m]==ctx.requests[m])++m;throw std::runtime_error("Original V4 request mismatch "+std::to_string(k)+"/"+std::to_string(j)+" byte "+std::to_string(m));}++steps;requests+=nr;}
  destroyed+=ctx.destroyed;fullness+=ctx.fullness;guards+=ctx.reentries;
 }
 ck(at==gold.size());auto legacy=file(argv[2]);at=0;ck(rd(legacy,at)==0x32564946);auto prior=rd(legacy,at);for(unsigned k=0;k<prior;++k){LootRandom8V2 r{rd(legacy,at),rd(legacy,at)};auto cap=std::int8_t(rd(legacy,at));Context c;c.legacy=true;c.minimal=rd(legacy,at);c.mutation=rd(legacy,at);auto loot=si(rd(legacy,at));auto seed=rd(legacy,at),calls=rd(legacy,at),size=rd(legacy,at);ck(size<=legacy.size()-at);Raw expected(legacy.begin()+at,legacy.begin()+at+size);at+=size;auto nr=rd(legacy,at);ck(nr*28<=legacy.size()-at);Raw req(legacy.begin()+at,legacy.begin()+at+nr*28);at+=nr*28;FreshInventoryOwnedV4 o(1,table.borrow(),r,cap,std::make_shared<PropertyState>());ck(o.add_fixed_loot(loot,{&c,service,observed,true},e));ck(snap(o)==expected);ck(c.requests==req);ck(r.seed==seed&&r.calls==calls);guards+=c.reentries;}ck(at==legacy.size());
 for(int fail=0;fail<24;++fail){LootRandom8V2 r{1,0};FreshInventoryOwnedV4 o(1,table.borrow(),r,12,std::make_shared<PropertyState>());Context c;c.fail=fail;ck(!o.add_fixed_loot(165,{&c,service,nullptr,true},e));ck(e=="Missing genuine effect fixture");++guards;}
 {LootRandom8V2 r{1,0};FreshInventoryOwnedV4 o(1,table.borrow(),r,12,std::make_shared<PropertyState>());std::int32_t result;ck(!o.auto_equip(0,result,{},e));ck(!o.unequip_from_slot(9,-1,{},e));ck(!o.set_gold(-1,{},e));std::unique_ptr<ItemInstanceV1> p;ck(!o.create_item(-1,1,p,{},e)&&!p);ck(!o.add_fixed_loot(165,{},e)&&o.items().empty());guards+=5;}
 // The live constructor aliases the caller's PropertyState and RNG. The
 // callback adapter uses the existing two-stream DH2 random owner; this
 // regression checks it against the imported V4 fixture stream.
 random_and_item_checks();
 {LootRandom8V2 fixture_rng{1,0};BorrowedRandom live_rng;seed_borrowed_random(live_rng,1,0);auto fixture_properties=std::make_shared<PropertyState>();PropertyState live_properties;live_properties.resolved[202]=fixture_properties->resolved[202]=1;FreshInventoryOwnedV4 fixture(UINT64_C(0x123400005678),table.borrow(),fixture_rng,12,fixture_properties);FreshInventoryOwnedV4 live(UINT64_C(0x123400005678),table.borrow(),{&live_rng,live_random},12,live_properties);ck(live.properties()==&live_properties);Context a,b;OwnedInventoryServicesV4 fixture_services{&a,service,observed,true},live_services{&b,service,observed,true};ck(fixture.add_fixed_loot(165,fixture_services,e));ck(live.add_fixed_loot(165,live_services,e));ck(snap(fixture)==snap(live)&&a.requests==b.requests&&live.properties()==&live_properties);ck(fixture_rng.seed==live_rng.live.seeds[0]&&fixture_rng.calls==live_rng.live.counters[0]&&live_rng.live.seeds[1]==0x98765432u&&live_rng.live.counters[1]==3);}
 std::cout<<"{\"validation\":\"PASS\",\"original_owned_cases\":"<<cases<<",\"original_owned_steps\":"<<steps<<",\"source_effect_requests\":"<<requests<<",\"legacy_loot_regressions\":"<<prior<<",\"native_item_deletions\":"<<destroyed<<",\"native_fullness_queries\":"<<fullness<<",\"guards\":"<<guards<<",\"checks\":"<<checks<<",\"mismatches\":0}\n";return 0;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
