#include "../fresh_inventory_owned_v4.hpp"
#include <fstream>
#include <iostream>
#include <cstring>
using namespace dh2::data;using Raw=std::vector<std::uint8_t>;static unsigned checks;
extern "C" std::uint32_t dh2_item_presentation_fixture_v5(const std::uint8_t*,std::uint8_t*);
extern "C" std::uint32_t dh2_item_power_instance_fixture_v5(const std::uint8_t*,std::uint8_t*);
static void ck(bool b){if(!b)throw std::runtime_error("Presentation V5 check "+std::to_string(checks));++checks;}
static Raw file(const std::string& p){std::ifstream f(p,std::ios::binary);ck(bool(f));return {std::istreambuf_iterator<char>(f),{}};}
static void word(Raw& b,std::uint32_t x){auto* p=reinterpret_cast<std::uint8_t*>(&x);b.insert(b.end(),p,p+4);}
struct Reader{const Raw& b;std::size_t at{};std::uint32_t u(){ck(b.size()-at>=4);std::uint32_t x;std::memcpy(&x,b.data()+at,4);at+=4;return x;}Raw block(){auto n=u();ck(b.size()-at>=n);Raw out(b.begin()+at,b.begin()+at+n);at+=n;return out;}};
int main(int argc,char** argv){try{ck(argc==4);auto gold=file(argv[1]);ck(!std::memcmp(gold.data(),"PRV5",4));Reader r{gold,4};auto count=r.u();Raw out(1024*1024);for(unsigned j=0;j<count;++j){auto input=r.block(),expected=r.block();auto n=dh2_item_presentation_fixture_v5(input.data(),out.data());ck(n==expected.size()&&std::equal(expected.begin(),expected.end(),out.begin()));}ck(r.at==gold.size());
 Raw cache;for(auto name:{"item_powers_pyarray.bin","item_powers_pyarraynames.bin","item_powers_pystructnames.bin"}){auto b=file(std::string(argv[3])+"/"+name);word(cache,b.size());cache.insert(cache.end(),b.begin(),b.end());}
 auto powers=file(argv[2]);ck(!std::memcmp(powers.data(),"PIV5",4));Reader pr{powers,4};auto power_cases=pr.u();for(unsigned j=0;j<power_cases;++j){auto input=pr.block(),expected=pr.block();Raw args=cache;args.insert(args.end(),input.begin(),input.end());auto n=dh2_item_power_instance_fixture_v5(args.data(),out.data());ck(n==expected.size()&&std::equal(expected.begin(),expected.end(),out.begin()));}ck(pr.at==powers.size());
 Item item;ItemInstanceV1 instance;instance.name="old";item.record.words[17]=1;std::string e;auto meta=[](void* p,const ItemInstanceV1&,std::string&)->const Item*{return static_cast<Item*>(p);};ItemTextServicesV5 svc{&item,meta,nullptr};ck(!item_update_name_v5(instance,svc,e)&&instance.name.empty()&&!e.empty());instance.description="old";ck(!item_update_stats_v5(instance,svc,e)&&instance.description.empty());instance.requirements="old";ck(item_update_requirements_v5(instance,svc,e)&&instance.requirements.empty());item.record.words[17]=-1;ck(item_update_name_v5(instance,svc,e));item.record.words[22]=14;item.record.words[29]=1;ck(item_update_requirements_v5(instance,svc,e));
 ItemPowerTablesV5 tables;auto records=file(std::string(argv[3])+"/item_powers_pyarray.bin"),names=file(std::string(argv[3])+"/item_powers_pyarraynames.bin"),schema=file(std::string(argv[3])+"/item_powers_pystructnames.bin");ck(tables.load({records.data(),records.size()},{names.data(),names.size()},{schema.data(),schema.size()},e));ItemPresentationOwnerV5 owner(tables.borrow());ck(!owner.add_power(instance,-1,0,svc,e)&&instance.powers.empty());ck(!owner.add_power(instance,0,0,svc,e)&&instance.powers.size()==1&&owner.powers(instance)->size()==1);ck(owner.forget(instance,e)&&!owner.powers(instance));instance.powers.clear();ck(!owner.add_power(instance,936,1,svc,e)&&instance.powers.empty());
 struct RefreshText{Item* row{};std::string locale;};RefreshText refresh{&item,"old"};item.record.words[17]=-1;item.record.words[22]=14;ItemTextServicesV5 refresh_services{&refresh,[](void* p,const ItemInstanceV1&,std::string&)->const Item*{return static_cast<RefreshText*>(p)->row;},[](void* p,ItemInstanceV1&,const ItemTextRequestV5& q,ItemTextResponseV5& r,std::string& out,std::string&)->bool{auto& c=*static_cast<RefreshText*>(p);if(q.operation==ItemTextOperationV5::integer_string)r.text=c.locale+":"+std::to_string(q.value);else if(q.operation==ItemTextOperationV5::parse_varargs||q.operation==ItemTextOperationV5::parse_ex)out+=q.input?q.input:"";else if(q.operation==ItemTextOperationV5::constant)r.value=0;else if(q.operation==ItemTextOperationV5::class_name)r.value=0;return true;}};ItemInstanceV1 refreshed;refreshed.name="stale";refreshed.description="stale";refreshed.requirements="stale";ItemPresentationOwnerV5 localized(tables.borrow());ck(localized.add_power(refreshed,0,-1,refresh_services,e));const auto saved_ids=refreshed.powers;refresh.locale="new";ck(localized.update_localization(refreshed,refresh_services,e));ck(refreshed.powers==saved_ids&&refreshed.name.empty()&&refreshed.description.empty()&&refreshed.requirements.empty());ck(localized.powers(refreshed)&&localized.powers(refreshed)->size()==saved_ids.size()&&localized.powers(refreshed)->front().description=="new:"+std::to_string(tables.borrow().rows()[std::size_t(saved_ids.front())].scalars.description));
 auto loot_records=file(std::string(argv[3])+"/loot_table_pyarray.bin"),loot_names=file(std::string(argv[3])+"/loot_table_pyarraynames.bin"),loot_schema=file(std::string(argv[3])+"/loot_table_pystructnames.bin");LootTablesV2 loot;ck(loot.load({loot_records.data(),loot_records.size()},{loot_names.data(),loot_names.size()},{loot_schema.data(),loot_schema.size()},e));struct InventoryEffects{} effects;OwnedInventoryServicesV4 inventory_services{&effects,[](void*,FreshInventoryOwnedV4&,const OwnedInventoryRequestV4& q,OwnedInventoryResponseV4& r,std::string&)->bool{if(q.operation==OwnedInventoryOperationV4::debug_query)r.value=0;return true;},nullptr,true};LootRandom8V2 rng{1,0};auto properties=std::make_shared<PropertyState>();FreshInventoryOwnedV4 inventory(0x1234,loot.borrow(),rng,-1,properties);for(std::int32_t id=0;id<2;++id){auto incoming=std::make_unique<ItemInstanceV1>();incoming->id=id;incoming->quantity=1;std::int32_t index=-1;ck(inventory.add_item(incoming,true,false,index,inventory_services,e)&&!incoming&&index==id);}struct InventoryText{const ItemTable* table{};std::string locale;std::vector<std::int32_t> item_order;};InventoryText inventory_text{&loot.borrow().items(),"new",{}};ItemTextServicesV5 inventory_text_services{&inventory_text,[](void* p,const ItemInstanceV1& x,std::string&)->const Item*{auto& c=*static_cast<InventoryText*>(p);if(c.item_order.empty()||c.item_order.back()!=x.id)c.item_order.push_back(x.id);return dh2::data::item(*c.table,x.id);},[](void* p,ItemInstanceV1&,const ItemTextRequestV5& q,ItemTextResponseV5& r,std::string& out,std::string&)->bool{auto& c=*static_cast<InventoryText*>(p);if(q.operation==ItemTextOperationV5::integer_string)r.text=c.locale+":"+std::to_string(q.value);else if(q.operation==ItemTextOperationV5::parse_varargs||q.operation==ItemTextOperationV5::parse_ex)out+=q.input?q.input:"";else if(q.operation==ItemTextOperationV5::constant||q.operation==ItemTextOperationV5::class_name)r.value=0;return true;}};ItemPresentationOwnerV5 inventory_presentation(tables.borrow());auto* first=inventory.items()[0]->item.get();auto* second=inventory.items()[1]->item.get();ck(inventory.update_localization(inventory_presentation,inventory_text_services,e));ck(inventory.items().size()==2&&inventory.items()[0]->item.get()==first&&inventory.items()[1]->item.get()==second&&inventory_text.item_order==std::vector<std::int32_t>({0,1}));
 std::cout<<"{\"validation\":\"PASS\",\"presentation_original_cases\":"<<count<<",\"power_instance_original_cases\":"<<power_cases<<",\"checks\":"<<checks<<",\"mismatches\":0}\n";return 0;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
