#include "../player_gear_effects_v5.hpp"
#include <fstream>
#include <iostream>
#include <cstring>
using namespace dh2::data;using Raw=std::vector<std::uint8_t>;static unsigned checks;
static void ck(bool b){if(!b)throw std::runtime_error("Gear owner V5 check "+std::to_string(checks));++checks;}
static Raw file(const std::string& p){std::ifstream f(p,std::ios::binary);ck(bool(f));return {std::istreambuf_iterator<char>(f),{}};}
struct Reader{const Raw& b;std::size_t at{};void copy(void* p,std::size_t n){ck(n<=b.size()-at);std::memcpy(p,b.data()+at,n);at+=n;}std::uint32_t u(){std::uint32_t n;copy(&n,4);return n;}};
struct Context{PlayerGearEffectsV5* gear;unsigned properties{},vitals{},skin{},presentation_fixture{},debug_fixture{};std::uintptr_t visual{};};
static bool effects(void* p,FreshInventoryOwnedV4&,const OwnedInventoryRequestV4& q,OwnedInventoryResponseV4& result,std::string& e){auto& c=*static_cast<Context*>(p);
 if(q.operation==OwnedInventoryOperationV4::update_gear_properties){++c.properties;return c.gear->update_properties(e);}if(q.operation==OwnedInventoryOperationV4::validate_hp_mp){++c.vitals;return c.gear->validate_hp_mp(e);}if(q.operation==OwnedInventoryOperationV4::skin){++c.skin;return c.gear->update_skin(&c.visual,{},e);}
 if(q.operation==OwnedInventoryOperationV4::update_name||q.operation==OwnedInventoryOperationV4::update_stats||q.operation==OwnedInventoryOperationV4::update_requirements){++c.presentation_fixture;return true;}
 if(q.operation==OwnedInventoryOperationV4::debug_load||q.operation==OwnedInventoryOperationV4::debug_query||q.operation==OwnedInventoryOperationV4::current_player){++c.debug_fixture;result={};return true;}
 e="Unreconstructed required V5 effect in fixture";return false;
}
int main(int argc,char** argv){try{ck(argc==6);std::string e;auto cache=std::string(argv[2]);auto bytes=file(cache+"/loot_table_pyarray.bin"),names=file(cache+"/loot_table_pyarraynames.bin"),schema=file(cache+"/loot_table_pystructnames.bin");LootTablesV2 table;ck(table.load({bytes.data(),bytes.size()},{names.data(),names.size()},{schema.data(),schema.size()},e));cache=argv[3];bytes=file(cache+"/item_powers_pyarray.bin");names=file(cache+"/item_powers_pyarraynames.bin");schema=file(cache+"/item_powers_pystructnames.bin");ItemPowerTablesV5 powers;ck(powers.load({bytes.data(),bytes.size()},{names.data(),names.size()},{schema.data(),schema.size()},e));
 cache=argv[4];bytes=file(cache+"/character_properties_pyarray.bin");names=file(cache+"/character_properties_pyarraynames.bin");schema=file(cache+"/character_properties_pystructnames.bin");CharacterTable chars;ck(load_characters({bytes.data(),bytes.size()},{names.data(),names.size()},{schema.data(),schema.size()},chars,e));PropertyRules rules;ck(load_property_rules(chars,rules,e));
 cache=argv[5];bytes=file(cache+"/character_classes_pyarray.bin");names=file(cache+"/character_classes_pyarraynames.bin");schema=file(cache+"/character_classes_pystructnames.bin");ClassTables classes;ck(load_classes({bytes.data(),bytes.size()},{names.data(),names.size()},{schema.data(),schema.size()},classes,e));std::vector<ClassRow> rows;for(auto& x:classes.rows)rows.push_back({x.data(),std::uint32_t(x.size())});
 auto gold=file(argv[1]);Reader r{gold};char magic[4];r.copy(magic,4);ck(!std::memcmp(magic,"GEV5",4));auto cases=r.u();unsigned steps=0,properties=0,vitals=0,skin=0,fixture=0;
 for(unsigned k=0;k<cases;++k){auto baseid=r.u(),selected=r.u(),count=r.u();auto state=std::make_shared<PropertyState>();reset_properties(rules,*state,&chars.rows.at(baseid));auto view=property_view(rules,*state);ck(dh2_class_recalc_base(rows.data(),rows.size(),state->base.data(),&view)==0);PropertyState initial;r.copy(&initial,sizeof initial);ck(!std::memcmp(state.get(),&initial,sizeof initial));LootRandom8V2 random{1,0};FreshInventoryOwnedV4 owner(0x100000001,table.borrow(),random,12,state);if(selected)owner.swap_equipment();PlayerGearEffectsV5 gear(owner,view,rows.data(),rows.size(),powers.borrow());Context context{&gear};OwnedInventoryServicesV4 services{&context,effects};
  for(unsigned i=0;i<count;++i){auto op=r.u(),a=r.u(),b=r.u(),c=r.u(),expected=r.u();(void)c;std::int32_t result=0;
   if(op==0)ck(owner.add_fixed_loot(std::int32_t(a),services,e));else if(op==2)ck(owner.character_auto_equip(a,result,services,e));else if(op==5)owner.swap_equipment();else if(op==4)ck(owner.unequip_from_slot(a,std::int32_t(b),services,e));else if(op==15)ck(gear.update_properties(e)&&gear.update_skin(&context.visual,{},e)&&gear.validate_hp_mp(e));else ck(false);
   ck(std::uint32_t(result)==expected);PropertyState after;r.copy(&after,sizeof after);if(std::memcmp(state.get(),&after,sizeof after)){auto* av=reinterpret_cast<const std::int32_t*>(state.get());auto* ev=reinterpret_cast<const std::int32_t*>(&after);for(unsigned j=0;j<896;++j)if(av[j]!=ev[j])std::cerr<<"case "<<k<<" step "<<i<<" op "<<op<<" sheet "<<j/224<<" property "<<j%224<<" actual "<<av[j]<<" expected "<<ev[j]<<"\n";}ck(!std::memcmp(state.get(),&after,sizeof after));++steps;
  }
  properties+=context.properties;vitals+=context.vitals;skin+=context.skin;fixture+=context.presentation_fixture;auto saved=*state;PropertyState other;auto mismatch=property_view(rules,other);PlayerGearEffectsV5 bad(owner,mismatch,rows.data(),rows.size(),powers.borrow());ck(!bad.update_properties(e)&&!std::memcmp(state.get(),&saved,sizeof saved));std::uintptr_t visual=0x100000010;ck(!gear.update_skin(&visual,{},e)&&!e.empty());ck(!gear.update_skin(nullptr,{},e));
 }
 ck(r.at==gold.size());std::cout<<"{\"validation\":\"PASS\",\"actual_starter_classes\":3,\"original_owner_cases\":"<<cases<<",\"original_owner_steps\":"<<steps<<",\"native_property_effects\":"<<properties<<",\"native_vitals_effects\":"<<vitals<<",\"original_null_visual_skin_branches\":"<<skin<<",\"item_text_fixture_deliveries\":"<<fixture<<",\"checks\":"<<checks<<",\"mismatches\":0}\n";return 0;
 }catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}

