#include "../quest_objective_list_v1.hpp"
#include <algorithm>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <memory>
#include <stdexcept>
namespace obj=dh2::data::quest_objective_list_v1;
namespace table=dh2::data::quest_table_bindings_v1;
using Stream=dh2::data::player_saved_quests_v1::StreamRef;
std::shared_ptr<std::vector<std::uint8_t>> file(const std::string& path){std::ifstream f(path,std::ios::binary|std::ios::ate);if(!f)throw std::runtime_error("cache missing");auto b=std::make_shared<std::vector<std::uint8_t>>(std::size_t(f.tellg()));f.seekg(0);if(!f.read(reinterpret_cast<char*>(b->data()),std::streamsize(b->size())))throw std::runtime_error("cache read failed");return b;}
table::Input input(std::shared_ptr<std::vector<std::uint8_t>> b,std::shared_ptr<std::vector<std::uint8_t>> n){table::Input in;if(dh2_quests_open(&in.table,b->data(),std::uint32_t(b->size())))throw std::runtime_error("packed table invalid");in.packed_owner=b;in.names=n->data();in.names_size=n->size();in.names_owner=n;return in;}
struct Record {obj::ObjectiveFields fields;obj::ObjectiveRef ref;std::uint32_t payload=0x60000000,destroyed=0;explicit Record(unsigned i):ref{{0x10010000+i*0x100,&fields.character_10},&fields}{fields.type_4=-17;fields.character_10=0x50000000+i;payload+=i;}};
struct Fixture {
 std::int32_t row[20]{};table::View view;obj::List list;Stream stream{0x10009000};
 std::vector<std::unique_ptr<obj::Array>> arrays;std::vector<std::unique_ptr<Record>> records;std::vector<std::array<std::uint32_t,5>> events;
 std::uint32_t attempts=0,cursor=0,created=0,returned=0;std::array<bool,3> retired{};bool mutated=false,reentrant_seen=false;obj::Runtime* runtime=nullptr;
 Fixture(table::View actual):view(std::move(actual)){for(unsigned a=0;a<3;++a){arrays.emplace_back(new obj::Array);arrays.back()->identity=0x10003000+a*0x100;}for(unsigned i=0;i<15;++i)records.emplace_back(new Record(i));}
 unsigned rid(obj::ObjectiveRef* r)const{if(!r)return 0;for(unsigned i=0;i<records.size();++i)if(&records[i]->ref==r)return i+1;throw std::runtime_error("actual objective factory missing");}
 unsigned aid(const obj::Array* a)const{if(!a)return 0;for(unsigned i=0;i<arrays.size();++i)if(arrays[i].get()==a)return i+1;throw std::runtime_error("actual array missing");}
 unsigned definition(const obj::Definition& d)const{if(!d.view)return 0;unsigned i=0;const auto* r=d.stub?d.stub->row:d.list?d.list->row:nullptr;if(!r)return 0;for(;i<d.view.count();++i)if(d.view.row(i)==r)break;if(i==d.view.count())throw std::runtime_error("actual definition missing");return 0x10004000+i*0x200+(d.stub?(d.stub->offset==0x3c?0x100:0x12c):d.index*0x2c);}
 obj::Definition def(unsigned index=0)const{const auto* r=view.row(std::uint32_t(row[1]));if(row[4])return {view,nullptr,0,view.resolve_stub(r->identity+(row[4]==1?0x3c:0x68))};return {view,view.list(*r,1),index,nullptr};}
 void init(){const auto cap=std::uint32_t(row[12]);arrays[0]->slots.resize(cap);arrays[1]->slots.resize(cap);for(unsigned i=0;i<cap;++i){arrays[0]->slots[i]=(std::uint32_t(row[11])&(1u<<i))?nullptr:&records[i]->ref;arrays[1]->slots[i]=&records[cap-1-i]->ref;}list.count_0=row[13];list.children_4=row[14]?arrays[0].get():nullptr;if(row[15])list.py_data_8=def();}
 bool event(unsigned op,unsigned target=0,unsigned value=0,unsigned extra=0){events.push_back({op,target,value,extra,cursor});++attempts;if(row[10]==13&&attempts==1&&runtime){obj::Result untouched;untouched.published=77;reentrant_seen=runtime->destroy(&untouched)==obj::Status::reentrant&&untouched.published==77;}return row[8]>0&&attempts==std::uint32_t(row[8]);}
 std::int32_t failure(bool failed){if(failed&&row[9])throw std::runtime_error("observing objective provider failure");return failed?1:0;}
 static std::int32_t allocate(void* ctx,obj::List&,std::uint32_t bytes,std::uint32_t tag,obj::Array** out){auto& f=*static_cast<Fixture*>(ctx);if(tag)return 1;const auto failed=f.event(1,3,bytes,tag);f.arrays[2]->slots.resize(std::min(bytes/4,64u));if(failed)return f.failure(true);if(f.row[10]==1)f.list.count_0=0;*out=f.row[10]==10?nullptr:f.arrays[2].get();return 0;}
 static std::int32_t factory(void* ctx,obj::List&,const obj::Definition& d,std::int32_t kind,obj::ObjectiveRef** out){auto& f=*static_cast<Fixture*>(ctx);const auto i=3+f.created++;const auto failed=f.event(2,i+1,std::uint32_t(kind),f.definition(d));if(failed)return f.failure(true);if(!f.mutated){if(f.row[10]==2)f.list.count_0=1;if(f.row[10]==3)f.list.children_4=f.arrays[1].get();if(f.row[10]==4){const auto* r=f.view.row(std::uint32_t(f.row[18]));f.list.py_data_8={f.view,f.view.list(*r,1),0,nullptr};}f.mutated=true;}*out=f.row[10]==9?nullptr:&f.records[i]->ref;return 0;}
 static std::int32_t member(void* ctx,obj::List&,const obj::StreamCall& call){auto& f=*static_cast<Fixture*>(ctx);if(call.stream!=&f.stream)return 1;auto& q=*f.records[f.rid(call.objective)-1];const auto failed=f.event(3,f.rid(call.objective),call.function,std::uint32_t(call.adjusted_target));if(failed&&f.row[16]){q.payload=(q.payload&0xffff0000)|((0x70000000+f.cursor/4)&0xffff);f.cursor+=2;}if(failed)return f.failure(true);q.payload=0x70000000+f.cursor/4;f.cursor+=4;if(!f.mutated){if(f.row[10]==5)f.list.count_0=0;if(f.row[10]==6)f.list.children_4=f.arrays[1].get();f.mutated=true;}return 0;}
 static std::int32_t deletion(void* ctx,obj::List&,obj::ObjectiveRef* q){auto& f=*static_cast<Fixture*>(ctx);const auto id=f.rid(q);const auto failed=f.event(4,id,4);if(failed&&f.row[16])f.records[id-1]->destroyed=1;if(failed)return f.failure(true);f.records[id-1]->destroyed=1;if(!f.mutated){if(f.row[10]==7){f.list.count_0=1;f.list.children_4=f.arrays[1].get();}if(f.row[10]==8)f.list.count_0=0;f.mutated=true;}return 0;}
 static std::int32_t release(void* ctx,obj::List&,obj::Array* a){auto& f=*static_cast<Fixture*>(ctx);const auto id=f.aid(a);const auto failed=f.event(5,id);if(failed)return f.failure(true);f.retired[id-1]=true;return 0;}
 obj::Services services(){return {this,allocate,factory,member,deletion,release};}
 obj::Status run(){obj::Runtime r(list,services());runtime=&r;obj::Result result;obj::Status status=obj::Status::complete;const auto d=def(std::uint32_t(row[3]));switch(row[0]){case 0:case 1:status=r.construct(&result);break;case 2:status=r.assign_pydata(d,row[2],&result);break;case 3:{obj::ObjectiveRef* child=nullptr;status=r.create_objective(d,&child,&result);returned=rid(child);break;}case 4:status=r.set_owner(std::uint32_t(row[5]),&result);break;case 5:status=r.load(stream,&result);break;case 6:case 7:status=r.destroy(&result);break;case 8:status=r.loop_stream(std::uint32_t(row[7]),row[6],stream,&result);break;default:status=r.construct(&result);if(status==obj::Status::complete)status=r.assign_pydata(d,row[2],&result);if(status==obj::Status::complete)status=r.set_owner(std::uint32_t(row[5]),&result);if(status==obj::Status::complete)status=r.load(stream,&result);if(status==obj::Status::complete)status=r.destroy(&result);break;}runtime=nullptr;return status;}
 std::vector<std::uint32_t> projection(obj::Status s){std::vector<std::uint32_t> out{s==obj::Status::complete?0u:1u,cursor,std::uint32_t(list.count_0),aid(list.children_4),definition(list.py_data_8),returned,created};for(unsigned i=0;i<arrays.size();++i){out.push_back(std::uint32_t(arrays[i]->slots.size()));out.push_back(retired[i]);for(auto* p:arrays[i]->slots)out.push_back(rid(p));}for(const auto& q:records){out.push_back(std::uint32_t(q->fields.type_4));out.push_back(definition(q->fields.py_data_c));out.push_back(std::uint32_t(q->fields.character_10));out.push_back(q->payload);out.push_back(q->destroyed);}out.push_back(std::uint32_t(events.size()));for(auto e:events)out.insert(out.end(),e.begin(),e.end());return out;}
};
table::View altered(const table::Input& actual,const std::int32_t* row){table::Owner owner;std::string error;if(!owner.load(actual,error))throw std::runtime_error(error);auto view=owner.borrow();if(row[17]!=INT32_MIN){auto bytes=std::make_shared<std::vector<std::uint8_t>>(actual.table.bytes,actual.table.bytes+actual.table.size);auto names=std::make_shared<std::vector<std::uint8_t>>(actual.names,actual.names+actual.names_size);const auto* r=view.row(std::uint32_t(row[1]));std::uint32_t offset=0;if(row[4]){const auto* stub=view.resolve_stub(r->identity+(row[4]==1?0x3c:0x68));offset=stub->definition->strings[0].offset-16;}else{dh2_quest_span span;if(!view.list_record(*view.list(*r,1),std::uint32_t(row[3]),&span,error))throw std::runtime_error(error);offset=span.offset;}std::memcpy(bytes->data()+offset,&row[17],4);if(!owner.load(input(bytes,names),error))throw std::runtime_error(error);view=owner.borrow();}return view;}
unsigned policies(table::View view,const table::Input& actual){unsigned n=0;auto check=[&](bool v){if(!v)throw std::runtime_error("Objective native policy "+std::to_string(n));++n;};Fixture f(view);f.row[1]=47;f.row[2]=3;f.row[8]=-1;f.row[12]=3;f.row[13]=3;f.row[14]=1;f.row[15]=1;f.init();obj::Runtime r(f.list,f.services());obj::Result result;const auto d=f.def();check(r.assign_pydata(d,3,&result)==obj::Status::complete);check(result.published==3&&f.list.children_4==f.arrays[2].get());check(!f.retired[0]);for(unsigned i=0;i<3;++i)check(f.records[3+i]->ref.action.character_10==&f.records[3+i]->fields.character_10);check(r.set_owner(99,&result)==obj::Status::complete&&result.owner_stores==3);check(r.load(f.stream,&result)==obj::Status::complete&&f.cursor==12);check(r.destroy(&result)==obj::Status::complete&&result.deleted==3&&f.retired[2]&&f.list.children_4==nullptr);check(f.list.count_0==3&&f.definition(f.list.py_data_8)!=0);for(unsigned i=0;i<3;++i)check(f.records[3+i]->destroyed==1);check(r.destroy(&result)==obj::Status::source_fault);check(r.construct(&result)==obj::Status::complete);check(r.destroy(&result)==obj::Status::complete);
 check(r.load(f.stream,nullptr)==obj::Status::invalid_argument);check(r.destroy(reinterpret_cast<obj::Result*>(&f.list))==obj::Status::invalid_argument);check(r.destroy(reinterpret_cast<obj::Result*>(&r))==obj::Status::invalid_argument);check(r.assign_pydata(d,1,reinterpret_cast<obj::Result*>(const_cast<obj::Definition*>(&d)))==obj::Status::invalid_argument);
 f.list.count_0=3;f.list.children_4=f.arrays[0].get();check(r.destroy(reinterpret_cast<obj::Result*>(&f.records[0]->fields))==obj::Status::invalid_argument);check(r.destroy(reinterpret_cast<obj::Result*>(f.arrays[0]->slots.data()))==obj::Status::invalid_argument);
 obj::Runtime missing(f.list,{});check(missing.load(f.stream,&result)==obj::Status::service_unavailable);check(missing.destroy(&result)==obj::Status::service_unavailable);check(missing.assign_pydata(d,-1,&result)==obj::Status::complete&&f.list.count_0==-1&&f.list.children_4==f.arrays[0].get());check(missing.assign_pydata(d,1,&result)==obj::Status::service_unavailable&&f.list.count_0==1&&f.list.children_4==f.arrays[0].get());
 Fixture nested(view);nested.row[0]=2;nested.row[1]=47;nested.row[2]=3;nested.row[8]=-1;nested.row[10]=13;nested.row[12]=3;nested.init();check(nested.run()==obj::Status::complete&&nested.reentrant_seen);
 auto wrong=d;wrong.index=3;check(r.assign_pydata(wrong,1,&result)==obj::Status::source_fault);check(result.service_calls==1&&f.list.count_0==1&&f.list.children_4==f.arrays[2].get());
 // Old immutable generation remains leased by the canonical Objective fields.
 const auto identity=f.records[3]->fields.py_data_c.view.rows_identity();dh2_quest_objective objective{};std::string error;check(identity&&f.records[3]->fields.py_data_c.view.objective(*f.records[3]->fields.py_data_c.list,0,&objective,error));
 Record retained(0);std::weak_ptr<const void> weak_bytes,weak_names;
 {auto bytes=std::make_shared<std::vector<std::uint8_t>>(actual.table.bytes,actual.table.bytes+actual.table.size);auto names=std::make_shared<std::vector<std::uint8_t>>(actual.names,actual.names+actual.names_size);weak_bytes=bytes;weak_names=names;table::Owner generation;check(generation.load(input(bytes,names),error));const auto lease=generation.borrow();obj::Definition definition{lease,lease.list(*lease.row(0),1),0,nullptr};obj::List one;obj::Services service;service.context=&retained;service.factory=[](void* p,obj::List&,const obj::Definition&,std::int32_t,obj::ObjectiveRef** out){*out=&static_cast<Record*>(p)->ref;return 0;};obj::Runtime runtime(one,service);obj::ObjectiveRef* created=nullptr;check(runtime.create_objective(definition,&created,&result)==obj::Status::complete&&created==&retained.ref);}
 check(!weak_bytes.expired()&&!weak_names.expired());check(retained.fields.py_data_c.view.objective(*retained.fields.py_data_c.list,0,&objective,error));retained.fields.py_data_c={};check(weak_bytes.expired()&&weak_names.expired());
 return n;}
int main(int argc,char** argv){try{if(argc!=4)return 2;const auto actual=input(file(std::string(argv[3])+"/v2quests_pyarray.bin"),file(std::string(argv[3])+"/v2quests_pyarraynames.bin"));auto* in=std::fopen(argv[1],"rb");auto* out=std::fopen(argv[2],"wb");if(!in||!out)return 3;std::uint32_t count;if(std::fread(&count,4,1,in)!=1)return 4;for(unsigned i=0;i<count;++i){std::int32_t row[20];if(std::fread(row,4,20,in)!=20)return 5;Fixture f(altered(actual,row));std::copy(row,row+20,f.row);f.init();const auto values=f.projection(f.run());const auto n=std::uint32_t(values.size());std::fwrite(&n,4,1,out);std::fwrite(values.data(),4,values.size(),out);}std::fclose(in);std::fclose(out);table::Owner owner;std::string error;if(!owner.load(actual,error))return 6;std::printf("%u\n",policies(owner.borrow(),actual));return 0;}catch(const std::exception& e){std::fprintf(stderr,"%s\n",e.what());return 9;}}
