"""Run reconciled Adam modules through the selected game-data shared library.

Gear-owner fixtures must first be regenerated by player_gear_effects_v5_original.py.
Text/debug providers and null-Visual Skin branches remain explicit fixtures.
"""
import argparse, hashlib, json, os, subprocess
from pathlib import Path

ROOT=Path(__file__).resolve().parents[3]
def digest(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser(description=__doc__)
 p.add_argument('--cache',type=Path,required=True)
 p.add_argument('--build',type=Path,required=True)
 p.add_argument('--compiler',type=Path,required=True)
 p.add_argument('--report',type=Path,required=True)
 a=p.parse_args();env=os.environ.copy();env['PATH']=str(a.compiler.parent)+os.pathsep+env.get('PATH','')
 files=list((ROOT/'port/game-data').glob('*.cpp'))+list((ROOT/'port/game-data').glob('*.hpp'))
 files += [ROOT/'port/game-data/CMakeLists.txt',ROOT/'port/random/random.c',ROOT/'port/random/random.h',Path(__file__).resolve()]
 files += list((ROOT/'port/game-data/tests').glob('*.cpp'))
 before={str(x.relative_to(ROOT)).replace('\\','/'):digest(x) for x in files}
 logs=[]
 def run(command):
  r=subprocess.run([str(x) for x in command],cwd=ROOT,env=env,capture_output=True,text=True)
  logs.append({'command':[str(x) for x in command],'returncode':r.returncode,'stdout':r.stdout,'stderr':r.stderr})
  if r.returncode:raise RuntimeError(r.stderr or r.stdout)
  return r.stdout
 run(['cmake','-S',ROOT/'port/game-data','-B',a.build,'-G','Ninja','-DCMAKE_BUILD_TYPE=RelWithDebInfo','-DCMAKE_EXPORT_COMPILE_COMMANDS=ON','-DCMAKE_CXX_COMPILER='+str(a.compiler),'-DCMAKE_C_COMPILER='+str(a.compiler.with_name('gcc.exe'))])
 targets=['item_gear_properties_v5_audit','loot_power_resources_v7_audit','fresh_inventory_owned_v4_audit','player_gear_effects_v5_audit']
 run(['cmake','--build',a.build,'--parallel','1','--target',*targets])
 ref=ROOT/'port/game-data/reference'
 commands=[
  [a.build/'item_gear_properties_v5_audit.exe',ref/'adam-c3ae797-item-v5/gear-fixtures.bin',ref/'adam-c3ae797-item-v5/power-fixtures.bin',a.cache],
  [a.build/'loot_power_resources_v7_audit.exe',a.cache],
  [a.build/'fresh_inventory_owned_v4_audit.exe','--random-only'],
  [a.build/'fresh_inventory_owned_v4_audit.exe',ref/'player-inventory-owned-v4/fixtures.bin',ref/'player-creation-v2/fresh-fixtures.bin',a.cache],
  [a.build/'fresh_inventory_owned_v4_audit.exe','--borrowed',ref/'player-inventory-owned-v4/fixtures.bin',ref/'player-creation-v2/fresh-fixtures.bin',a.cache],
  [a.build/'player_gear_effects_v5_audit.exe',ref/'player-item-effects-v5/starter-effects-fixtures.bin',a.cache,a.cache,a.cache,a.cache]]
 results=[]
 for command in commands:
  result=json.loads(run(command));assert result['validation']=='PASS',result
  results.append({'command':[str(x) for x in command],'result':result})
 after={str(x.relative_to(ROOT)).replace('\\','/'):digest(x) for x in files}
 assert before==after,'Selected source changed during the gate; rerun after freezing'
 database=json.loads((a.build/'compile_commands.json').read_text())
 selected=[x for x in database if 'CMakeFiles/dh2_game_data.dir' in x['command'].replace('\\','/')]
 library=a.build/'libdh2_game_data.dll'
 original=json.loads((ref/'player-item-effects-v5/starter-effects-original-gold.json').read_text())
 assert original['gold_sha256']==digest(ref/'player-item-effects-v5/starter-effects-fixtures.bin')
 report={'validation':'PASS','scope':'Current selected shared-library host verification. V4 borrows properties/RNG; gear text/debug are fixtures and Skin exercises null Visual. No native inventory, skill execution, loot pickup or gameplay claim.','upstream_commit':'c3ae797332a82a30a586b9156cddc25445e36a4c','source_before_after_equal':True,'source_sha256':before,'selected_library':{'path':str(library),'sha256':digest(library)},'selected_commands':selected,'tests':results,'fresh_gear_original_receipt':original,'cache':{x.name:digest(x) for x in a.cache.glob('*.bin') if x.name.startswith(('loot_table_','item_powers_','character_properties_','character_classes_'))}}
 a.report.parent.mkdir(parents=True,exist_ok=True);a.report.write_text(json.dumps(report,indent=2)+'\n')
 (a.build/'gate-command-outputs.json').write_text(json.dumps(logs,indent=2)+'\n')
 print(json.dumps({'validation':'PASS','suites':len(results),'selected_library_units':len(selected),'source_hashes':len(before),'report':str(a.report),'report_sha256':digest(a.report)}))
if __name__=='__main__':main()
