#include "../gfnt.hpp"
#include <cstring>
#include <fstream>
#include <iostream>
#include <iterator>
#include <stdexcept>
using namespace dh2::ui;
namespace {unsigned checks=0,guards=0;void check(bool b){++checks;if(!b)throw std::runtime_error("GFNT check "+std::to_string(checks));}std::vector<std::uint8_t> file(const char* p){std::ifstream f(p,std::ios::binary);check(bool(f));return {std::istreambuf_iterator<char>(f),{}};}unsigned word(std::istream& f){unsigned v;f.read(reinterpret_cast<char*>(&v),4);check(bool(f));return v;}void put(std::vector<std::uint8_t>& b,unsigned p,unsigned n){for(unsigned i=0;i<4;++i)b[p+i]=n>>(24-8*i);}unsigned be(const std::vector<std::uint8_t>& b,unsigned p){return(unsigned(b[p])<<24)|(unsigned(b[p+1])<<16)|(unsigned(b[p+2])<<8)|b[p+3];}}
int main(int argc,char** argv){try{check(argc==3);auto b=file(argv[2]);GfntFont owner;std::string error;check(owner.load(b.data(),b.size(),error));auto pin=owner.borrow();check(pin.first_codepoint()==32&&pin.glyph_slots()==8451);std::ifstream gold(argv[1],std::ios::binary);check(word(gold)==0x31544647);unsigned n=word(gold),present=0;GfntRaster out;for(unsigned i=0;i<n;++i){unsigned code=word(gold);auto height=static_cast<std::int32_t>(word(gold));auto expected=word(gold);GfntMetrics20 metrics;gold.read(reinterpret_cast<char*>(&metrics),20);unsigned bytes=word(gold);std::vector<std::uint8_t> pixels(bytes);gold.read(reinterpret_cast<char*>(pixels.data()),bytes);check(bool(gold));auto prior=out;check(pin.raster(out,code,height,error)==int(expected));if(expected){check(!std::memcmp(&out.source.metrics,&metrics,20)&&out.source.pitch==64&&out.source.reserved==0&&out.rgba==pixels);check(out.advance_twips==static_cast<float>(metrics.advance)*20.0f);++present;}else check(out.rgba==prior.rgba&&!std::memcmp(&out.source,&prior.source,32));}check(gold.peek()==EOF);
 check(!owner.load(b.data(),b.size(),error));++guards;pin={};auto malformed=b;malformed[0]^=1;check(!owner.load(malformed.data(),malformed.size(),error));++guards;malformed=b;put(malformed,12,0xffffffff);check(!owner.load(malformed.data(),malformed.size(),error));++guards;
 for(unsigned limit:{0u,1u,39u,40u,44u,33847u,33848u,120567u}){check(!owner.load(b.data(),limit,error));++guards;}for(unsigned i=0;i<8451;++i){auto start=be(b,40+4*i),end=be(b,44+4*i);if(start!=end){malformed=b;malformed[start+4]=127;check(!owner.load(malformed.data(),malformed.size(),error));++guards;}}
 GfntInput16 input{b.data(),static_cast<unsigned>(b.size()),0};GfntGlyph32 info,before;std::memset(&info,0xa5,32);before=info;std::vector<std::uint8_t> pixels(1216,0xa5);auto original=pixels;check(dh2_gfnt_raster(&info,pixels.data(),1215,&input,65,19)==-1&&!std::memcmp(&info,&before,32)&&pixels==original);++guards;check(dh2_gfnt_raster(reinterpret_cast<GfntGlyph32*>(pixels.data()),pixels.data(),pixels.size(),&input,65,19)==-1&&pixels==original);++guards;check(dh2_gfnt_raster(&info,b.data(),1216,&input,65,19)==-1&&!std::memcmp(&info,&before,32));++guards;input.reserved=1;check(dh2_gfnt_raster(&info,pixels.data(),pixels.size(),&input,65,19)==-1&&pixels==original);++guards;input.reserved=0;check(dh2_gfnt_raster(&info,pixels.data(),pixels.size(),&input,0,19)==0&&!std::memcmp(&info,&before,32)&&pixels==original);++guards;
 pin=owner.borrow();owner=GfntFont{};b.clear();b.shrink_to_fit();check(pin.raster(out,65,19,error)==1&&out.rgba.size()==1216);std::cout<<"{\"validation\":\"PASS\",\"comparisons\":"<<n<<",\"present_glyphs\":"<<present<<",\"checks\":"<<checks<<",\"atomic_guards\":"<<guards<<",\"owned_snapshot_survives_inputs\":true,\"advance_twips_verified\":true,\"mismatches\":0}\n";
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
