"""Emit engine algorithm data, preserving every captured distribution byte."""
import hashlib,json,pathlib
root=pathlib.Path(__file__).resolve().parents[1];reference=root/'reference/procedural-generation'
provenance=json.loads((reference/'provenance.json').read_text());raw=(reference/'distributions.bin').read_bytes()
assert hashlib.sha256(raw).hexdigest()==provenance['distribution']['sha256'] and len(raw)==26136
lines=['// Original rnd::gDistributions bytes; generated by tools/emit_procedural_distribution.py.',
       '// ELF SHA256 '+provenance['engine_sha256'],
       '// Table SHA256 '+provenance['distribution']['sha256']]
for i in range(0,len(raw),24):lines.append(','.join(str(n if n<128 else n-256) for n in raw[i:i+24])+',')
(root/'procedural_distribution_v1.inc').write_text('\n'.join(lines)+'\n')
print(json.dumps({'bytes':len(raw),'table_sha256':provenance['distribution']['sha256']}))
