#include "../visual_skin_owner_v6.hpp"
#include "../../engine-animation/animation.hpp"
#include <fstream>
#include <filesystem>
#include <iostream>
#include <cctype>
#include <cmath>
#include <algorithm>
using namespace dh2;using namespace dh2::skinning;
static unsigned checks;static void ck(bool b,const std::string& e){if(!b)throw std::runtime_error("V6 check "+std::to_string(checks)+": "+e);++checks;}
static std::vector<std::uint8_t> read(const std::string& path){std::ifstream f(path,std::ios::binary);if(!f)throw std::runtime_error("Missing file: "+path);return {std::istreambuf_iterator<char>(f),{}};}
struct Files {std::string directory;unsigned reads{};bool fail{};};
static VisualAssetResultV6 file(void* p,const char* name,std::vector<std::uint8_t>& b,std::string& e){auto& f=*static_cast<Files*>(p);++f.reads;if(f.fail){e="Explicit provider failure";return VisualAssetResultV6::failed;}std::string path=name;auto slash=path.find_last_of('/');path=path.substr(slash+1);for(auto& c:path)c=char(std::tolower(static_cast<unsigned char>(c)));auto full=f.directory+"/"+path;if(!std::filesystem::exists(full))return VisualAssetResultV6::missing;b=read(full);return VisualAssetResultV6::found;}
int main(int argc,char** argv){try{ck(argc==4,"usage model weapons-directory authored-clip");std::string e;VisualSkinResourcesV6 resources;auto bytes=read(argv[1]);ck(resources.load(bytes,e),e);auto b=resources.borrow();ck(b.categories().size()==4&&b.factory_scene().graph.size()==35,"Source catalog/node counts");auto scene=b.factory_scene();Files f{argv[2]};VisualSkinOwnerV6 owner(b,scene,{&f,file});ck(owner.initialize(e),e);ck(!owner.initialize(e),"Repeated initialize accepted");std::vector<VisualDrawPartV6> parts;ck(owner.draw_parts(parts,e),e);ck(parts.size()==4,"Naked default part count");unsigned modules=0,vertices=0;
 for(unsigned c=0;c<b.categories().size();++c){ck(owner.category_id(b.categories()[c].name.c_str())==int(c),"Category selection");ck(owner.current_module(c)==0,"Source naked default");for(unsigned m=0;m<b.categories()[c].modules.size();++m){const auto& resource=b.categories()[c].modules[m];auto name=resource.uri.substr(1,resource.uri.size()-11);ck(owner.module_id(999,name.c_str())==int(m),"Global ordered module index");ck(owner.set_modular(c,m,e),e);owner.clear_visibility_dirty();ck(owner.set_modular(c,m,e)&&owner.visibility_dirty(),"Same-module still source Visibility notify");ck(owner.draw_parts(parts,e),e);ck(parts.size()==4&&parts[c].module==int(m)&&parts[c].geometry==&resource.part.geometry,"Real graph module replacement");ck(parts[c].positions.size()==resource.part.geometry.positions.size(),"Real skin stream");for(const auto& v:parts[c].positions)for(auto x:v)ck(std::isfinite(x),"Skinned position nonfinite");vertices+=parts[c].positions.size();++modules;}}
 ck(modules==172,"Source module count");
 // Real source animation modifies the SAME borrowed Scene. Palette/CPU streams
 // reflect that pose without rebuilding, appending or replacing joint storage.
 animation::Player clip;auto clipbytes=read(argv[3]);ck(clip.load(clipbytes.data(),clipbytes.size(),scene,e,animation::MissingTargets::ignore),e);animation::TransformSet set;ck(set.compile_dynamic({{0,&clip}},scene,e,nullptr),e);auto pose=[&](int ms){for(unsigned t=0;t<set.targets().size();++t){const auto& target=set.targets()[t];if(target.node>=scene.graph.size())continue;auto& node=scene.graph[target.node];float value[4]{};float* destination=target.type==1?node.translation:target.type==5?node.quaternion:target.type==10?node.scale:nullptr;ck(destination!=nullptr,"Compiled transform type unsupported");std::copy_n(destination,target.components,value);ck(set.sample(0,t,ms,value,4,nullptr,e),e);std::copy_n(value,target.components,destination);}ck(scene::update_world(scene,e),e);};pose(clip.start);ck(owner.draw_parts(parts,e),e);auto prior=parts;pose(clip.start+(clip.end-clip.start)/2);ck(owner.draw_parts(parts,e),e);unsigned moved=0;for(unsigned i=0;i<4;++i)for(unsigned j=0;j<parts[i].positions.size();++j)if(parts[i].positions[j]!=prior[i].positions[j])++moved;ck(moved>0,"Real animation did not move owned skin graph");
 unsigned weapons=0,weaponparts=0;for(auto& p:std::filesystem::directory_iterator(argv[2])){if(p.path().extension()!=".bdae")continue;auto name=p.path().stem().string();ck(owner.set_weapon(name.c_str(),1,weapons%3,e),name+": "+e);ck(owner.draw_parts(parts,e),e);ck(parts.size()>4,"Weapon missing actual geometry/anchor");for(unsigned i=4;i<parts.size();++i){ck(parts[i].geometry&&parts[i].material_table&&parts[i].materials&&parts[i].retention&&!parts[i].positions.empty(),"Weapon resource backing");++weaponparts;}++weapons;}
 ck(weapons==781,"Cache weapon count");auto retained=parts;auto retained_id=parts.back().geometry->id;ck(owner.set_weapon(nullptr,1,1,e)&&owner.draw_parts(parts,e)&&parts.size()==4,"Weapon unequip");ck(retained.back().geometry->id==retained_id,"Draw snapshot resource freed prematurely");ck(owner.set_weapon("mc_rweapon_longsword_01",2,2,e),e);ck(owner.draw_parts(parts,e)&&parts.size()>4,"Second slot weapon");ck(owner.set_weapon("genuine_missing_asset",2,2,e)&&owner.draw_parts(parts,e)&&parts.size()==4,"Source null factory replaces old weapon");
 ck(owner.set_modular(0,-1,e)&&owner.draw_parts(parts,e)&&parts.size()==3,"Module unequip");ck(owner.set_modular(0,0,e),e);f.fail=true;ck(!owner.set_weapon("mc_rweapon_longsword_01",1,1,e)&&e=="Explicit provider failure","Provider failure hidden");f.fail=false;ck(!owner.set_weapon("mc_rweapon_longsword_01",1,3,e),"Invalid attachment mode accepted");ck(!owner.set_modular(4,0,e),"Invalid category accepted");ck(!resources.load(bytes,e),"Reload with active Borrow accepted");auto old_scene=scene;scene.graph[0].sid="changed";ck(!owner.draw_parts(parts,e),"Changed live graph accepted");scene=old_scene;ck(owner.draw_parts(parts,e),e);
 auto corrupt=bytes;corrupt.resize(60);VisualSkinResourcesV6 bad;ck(!bad.load(corrupt,e),"Malformed BRES accepted");std::vector<VisualDrawPartV6> afterlife;
 {VisualSkinResourcesV6 temporary;ck(temporary.load(bytes,e),e);auto live=temporary.borrow().factory_scene();{VisualSkinOwnerV6 transient(temporary.borrow(),live,{&f,file});ck(transient.initialize(e)&&transient.set_weapon("mc_rweapon_longsword_01",1,1,e)&&transient.draw_parts(afterlife,e),e);}ck(!afterlife.empty()&&!afterlife.back().geometry->positions.empty(),"Owner-destroyed draw lifetime");}
 ck(!afterlife.front().geometry->positions.empty(),"Resource-owner destroyed draw lifetime");
 std::cout<<"{\"validation\":\"PASS\",\"checks\":"<<checks<<",\"actual_modules\":"<<modules<<",\"actual_skinned_vertices_sampled\":"<<vertices<<",\"actual_weapons\":"<<weapons<<",\"actual_weapon_parts\":"<<weaponparts<<",\"actual_animation_changed_vertices\":"<<moved<<",\"mismatches\":0}\n";return 0;
}catch(const std::exception& x){std::cerr<<x.what()<<'\n';return 1;}}
