#!/usr/bin/env python3
"""Generate checked numeric vectors by executing original Lua API/Arith bodies."""
import argparse
import ctypes as c
import hashlib
import importlib.util
import json
from pathlib import Path
import random
import struct
from elftools.elf.elffile import ELFFile
ROOT=Path(__file__).resolve().parents[1]
spec=importlib.util.spec_from_file_location('lua_cpu',ROOT/'../animation-values/tests/differential.py')
cpu=importlib.util.module_from_spec(spec);spec.loader.exec_module(cpu)
ROWS=[(0x84b458,32,'lua_pushnumber'),(0x84c450,60,'lua_tonumber'),
      (0x84af9c,240,'index2adr'),(0x85cd38,484,'Arith'),(0x85ccd8,96,'luaV_tonumber')]
class Dependencies(cpu.Dependencies):
    def __init__(self,path):
        super().__init__(path);self.libm=c.CDLL('libm.so.6')
        for name,count in [('floor',1),('pow',2)]:
            fn=getattr(self.libm,name);fn.argtypes=[c.c_double]*count;fn.restype=c.c_double
            self.functions[name]=(fn,'d',count)
def main():
    p=argparse.ArgumentParser()
    for name in ('original','oracle','report','header'):p.add_argument('--'+name,type=Path,required=True)
    a=p.parse_args();sha=lambda path:hashlib.sha256(path.read_bytes()).hexdigest()
    assert sha(a.original)==cpu.ORIGINAL_SHA256;evidence=[]
    with a.original.open('rb')as stream:
        elf=ELFFile(stream);loads=[s for s in elf.iter_segments()if s['p_type']=='PT_LOAD']
        for address,size,name in ROWS:
            segment=next(s for s in loads if s['p_vaddr']<=address and address+size<=s['p_vaddr']+s['p_filesz'])
            stream.seek(segment['p_offset']+address-segment['p_vaddr'])
            evidence.append({'elf_address':f'0x{address:08x}','size':size,'name':name,
                             'sha256':hashlib.sha256(stream.read(size)).hexdigest()})
    machine=cpu.EngineCpu(a.original,False,Dependencies(a.oracle),{'functions':evidence})
    state,bottom,left,right,out=[machine.data+x for x in (0x400,0x800,0x1000,0x1100,0x1200)]
    f32=lambda x:c.c_float(x).value
    bits=lambda x:struct.unpack('<I',struct.pack('<f',f32(x)))[0]
    api_checks=0
    for raw in (0,0x80000000,1,0x7fffff,0x800000,0x3f800000,0xbf800000,0x4b800000,0x7f7fffff,0xff7fffff,0x7f800000,0xff800000,0x7fc12345):
        machine.uc.mem_write(state,bytes(128));machine.uc.mem_write(state+8,struct.pack('<II',bottom,bottom))
        machine.uc.mem_write(bottom,b'\xa5'*32);machine.call(0x84b458,[state,raw])
        assert bytes(machine.uc.mem_read(bottom,8))==struct.pack('<II',raw,3)
        assert bytes(machine.uc.mem_read(bottom+8,24))==b'\xa5'*24
        assert struct.unpack('<I',machine.uc.mem_read(state+8,4))[0]==bottom+8
        assert machine.call(0x84c450,[state,1])==raw
        assert machine.call(0x84c450,[state,0xffffffff])==raw
        api_checks+=1
    rng=random.Random(20261002)
    pairs=[(0,1),(-0.,-1),(16777216,1),(-16777216,1),(1e-30,3),(-1.5,2),(-5,2),(5,-2)]
    pairs +=[(rng.uniform(-1000,1000),rng.choice((-1,1))*rng.uniform(.1,100))for _ in range(64)]
    vectors=[]
    for op in range(5,12):
        selected=([(rng.uniform(.1,20),rng.uniform(-3,3))for _ in range(72)]if op==10 else pairs)
        for x,y in selected:
            aa,bb=bits(x),bits(y)
            machine.uc.mem_write(left,struct.pack('<II',aa,3));machine.uc.mem_write(right,struct.pack('<II',bb,3))
            machine.uc.mem_write(out,b'\xa5'*24);machine.call(0x85cd38,[state,out,left,right,op])
            expected,kind=struct.unpack('<II',machine.uc.mem_read(out,8));assert kind==3
            assert bytes(machine.uc.mem_read(out+8,16))==b'\xa5'*16
            assert bytes(machine.uc.mem_read(left,8))==struct.pack('<II',aa,3)
            assert bytes(machine.uc.mem_read(right,8))==struct.pack('<II',bb,3)
            vectors.append({'op':op,'a_bits':aa,'b_bits':bb,'result_bits':expected})
    header='/* Generated by original_numeric_vectors.py; exact original numeric outputs. */\n'
    header+='static const struct { unsigned op; uint32_t a,b,result; } numeric_vectors[] = {\n'
    header+=''.join('    {%du,0x%08xu,0x%08xu,0x%08xu},\n'%(v['op'],v['a_bits'],v['b_bits'],v['result_bits'])for v in vectors)
    header+='};\n';a.header.write_text(header,newline='\n')
    result={'complete_game':False,'full_interpreter_equivalence_tested':False,'original_game_scripts_executed':False,
            'number_storage_bits':32,'numeric_tag':3,'tvalue_bytes':8,'push_positive_negative_index_checks':api_checks,
            'numeric_arith_vectors':len(vectors),'original_sha256':sha(a.original),'oracle_sha256':sha(a.oracle),
            'function_evidence':evidence,'test_sha256':sha(Path(__file__)),'header_sha256':sha(a.header),
            'vectors':vectors,'input_preservation':True,'output_guards':True,'stack_restoration':True,
            'dependency_model':'Actual original API, index helper, numeric coercion and Arith instructions execute; arithmetic imports use existing host C oracle; floor/pow use host libm, not historical Android libm',
            'import_calls':machine.import_calls,'seed':20261002}
    a.report.write_text(json.dumps(result,indent=2)+'\n');print('Original API cases:',api_checks,'arithmetic vectors:',len(vectors))
if __name__=='__main__':main()
