#include "fresh_inventory_owned_v4.hpp"
#include <cstring>
#include <stdexcept>
namespace dh2::data {
namespace {
bool legacy_fixture_random(void* context,std::int32_t bound,std::uint32_t stream,std::int32_t& value,std::string& error){
 if(stream!=0||!context){error="Invalid legacy fixture RNG request";return false;}
 if(dh2_loot_v2_random(static_cast<LootRandom8V2*>(context),bound,&value)){error="Invalid legacy fixture RNG";return false;}
 return true;
}
}
FreshInventoryOwnedV4::FreshInventoryOwnedV4(std::uintptr_t id,LootTablesV2::Borrow b,InventoryRandomServiceV4 random,std::int8_t cap,PropertyState& props):tables_(std::move(b)),random_(random),character_(id),properties_(&props),potion_capacity_(cap){if(!id||!tables_)throw std::invalid_argument("Unbound fresh inventory owner");}
FreshInventoryOwnedV4::FreshInventoryOwnedV4(std::uintptr_t id,LootTablesV2::Borrow b,LootRandom8V2& r,std::int8_t cap,std::shared_ptr<PropertyState> props):tables_(std::move(b)),random_{&r,legacy_fixture_random},character_(id),properties_(props.get()),fixture_properties_(std::move(props)),potion_capacity_(cap){if(!id||!tables_||!properties_)throw std::invalid_argument("Unbound legacy fixture inventory owner");}
bool FreshInventoryOwnedV4::mutation_allowed(std::string& e)const{if(callback_depth_){e="Unsupported destructive inventory callback reentry";return false;}return true;}
void FreshInventoryOwnedV4::observe(const OwnedInventoryServicesV4& s,OwnedInventoryOperationV4 op,std::uint32_t caller,ItemInstanceV1* item,std::int32_t arg,std::uint32_t index){if(s.observe_storage){++callback_depth_;struct Guard{std::uint32_t& n;~Guard(){--n;}}guard{callback_depth_};s.observe_storage(s.context,*this,{op,caller,item,nullptr,arg,index});}}
bool FreshInventoryOwnedV4::deliver(const OwnedInventoryServicesV4& s,OwnedInventoryOperationV4 op,std::uint32_t caller,ItemInstanceV1* instance,const char* name,std::int32_t arg,std::uint32_t index,OwnedInventoryResponseV4& out,std::string& e){out={};if(op==OwnedInventoryOperationV4::destroy_item){if(!s.observe_storage&&!s.stateless_temporaries){e="Required Item retirement provider unavailable at "+std::to_string(caller);return false;}observe(s,op,caller,instance,arg,index);return true;}if(op==OwnedInventoryOperationV4::inventory_full){observe(s,op,caller,instance,arg,index);bool full;if(!is_full(full,s,e))return false;out.value=full;return true;}if(!s.invoke){e="Required owned inventory effect unavailable at "+std::to_string(caller);return false;}++callback_depth_;struct Guard{std::uint32_t& n;~Guard(){--n;}}guard{callback_depth_};if(!s.invoke(s.context,*this,{op,caller,instance,name,arg,index},out,e)){if(e.empty())e="Required owned inventory effect failed at "+std::to_string(caller);return false;}return true;}
bool FreshInventoryOwnedV4::debug(const OwnedInventoryServicesV4& s,std::uint32_t call,const char* name,std::int32_t& value,std::string& e){OwnedInventoryResponseV4 out;auto load=call-0x1c;if(call==0x40411c||call==0x403d48||call==0x403138)load=call-0x20;else if(call==0x403c2c)load=call-0x24;if(!deliver(s,OwnedInventoryOperationV4::debug_load,load,nullptr,nullptr,0,0,out,e)||!deliver(s,OwnedInventoryOperationV4::debug_query,call,nullptr,name,0,0,out,e))return false;value=out.value;return true;}
bool FreshInventoryOwnedV4::add_fixed_loot_impl(std::int32_t id,std::unique_ptr<ItemInstanceV1>& owned,bool retained,const OwnedInventoryServicesV4& s,std::string& e){
 if(!mutation_allowed(e))return false;if(running_||!s.invoke){e="Malformed fresh loot service or unsupported owner reentry";return false;}if(id<0||std::size_t(id)>=tables_.loots().size()){e.clear();return true;}running_=true;struct Guard{bool& b;~Guard(){b=false;}}guard{running_};std::int32_t ignored=0;auto trace=[&](std::uint32_t at){return debug(s,at,"isTracingItemInventory_Loot",ignored,e);};
 if(!debug(s,0x40411c,"MP_MinimalRandoms",ignored,e))return false;if(ignored){e.clear();return true;}if(!trace(0x404160)||!trace(0x404190))return false;
 const auto& loot=tables_.loots()[id];if(!loot.random_entries.empty()||!loot.sub_loots.empty()){e="Required random/subloot source continuation unavailable";return false;}
 if(!trace(0x403a20)||!trace(0x403a50)||!trace(0x403a94))return false;
 for(const auto& entry:loot.fixed_entries){if(!trace(0x403b20))return false;auto list=entry.words[0];if(list<0||std::size_t(list)>=tables_.item_lists().size()){e="Loot ItemList requires unrecovered Debug continuation";return false;}if(entry.words[1]!=-1){e="Required ItemPowerList producer unavailable";return false;}}
 if(!trace(0x403d48)||!trace(0x403c2c)||!trace(0x404264)||!trace(0x404294))return false;
 struct Prepared {std::int32_t id;std::uint8_t quantity;const Item* row;};std::vector<Prepared> selected;
 for(const auto& entry:loot.fixed_entries){const auto& list=tables_.item_lists()[entry.words[0]];std::uint32_t sum=0;for(const auto& p:list)sum+=std::uint32_t(std::int32_t(p.probability));if(list.empty()||!sum){e="ItemList weighted selection requires source Debug continuation";return false;}
  std::int32_t bound;std::memcpy(&bound,&sum,4);std::int32_t draw;if(!random_.next||!random_.next(random_.context,bound,0,draw,e)){if(e.empty())e="Invalid borrowed source RNG";return false;}std::uint32_t remainder=std::uint32_t(draw);const LootItemEntryV2* chosen=nullptr;for(const auto& p:list){auto weight=std::uint32_t(std::int32_t(p.probability));if(remainder<weight){chosen=&p;break;}remainder-=weight;}if(!chosen){e="Weighted ItemList fell through required Debug continuation";return false;}
  auto* row=item(tables_.items(),chosen->item);if(!row){e="Selected ItemID exceeds genuine ItemTable";return false;}if(!trace(0x403138))return false;selected.push_back({chosen->item,chosen->quantity,row});
 }
 if(selected.empty()){if(!trace(0x404574)||!trace(0x4045a4)||!trace(0x4041f8)||!trace(0x404228))return false;e.clear();return true;}
 if(!trace(0x4042fc)||!trace(0x40432c))return false;OwnedInventoryResponseV4 out;
 for(const auto& chosen:selected){auto type=item_type(*chosen.row);if(type==13){e="Required gold-loot valuation unavailable";return false;}std::int32_t repeats=1;auto distribution=chosen.row->record.words[4];if(distribution==2||distribution==3){if(!deliver(s,OwnedInventoryOperationV4::player_count,0x4043a8,nullptr,nullptr,0,0,out,e))return false;repeats=out.value;if(repeats<=0)continue;if(repeats>1024){e="Source player count exceeds owned budget";return false;}}
  for(std::int32_t j=0;j<repeats;++j){if(!deliver(s,OwnedInventoryOperationV4::current_player,0x4043cc,nullptr,nullptr,0,0,out,e))return false;if(out.identity){if(!deliver(s,OwnedInventoryOperationV4::current_player,0x4043dc,nullptr,nullptr,1,0,out,e))return false;if(out.value!=0){e="Required difficulty-name item variant lookup unavailable";return false;}}
   if(!(retained?create_item(chosen.id,1,RetainedItemSlotV4{&owned},s,e):create_item(chosen.id,1,owned,s,e)))return false;auto* instance=owned.get();
   std::int8_t qty;std::memcpy(&qty,&chosen.quantity,1);if(qty==-2)qty=99;if(qty<0){e="SetQty requires original negative Debug continuation";return false;}instance->quantity=std::uint16_t(qty);
   auto* valued=item(tables_.items(),instance->id);if(!valued||item_type(*valued)==13){e="Item effects changed ID into unsupported valuation continuation";return false;}auto value=std::uint32_t(valued->record.words[27])*std::uint32_t(valued->record.words[28]);for(const auto& power:instance->powers){(void)power;e="Item effects supplied unrecovered powered valuation";return false;}std::memcpy(&instance->value,&value,4);if(!deliver(s,OwnedInventoryOperationV4::update_name,0x402128,instance,nullptr,0,0,out,e))return false;
   auto* inserted=item(tables_.items(),instance->id);if(!inserted){e="Item effects changed ID outside genuine ItemTable";return false;}auto inserted_type=item_type(*inserted);
   if(potion_capacity_==0&&inserted_type==14){if(!destroy(owned,s,0x3ff70c,e))return false;continue;}
   if(!potion_&&inserted_type==14)potion_=instance;auto slot=std::make_unique<OwnedItemSlotV4>();slot->item=std::move(owned);items_.push_back(std::move(slot));auto index=std::uint32_t(items_.size()-1);if(!deliver(s,OwnedInventoryOperationV4::inventory_full,0x3ff6c4,instance,nullptr,0,index,out,e))return false;if(out.value&&!deliver(s,OwnedInventoryOperationV4::full_notifications,0x3ff7a8,instance,nullptr,0,index,out,e))return false;
  }
 }
 e.clear();return true;
}
bool FreshInventoryOwnedV4::add_fixed_loot(std::int32_t id,RetainedItemSlotV4 slot,const OwnedInventoryServicesV4& s,std::string& e){
 if(!mutation_allowed(e)||!lifetime_slot(slot,nullptr,e))return false;if(*slot.value){e="Fixed loot incoming slot already owns an item";return false;}
 return add_fixed_loot_impl(id,*slot.value,true,s,e);
}
bool FreshInventoryOwnedV4::add_fixed_loot(std::int32_t id,const OwnedInventoryServicesV4& s,std::string& e){
 std::unique_ptr<ItemInstanceV1> temporary;bool ok;try{ok=add_fixed_loot_impl(id,temporary,false,s,e);}catch(...){if(temporary)observe(s,OwnedInventoryOperationV4::destroy_item,0,temporary.get());throw;}
 if(temporary)observe(s,OwnedInventoryOperationV4::destroy_item,0,temporary.get());return ok;
}
std::int32_t FreshInventoryOwnedV4::num_potions()const noexcept{std::int16_t value=0;if(potion_)std::memcpy(&value,&potion_->quantity,2);return value;}

namespace {
std::int32_t wrap32(std::uint32_t v){std::int32_t n;std::memcpy(&n,&v,4);return n;}
}
const Item* FreshInventoryOwnedV4::metadata(const ItemInstanceV1* instance,std::string& e)const{auto* p=instance?item(tables_.items(),instance->id):nullptr;if(!p)e="Item index requires original assertion continuation";return p;}
std::int32_t FreshInventoryOwnedV4::set_for_slot(std::int32_t slot)const noexcept{return slot<0||slot==1||slot==2?selected_:0;}
std::int8_t& FreshInventoryOwnedV4::slot_for_set(OwnedItemSlotV4& slot,std::uint32_t set)noexcept{return slot.slots[set];}
bool FreshInventoryOwnedV4::inventory_full(bool& out,const OwnedInventoryServicesV4& s,std::string& e){return is_full(out,s,e);}
bool FreshInventoryOwnedV4::is_full(bool& full,const OwnedInventoryServicesV4& s,std::string& e){OwnedInventoryResponseV4 r;if(!deliver(s,OwnedInventoryOperationV4::debug_load,0x3fe364,nullptr,nullptr,0,0,r,e)||!deliver(s,OwnedInventoryOperationV4::debug_query,0x3fe3a8,nullptr,"InfiniteInventory",0,0,r,e))return false;full=!r.value&&!unlimited_&&items_.size()>99;return true;}
bool FreshInventoryOwnedV4::destroy(std::unique_ptr<ItemInstanceV1>& p,const OwnedInventoryServicesV4& s,std::uint32_t caller,std::string& e){if(!p){e="Null source item destruction";return false;}if(!s.observe_storage&&!s.stateless_temporaries){e="Required Item retirement provider unavailable at "+std::to_string(caller);return false;}observe(s,OwnedInventoryOperationV4::destroy_item,caller,p.get());p.reset();return true;}
bool FreshInventoryOwnedV4::equal(const ItemInstanceV1& a,const ItemInstanceV1& b)noexcept{return a.id==b.id&&a.powers==b.powers;}
bool FreshInventoryOwnedV4::add_quantity(ItemInstanceV1& p,std::int32_t n,std::string& e){auto q=wrap32(std::uint32_t(p.signed_quantity())+std::uint32_t(n));if(q==-2)q=99;if(q<0){e="Negative SetQty requires original assertion continuation";return false;}p.quantity=std::uint16_t(q);return true;}
bool FreshInventoryOwnedV4::lifetime_slot(RetainedItemSlotV4 slot,const ItemInstanceV1* original,std::string& e)const{
 auto at=reinterpret_cast<std::uintptr_t>(slot.value);if(!slot.value||at%alignof(std::unique_ptr<ItemInstanceV1>)||at>UINTPTR_MAX-sizeof(*slot.value)){e="Invalid borrowed Item lifetime slot";return false;}
 auto overlaps=[&](const void* p,std::size_t n){auto q=reinterpret_cast<std::uintptr_t>(p);return p&&q<=UINTPTR_MAX-n&&at<q+n&&q<at+sizeof(*slot.value);};
 if(overlaps(this,sizeof(*this))||overlaps(properties_,sizeof(*properties_))||(original&&overlaps(original,sizeof(*original)))){e="Item lifetime slot aliases an owner";return false;}
 for(const auto& cell:items_)if(overlaps(cell.get(),sizeof(*cell))||overlaps(cell->item.get(),sizeof(*cell->item))){e="Item lifetime slot aliases retained inventory storage";return false;}
 return true;
}
bool FreshInventoryOwnedV4::create_item(std::int32_t id,std::uint32_t quantity,RetainedItemSlotV4 slot,const OwnedInventoryServicesV4& s,std::string& e){
 if(!mutation_allowed(e)||!lifetime_slot(slot,nullptr,e))return false;auto& out=*slot.value;if(out||!item(tables_.items(),id)){e="Malformed constructor output or source item index";return false;}
 out=std::make_unique<ItemInstanceV1>();out->id=id;out->quantity=std::uint16_t(quantity);auto* actual=out.get();OwnedInventoryResponseV4 r;
 for(auto op:{OwnedInventoryOperationV4::update_name,OwnedInventoryOperationV4::update_stats,OwnedInventoryOperationV4::update_requirements}){
  if(!deliver(s,op,op==OwnedInventoryOperationV4::update_name?0x3fc36c:op==OwnedInventoryOperationV4::update_stats?0x3fc374:0x3fc37c,actual,nullptr,0,0,r,e))return false;
  if(out.get()!=actual){e="Constructor callback changed retained Item identity";return false;}
 }e.clear();return true;
}
bool FreshInventoryOwnedV4::create_item(std::int32_t id,std::uint32_t quantity,std::unique_ptr<ItemInstanceV1>& out,const OwnedInventoryServicesV4& s,std::string& e){
 if(!mutation_allowed(e))return false;if(out||!item(tables_.items(),id)){e="Malformed constructor output or source item index";return false;}
 if(!s.stateless_temporaries){e="Constructor requires retained Item slot or explicit stateless temporary callbacks";return false;}
 std::unique_ptr<ItemInstanceV1> temporary;
 bool ok;try{ok=create_item(id,quantity,RetainedItemSlotV4{&temporary},s,e);}
 catch(...){if(temporary)observe(s,OwnedInventoryOperationV4::destroy_item,0,temporary.get());throw;}
 if(!ok){if(temporary)observe(s,OwnedInventoryOperationV4::destroy_item,0,temporary.get());return false;}out=std::move(temporary);return true;
}
bool FreshInventoryOwnedV4::retire_item(RetainedItemSlotV4 slot,const OwnedInventoryServicesV4& s,std::string& e){
 if(!mutation_allowed(e)||!lifetime_slot(slot,nullptr,e))return false;if(!*slot.value){e="Null retained Item retirement";return false;}
 if(!s.observe_storage){e="Retained Item retirement provider unavailable";return false;}
 try{observe(s,OwnedInventoryOperationV4::destroy_item,0,slot.value->get());}catch(const std::exception& x){e=x.what();return false;}catch(...){e="Retained Item retirement provider threw";return false;}
 slot.value->reset();e.clear();return true;
}
bool FreshInventoryOwnedV4::saved_item_effect(OwnedInventoryOperationV4 op,std::uint32_t at,ItemInstanceV1* p,std::int32_t argument,std::uint32_t index,const OwnedInventoryServicesV4& s,std::string& e){if(!mutation_allowed(e))return false;if(!p||(op!=OwnedInventoryOperationV4::update_name&&op!=OwnedInventoryOperationV4::add_power)){e="Invalid direct saved Item effect";return false;}OwnedInventoryResponseV4 out;return deliver(s,op,at,p,nullptr,argument,index,out,e);}
bool FreshInventoryOwnedV4::split_item(ItemInstanceV1& original,std::int32_t amount,RetainedItemSlotV4 slot,const OwnedInventoryServicesV4& s,std::string& e){
 if(!mutation_allowed(e)||!lifetime_slot(slot,&original,e))return false;auto& out=*slot.value;if(out){e="Split output already owns an item";return false;}auto* info=metadata(&original,e);if(!info)return false;
 if(!std::uint8_t(info->record.words[7])||amount<=0||amount>=original.signed_quantity()){e.clear();return true;}
 if(!add_quantity(original,-amount,e)||!create_item(original.id,std::uint32_t(amount),slot,s,e))return false;auto* actual=out.get();out->value=original.value;OwnedInventoryResponseV4 r;
 if(!deliver(s,OwnedInventoryOperationV4::update_name,0x3fc44c,actual,nullptr,0,0,r,e))return false;if(out.get()!=actual){e="Split SetValue changed retained Item identity";return false;}
 out->identified=0;for(std::size_t i=0;i<original.powers.size();++i){if(i>65536){e="Source power iteration exceeds owned budget";return false;}auto id=original.powers[i];if(!deliver(s,OwnedInventoryOperationV4::add_power,0x3fc468,actual,nullptr,id,UINT32_MAX,r,e))return false;if(out.get()!=actual){e="Split AddPower changed retained Item identity";return false;}}
 out->identified=original.identified;e.clear();return true;
}
bool FreshInventoryOwnedV4::split_item(ItemInstanceV1& original,std::int32_t amount,std::unique_ptr<ItemInstanceV1>& out,const OwnedInventoryServicesV4& s,std::string& e){
 if(!mutation_allowed(e))return false;if(out){e="Split output already owns an item";return false;}auto* info=metadata(&original,e);if(!info)return false;if(!std::uint8_t(info->record.words[7])||amount<=0||amount>=original.signed_quantity()){e.clear();return true;}
 if(!s.stateless_temporaries){e="Split requires retained Item slot or explicit stateless temporary callbacks";return false;}
 return split_item(original,amount,RetainedItemSlotV4{&out},s,e);
}
bool FreshInventoryOwnedV4::is_equipped(std::uint32_t index,bool& out,std::string& e)const{if(index>=items_.size()||!items_[index]||!items_[index]->item){e="Equipped query requires original valid slot";return false;}auto* p=metadata(items_[index]->item.get(),e);if(!p)return false;auto slot=p->record.words[26];auto set=slot>=0||slot<-4?set_for_slot(slot):slot==-2?set_for_slot(5):slot==-1?set_for_slot(-1):set_for_slot(1);out=items_[index]->slots[set]!=-1;e.clear();return true;}
bool FreshInventoryOwnedV4::has_like(const ItemInstanceV1* p,std::uint32_t& index,bool& found,std::string& e)const{found=false;for(std::size_t i=0;i<items_.size();++i){auto* candidate=items_[i]->item.get();if(candidate&&candidate!=p&&equal(*candidate,*p)){bool equipped;if(!is_equipped(std::uint32_t(i),equipped,e))return false;if(!equipped){index=std::uint32_t(i);found=true;break;}}}return true;}
bool FreshInventoryOwnedV4::delete_instance(ItemInstanceV1* p,const OwnedInventoryServicesV4& s,std::string& e){if(potion_==p)potion_=nullptr;for(std::size_t i=0;i<items_.size();++i)if(items_[i]->item.get()==p){for(const auto& set:equipment_)for(auto* cell:set)if(cell==items_[i].get()){e="Source invalid deletion of a still-equipped slot";return false;}if(!s.observe_storage&&!s.stateless_temporaries){e="Required Item retirement provider unavailable at "+std::to_string(0x3fe838);return false;}observe(s,OwnedInventoryOperationV4::destroy_item,0x3fe838,p,0,std::uint32_t(i));items_.erase(items_.begin()+std::ptrdiff_t(i));e.clear();return true;}e.clear();return true;}
bool FreshInventoryOwnedV4::set_gold(std::int32_t value,const OwnedInventoryServicesV4& s,std::string& e){if(!mutation_allowed(e))return false;if(value<0){e="Negative SetGold requires original assertion continuation";return false;}gold_=value<=gold_limit_?value:gold_limit_;OwnedInventoryResponseV4 out;if(!deliver(s,OwnedInventoryOperationV4::gold_notifications,0x3fdfd8,nullptr,nullptr,0,0,out,e))return false;e.clear();return true;}
bool FreshInventoryOwnedV4::add_gold(std::int32_t amount,const OwnedInventoryServicesV4& s,std::string& e){if(!mutation_allowed(e))return false;if(amount<0){auto neg=wrap32(0u-std::uint32_t(amount));if(gold_<neg)amount=wrap32(0u-std::uint32_t(gold_));}if(amount>0){auto room=wrap32(std::uint32_t(gold_limit_)-std::uint32_t(gold_));if(amount>room)amount=room<0?0:room;}return set_gold(wrap32(std::uint32_t(gold_)+std::uint32_t(amount)),s,e);}
bool FreshInventoryOwnedV4::add_item(std::unique_ptr<ItemInstanceV1>& incoming,bool force,bool convert_gold,std::int32_t& index,const OwnedInventoryServicesV4& s,std::string& e){if(!mutation_allowed(e))return false;auto* info=metadata(incoming.get(),e);if(!info)return false;auto* p=incoming.get();index=-1;if(potion_capacity_==0&&item_type(*info)==14)return destroy(incoming,s,0x3ff70c,e);if(!potion_&&item_type(*info)==14)potion_=p;if(convert_gold&&item_type(*info)==13){if(!add_gold(p->value,s,e))return false;return destroy(incoming,s,0x3ff744,e);}if(std::uint8_t(info->record.words[7])&&!force){for(std::size_t i=0;i<items_.size();++i){auto* candidate=items_[i]->item.get();if(!candidate)continue;bool equipped;if(!is_equipped(std::uint32_t(i),equipped,e))return false;if(equipped||!equal(*candidate,*p))continue;auto qty=p->signed_quantity();info=metadata(p,e);if(!info)return false;if(item_type(*info)==14){auto room=wrap32(std::uint32_t(std::int32_t(potion_capacity_))-std::uint32_t(candidate->signed_quantity()));if(room<qty)qty=room<0?0:room;}if(!add_quantity(*candidate,qty,e))return false;index=std::int32_t(i);return destroy(incoming,s,0x3ff794,e);}}auto slot=std::make_unique<OwnedItemSlotV4>();slot->item=std::move(incoming);items_.push_back(std::move(slot));auto i=std::uint32_t(items_.size()-1);bool full;observe(s,OwnedInventoryOperationV4::inventory_full,0x3ff6c4,p,0,i);if(!is_full(full,s,e))return false;if(full){OwnedInventoryResponseV4 r;if(!deliver(s,OwnedInventoryOperationV4::full_notifications,0x3ff7a8,p,nullptr,0,i,r,e))return false;}index=std::int32_t(items_.size()-1);e.clear();return true;}
bool FreshInventoryOwnedV4::has_two_hander(bool ignore,bool& out,std::string& e)const{out=false;auto* slot=equipment_[set_for_slot(1)][1];if(!slot){e.clear();return true;}auto* p=metadata(slot->item.get(),e);if(!p)return false;auto type=item_type(*p);auto slotting=p->record.words[26];out=(std::uint32_t(type)-4<=1||ignore)?slotting==-4:slotting==-4&&properties_->resolved[203]==0;e.clear();return true;}
bool FreshInventoryOwnedV4::unequip_from_slot(std::uint32_t slot,std::int32_t selected,const OwnedInventoryServicesV4& s,std::string& e){if(!mutation_allowed(e))return false;if(slot>=9||selected<-1||selected>1){e="UnEquip assertion domain unsupported";return false;}auto active=selected==-1?set_for_slot(std::int32_t(slot)):selected;auto* old=equipment_[active][slot];equipment_[active][slot]=nullptr;if(!old){e.clear();return true;}old->slots[active]=-1;if(old->slots[0]!=-1||old->slots[1]!=-1){e.clear();return true;}auto* info=metadata(old->item.get(),e);if(!info)return false;if(!std::uint8_t(info->record.words[7])){e.clear();return true;}std::uint32_t index=0;bool found;if(!has_like(old->item.get(),index,found,e))return false;if(!found){e.clear();return true;}bool equipped;if(!is_equipped(index,equipped,e))return false;if(equipped){e.clear();return true;}if(!add_quantity(*items_[index]->item,old->item->signed_quantity(),e))return false;return delete_instance(old->item.get(),s,e);}
bool FreshInventoryOwnedV4::equip_to_slot_impl(std::uint32_t requested,std::uint32_t index,bool forced,std::unique_ptr<ItemInstanceV1>& remainder,bool retained,const OwnedInventoryServicesV4& s,std::string& e){if(!mutation_allowed(e))return false;if(requested>=9||index>=items_.size()){e="Equip assertion domain unsupported";return false;}auto* slot=items_[index].get();if(!slot||!slot->item){e.clear();return true;}auto active=set_for_slot(std::int32_t(requested));auto* info=metadata(slot->item.get(),e);if(!info)return false;auto slotting=info->record.words[26];auto type=item_type(*info);if(type!=5&&type!=4&&slotting==-4&&properties_->resolved[203])slotting=1;if(info->record.words[26]==-1){e.clear();return true;}auto old=slot->slots[active];if(old==std::int32_t(requested)&&equipment_[active][requested]==slot){e.clear();return true;}if(!unequip_from_slot(requested,-1,s,e))return false;old=slot->slots[active];if(old!=-1){if(old<0||old>=9){e="Invalid live equipment slot byte";return false;}if(equipment_[active][std::uint32_t(old)]==slot&&!unequip_from_slot(std::uint32_t(old),-1,s,e))return false;}auto target=requested;if(slotting==-4){if(!forced&&!unequip_from_slot(2,-1,s,e))return false;if(!unequip_from_slot(1,-1,s,e))return false;target=1;}else if(requested==2){bool two;if(!has_two_hander(false,two,e))return false;if(two&&!forced&&!unequip_from_slot(1,-1,s,e))return false;}if(slot->item->signed_quantity()!=1){if(!(retained?split_item(*slot->item,slot->item->signed_quantity()-1,RetainedItemSlotV4{&remainder},s,e):split_item(*slot->item,slot->item->signed_quantity()-1,remainder,s,e)))return false;if(!remainder){e="Source Equip split failed required assertion continuation";return false;}}equipment_[active][target]=slot;equipment_[active][target]->slots[active]=std::int8_t(target);if(remainder){std::int32_t added;return add_item(remainder,true,true,added,s,e);}e.clear();return true;}
bool FreshInventoryOwnedV4::equip_to_slot(std::uint32_t requested,std::uint32_t index,bool forced,RetainedItemSlotV4 slot,const OwnedInventoryServicesV4& s,std::string& e){if(!lifetime_slot(slot,nullptr,e))return false;if(*slot.value){e="Equip remainder already owns an item";return false;}return equip_to_slot_impl(requested,index,forced,*slot.value,true,s,e);}
bool FreshInventoryOwnedV4::equip_to_slot(std::uint32_t requested,std::uint32_t index,bool forced,const OwnedInventoryServicesV4& s,std::string& e){std::unique_ptr<ItemInstanceV1> remainder;bool ok;try{ok=equip_to_slot_impl(requested,index,forced,remainder,false,s,e);}catch(...){if(remainder)observe(s,OwnedInventoryOperationV4::destroy_item,0,remainder.get());throw;}if(remainder)observe(s,OwnedInventoryOperationV4::destroy_item,0,remainder.get());return ok;}
bool FreshInventoryOwnedV4::auto_equip(std::uint32_t index,std::int32_t& result,const OwnedInventoryServicesV4& s,std::string& e){if(!mutation_allowed(e))return false;result=0;if(index>=items_.size()){e="AutoEquip assertion domain unsupported";return false;}auto* slot=items_[index].get();auto* info=metadata(slot->item.get(),e);if(!info)return false;auto slotting=info->record.words[26];if(slotting==-1){e.clear();return true;}auto type=item_type(*info);if(type!=5&&type!=4){if(slotting==1&&properties_->resolved[202])slotting=-3;else if(slotting==-4&&properties_->resolved[203])slotting=1;}if(slotting>=0&&slotting<9){if(slotting==2){bool two;if(!has_two_hander(false,two,e))return false;if(two&&!unequip_from_slot(1,-1,s,e))return false;}if(!equip_to_slot(std::uint32_t(slotting),index,false,s,e))return false;}else if(slotting==-3||slotting==-2){auto first=slotting==-3?1u:5u;auto second=first+1;auto chosen=first;if(equipment_[set_for_slot(std::int32_t(first))][first]){if(equipment_[set_for_slot(std::int32_t(second))][second]){e.clear();return true;}chosen=second;}if(!equip_to_slot(chosen,index,false,s,e))return false;}else if(slotting==-4){if(!unequip_from_slot(2,-1,s,e)||!equip_to_slot(1,index,false,s,e))return false;}else{e.clear();return true;}result=1;e.clear();return true;}
bool FreshInventoryOwnedV4::character_auto_equip(std::uint32_t index,std::int32_t& result,const OwnedInventoryServicesV4& s,std::string& e){if(!mutation_allowed(e))return false;std::int32_t captured;if(!auto_equip(index,captured,s,e))return false;OwnedInventoryResponseV4 r;for(auto op:{OwnedInventoryOperationV4::update_gear_properties,OwnedInventoryOperationV4::skin,OwnedInventoryOperationV4::validate_hp_mp})if(!deliver(s,op,op==OwnedInventoryOperationV4::update_gear_properties?0x3a9fc0:op==OwnedInventoryOperationV4::skin?0x3a9fc8:0x3a9fd0,nullptr,nullptr,0,0,r,e))return false;result=captured;e.clear();return true;}
}
