#!/usr/bin/env python3
"""Generate immutable source field tables from checked original initializer output."""
import argparse
import hashlib
import json
from pathlib import Path
import struct
REPO=Path(__file__).resolve().parents[1]
TRACE_SHA='94201dae07d7dee055afef052670d65433b8f9fae53f2db42556803e2002b464'
def main():
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args()
    path=REPO/'reports/pydata-struct-name-trace.json';raw=path.read_bytes()
    assert hashlib.sha256(raw).hexdigest()==TRACE_SHA
    trace=json.loads(raw);assert trace['table_count']==71 and trace['names']==636
    lines=['/* Generated by tools/generate_pydata_struct_names.py; see RIGHTS.md. */',
           '/* Original initializer trace SHA-256: '+TRACE_SHA+' */',
           'struct dh2_builtin_name_table { const char *name; const unsigned char *bytes; unsigned size; };']
    for i,row in enumerate(trace['tables']):
        names=[name.encode('ascii')for name in row['names']]
        data=struct.pack('<I',len(names))+b''.join(struct.pack('<I',len(name))+name for name in names)
        lines.append('static const unsigned char dh2_struct_names_%u[] = {'%i)
        for off in range(0,len(data),24):lines.append('    '+','.join(str(b)for b in data[off:off+24])+',')
        lines.append('};')
    lines.append('static const struct dh2_builtin_name_table dh2_struct_name_tables[] = {')
    for i,row in enumerate(trace['tables']):
        lines.append('    {%s, dh2_struct_names_%u, sizeof(dh2_struct_names_%u)},'%(json.dumps(row['registered_name']),i,i))
    lines.append('};');text='\n'.join(lines)+'\n'
    target=REPO/'port/pydata-names/struct-names.h'
    if a.check:assert target.read_bytes()==text.encode('ascii')
    else:target.write_text(text,encoding='ascii',newline='\n')
    print(json.dumps({'tables':71,'fields':636,'unique_registered_names':len({r['registered_name']for r in trace['tables']}),
                      'header_sha256':hashlib.sha256(target.read_bytes()).hexdigest(),'checked':a.check}))
if __name__=='__main__':main()
