// The runner extracts the unchanged positive-test fixture prefix into this
// generated header, retaining its exact source hash. No old fixture is edited.
#include "character-level-runtime-fixture.hpp"
#include "../character_level_runtime.hpp"
#include <limits>
namespace lr=dh2::character_level_runtime;
struct NativeFixture:PositiveFixture {
 lr::Runtime runtime;lr::Result last_native{};dh2::data::PropertyView native_view{};lr::DesignBinding binding{};
 bool mutate_hp_during_save=false;
 using PositiveFixture::PositiveFixture;
 lr::Storage storage(){native_view=property_view(*rules,properties);binding={application.design_manager,design};return {owner,reinterpret_cast<std::uintptr_t>(&properties),properties.base.data(),&native_view,rows.data(),std::uint32_t(rows.size()),&binding,1,&debug_globals,&debug_services};}
 static int mutating_write(void* p,const dp::Request* request,dp::Stream* reply){auto& s=*static_cast<NativeFixture*>(static_cast<PositiveFixture*>(p));const auto rc=PositiveFixture::write_operation(p,request,reply);if(request->operation==dp::Operation::open_write&&s.mutate_hp_during_save){s.mutate_hp_during_save=false;auto view=property_view(*s.rules,s.properties);require(!dh2_property_add(&view,36,64),"live debug-time property mutation failed");}return rc;}
 static int native_set_level(void* p,std::uintptr_t id,float raw){auto& s=*static_cast<NativeFixture*>(static_cast<Fixture*>(p));s.subject(id);++s.set_level_calls;auto storage=s.storage();sl::Globals globals{&s.application};const auto status=s.runtime.set_level_fixed(&storage,&globals,raw,&s.last_native);s.last_level=s.last_native.level;return status==lr::Status::complete?0:1;}
 void load_native(ms::Source common,ms::Source monster){std::string error;auto services=Fixture::services();services.set_level=native_set_level;require(vm.create(services,error)==ms::Status::complete&&vm.bind_functions(error)==ms::Status::complete&&vm.load_common(common,error)==ms::Status::complete&&vm.load_external(monster,error)==ms::Status::complete,error.c_str());}
 void check_positive(const std::vector<unsigned char>& configuration){require(last_native.level.applied&&last_native.number_reads==2&&last_native.design_reads==1&&last_native.class_result==0&&last_native.hp_attempted&&last_native.mp_attempted&&last_native.hp.positive_amount&&last_native.mp.positive_amount&&last_native.hp.added&&last_native.mp.added,"native caller/class/regen composition differs");require(properties.resolved[36]==properties.resolved[38]&&properties.resolved[41]==properties.resolved[43]&&runtime.retained_strings()==0,"native live add or string lifetime differs");require(debug_globals.loaded&&debug_owner.switches().size()==24&&debug_owner.switches().at("isTracingChar_Stats")==0&&read_opens==1&&read_closes==1&&save_calls==5&&write_opens==5&&write_closes==5&&read(filename.string())==configuration,"native source debug/persistence effects differ");}
};
struct Numbers {lr::Runtime* runtime;lr::Storage* storage;sl::Globals* globals;float first=256,second=512;unsigned reads=0;bool reenter=false;lr::Status reentry{};static int invoke(void* p,std::uintptr_t id,std::uint32_t* out){auto& s=*static_cast<Numbers*>(p);require(id==0x9191,"wrong live argument identity");if(s.reenter){lr::Result result{};s.reentry=s.runtime->set_level_fixed(s.storage,s.globals,256,&result);}*out=bits(s.reads++?s.second:s.first);return 0;}};
int main(int argc,char** argv){try{
 require(argc==5,"pass cache/common/monster/temp-folder");const std::string root=std::string(argv[1])+"/data/pydata/";std::string error;
 auto cp=read(root+"character_properties_pyarray.bin"),cn=read(root+"character_properties_pyarraynames.bin"),cs=read(root+"character_properties_pystructnames.bin");CharacterTable characters;PropertyRules rules;require(load_characters(bytes(cp),bytes(cn),bytes(cs),characters,error)&&load_property_rules(characters,rules,error),error.c_str());
 auto ca=read(root+"character_classes_pyarray.bin"),can=read(root+"character_classes_pyarraynames.bin"),cas=read(root+"character_classes_pystructnames.bin"),design_bytes=read(root+"design_pycst.bin");ClassTables classes;require(load_classes(bytes(ca),bytes(can),bytes(cas),classes,error),error.c_str());dh2_pycst_view design{};require(!dh2_pycst_open(&design,design_bytes.data(),design_bytes.size()),"design cache rejected");
 auto la=read(root+"levels_pyarray.bin"),lan=read(root+"levels_pyarraynames.bin"),las=read(root+"levels_pystructnames.bin");LevelTables levels;require(load_levels(bytes(la),bytes(lan),bytes(las),levels,error),error.c_str());
 const auto configuration=read(std::string(argv[1])+"/DebugSwitches.savegame");auto common_bytes=read(argv[2]),monster_bytes=read(argv[3]);ms::Source common{common_bytes.data(),common_bytes.size()},monster{monster_bytes.data(),monster_bytes.size()};const std::filesystem::path folder(argv[4]);unsigned cases=0,positive_cases=0;
 for(auto name:{"Crypt_Ghost","Crypt_Ghost_RE"})for(auto level_name:{"GOTHICUS_CRYPT_01","SWAMP","INFECTED_VILLAGE_01"})for(int mode=0;mode<3;++mode){NativeFixture f(characters,classes,rules,design,name,folder/std::to_string(cases),configuration);f.levels=&levels;f.level_oid=find_level(levels,level_name);f.difficulty=mode;f.properties.saved[36]-=256;f.properties.saved[41]-=256;f.load_native(common,monster);require(f.vm.dispatch(ms::Event::init,0,error)==ms::Status::complete,error.c_str());f.check_positive(configuration);std::int32_t minimum=0;require(read_level_range_word(levels,f.level_oid*72,0x3c+mode*4,minimum)&&f.properties.base[19]==minimum*256,"native actual level range differs");require(f.vm.dispatch(ms::Event::enemy_spotted,0x1234567800000091ull,error)==ms::Status::complete&&f.target==0x1234567800000091ull,"native same-VM acquisition callback differs");++cases;++positive_cases;}
 {NativeFixture f(characters,classes,rules,design,"Crypt_Ghost",folder/std::to_string(cases),configuration);auto storage=f.storage();storage.debug_globals=nullptr;storage.debug_services=nullptr;sl::Globals globals{&f.application};lr::Result result{};require(f.runtime.set_level_fixed(&storage,&globals,256,&result)==lr::Status::complete&&!result.hp.positive_amount&&!result.mp.positive_amount&&f.save_calls==0,"zero-delta native call required debug provider");++cases;}
 {NativeFixture f(characters,classes,rules,design,"Crypt_Ghost",folder/std::to_string(cases),configuration);auto storage=f.storage();storage.debug_globals=nullptr;storage.debug_services=nullptr;sl::Globals globals{&f.application};lr::Result result{};const auto saved=f.properties.saved;require(f.runtime.set_level_fixed(&storage,&globals,512,&result)==lr::Status::debug_failed&&f.properties.base[19]==512&&f.properties.saved==saved&&result.level.applied&&result.hp_attempted&&!result.mp_attempted,"missing positive debug rolled back live class/Level effects");++cases;}
 {NativeFixture f(characters,classes,rules,design,"Crypt_Ghost",folder/std::to_string(cases),configuration);auto storage=f.storage();sl::Globals globals{&f.application};lr::Result result{};const ClassFormula formulas[]={{20,9,177,0,0},{224,9,1,0,0}};const ClassRow rows[]={{formulas,2}};storage.classes=rows;storage.class_count=1;f.properties.base[26]=0;const auto before=f.properties.resolved;require(f.runtime.set_level_fixed(&storage,&globals,512,&result)==lr::Status::class_failed&&result.class_result==4&&f.properties.base[19]==512&&f.properties.base[20]==177&&f.properties.resolved==before&&result.level.applied&&!result.hp_attempted&&!result.mp_attempted&&f.save_calls==0,"class failure used atomic copy/commit");++cases;}
 for(float raw:{std::numeric_limits<float>::quiet_NaN(),std::numeric_limits<float>::infinity(),-std::numeric_limits<float>::infinity(),2147483648.0f,-2147483904.0f}){NativeFixture f(characters,classes,rules,design,"Crypt_Ghost",folder/std::to_string(cases),configuration);auto storage=f.storage();sl::Globals globals{&f.application};lr::Result result{};const auto before=f.properties;require(f.runtime.set_level_fixed(&storage,&globals,raw,&result)==lr::Status::unsupported_numeric&&!result.level.applied&&f.properties.base==before.base&&f.properties.saved==before.saved&&f.save_calls==0,"unsupported numeric helper invented a value");++cases;}
 for(float raw:{-2147483648.0f,-0.0f,0.0f,127.75f,256.0f,30000.0f,2147483520.0f}){NativeFixture f(characters,classes,rules,design,"Crypt_Ghost",folder/std::to_string(cases),configuration);auto storage=f.storage();sl::Globals globals{&f.application};lr::Result result{};require(f.runtime.set_level_fixed(&storage,&globals,raw,&result)==lr::Status::complete,"finite numeric adapter rejected supported input");const auto expected=raw>25600?25600:std::int32_t(raw);require(f.properties.base[19]==expected&&result.level.clamped==unsigned(raw>25600)&&result.number_reads==(raw>25600?1u:2u)&&result.design_reads==(raw>25600?2u:1u),"finite numeric truncation/clamp source order differs");++cases;}
 {NativeFixture f(characters,classes,rules,design,"Crypt_Ghost",folder/std::to_string(cases),configuration);auto storage=f.storage();sl::Globals globals{&f.application};sl::Arguments args{0x9191,1,3};Numbers sequence{&f.runtime,&storage,&globals};sequence.reenter=true;lr::NumberServices numbers{&sequence,Numbers::invoke};lr::Result result{};require(f.runtime.set_level(&storage,&args,&globals,&numbers,&result)==lr::Status::complete&&f.properties.base[19]==512&&sequence.reads==2&&sequence.reentry==lr::Status::busy,"fresh numbers or native owner reentry differ");++cases;}
 {NativeFixture f(characters,classes,rules,design,"Crypt_Ghost",folder/std::to_string(cases),configuration);auto storage=f.storage();sl::Globals globals{&f.application};storage.design_count=0;lr::Result result{};const auto before=f.properties.base;require(f.runtime.set_level_fixed(&storage,&globals,256,&result)==lr::Status::design_missing&&f.properties.base==before&&!result.level.applied,"missing design invented a constant");++cases;}
 {NativeFixture f(characters,classes,rules,design,"Crypt_Ghost",folder/std::to_string(cases),configuration);auto storage=f.storage();sl::Globals globals{&f.application};const lr::DesignBinding duplicate[]={{f.application.design_manager,nullptr},{f.application.design_manager,&design}};storage.designs=duplicate;storage.design_count=2;lr::Result result{};require(f.runtime.set_level_fixed(&storage,&globals,256,&result)==lr::Status::design_missing&&!result.level.applied,"ambiguous design ownership accepted");++cases;}
 {NativeFixture f(characters,classes,rules,design,"Crypt_Ghost",folder/std::to_string(cases),configuration);auto storage=f.storage();sl::Globals globals{&f.application};sl::Arguments args{0x9191,1,3};Numbers sequence{&f.runtime,&storage,&globals};sequence.second=std::numeric_limits<float>::quiet_NaN();lr::NumberServices numbers{&sequence,Numbers::invoke};lr::Result result{};const auto before=f.properties.base;require(f.runtime.set_level(&storage,&args,&globals,&numbers,&result)==lr::Status::unsupported_numeric&&sequence.reads==2&&!result.level.applied&&f.properties.base==before,"invalid second source number reused first value");++cases;}
 {NativeFixture f(characters,classes,rules,design,"Crypt_Ghost",folder/std::to_string(cases),configuration);const auto maximum=f.properties.resolved[38];f.properties.saved[36]-=256;f.mutate_hp_during_save=true;f.write_services={static_cast<PositiveFixture*>(&f),NativeFixture::mutating_write};auto storage=f.storage();sl::Globals globals{&f.application};lr::Result result{};require(f.runtime.set_level_fixed(&storage,&globals,256,&result)==lr::Status::complete&&result.hp.current==std::uint32_t(maximum-256)&&result.hp.maximum==std::uint32_t(maximum)&&result.hp.positive_amount==256&&f.properties.resolved[36]==maximum+64,"debug mutation replaced captured amount or live property add");++cases;}
 {NativeFixture f(characters,classes,rules,design,"Crypt_Ghost",folder/std::to_string(cases),configuration);auto storage=f.storage();sl::Globals globals{nullptr};sl::Arguments args{0x9191,0,0};lr::NumberServices numbers{};storage.base=nullptr;storage.view=nullptr;lr::Result result{};require(f.runtime.set_level(&storage,&args,&globals,&numbers,&result)==lr::Status::complete&&!result.level.calls,"empty source argument required unused providers");++cases;}
 {NativeFixture f(characters,classes,rules,design,"Crypt_Ghost",folder/std::to_string(cases),configuration);auto storage=f.storage();sl::Globals globals{&f.application};sl::Arguments args{0x9191,1,3};lr::NumberServices numbers{};lr::Result result{};require(f.runtime.set_level(&storage,&args,&globals,&numbers,&result)==lr::Status::number_unavailable&&!result.level.applied,"missing argument reader fabricated number");++cases;}
 {NativeFixture f(characters,classes,rules,design,"Crypt_Ghost",folder/std::to_string(cases),configuration);f.properties.saved[36]-=256;auto storage=f.storage();sl::Globals globals{&f.application};lr::Result result{};f.fail_write_at=2;require(f.runtime.set_level_fixed(&storage,&globals,256,&result)==lr::Status::debug_failed&&f.debug_globals.loaded&&f.save_calls==1&&f.write_closes==0&&!result.hp.added&&!result.mp_attempted,"native source file failure added stats or closed resources");++cases;}
 {NativeFixture f(characters,classes,rules,design,"Crypt_Ghost",folder/std::to_string(cases),configuration);auto storage=f.storage();sl::Globals globals{&f.application};lr::Result result{};require(f.runtime.set_level_fixed(nullptr,&globals,256,&result)==lr::Status::invalid_argument,"null native storage accepted");storage.view->saved=storage.base;require(f.runtime.set_level_fixed(&storage,&globals,256,&result)==lr::Status::invalid_argument,"aliased mutable native sheets accepted");++cases;}
 std::printf("{\"validation\":\"PASS\",\"host_cases\":%u,\"unchanged_on_init_positive_cases\":%u,\"live_non_atomic_class_property_kernel\":true,\"actual_design_constants\":true,\"finite_f2iz_only\":true,\"actual_source_debug_and_real_file_backend\":true,\"native_runtime_adapter\":true,\"android_wired\":false}\n",cases,positive_cases);return 0;
}catch(const std::exception& error){std::fprintf(stderr,"character level runtime: %s\n",error.what());return 1;}}
