#include "../character_combat_queries.hpp"
#include <array>
#include <cstring>
#include <fstream>
#include <iostream>
#include <iterator>
#include <stdexcept>
using namespace dh2;
namespace {void check(bool value,const std::string& message){if(!value)throw std::runtime_error(message);}std::vector<std::uint8_t> read(const std::string& p){std::ifstream f(p,std::ios::binary);check(bool(f),"Missing "+p);return {std::istreambuf_iterator<char>(f),{}};}data::Bytes view(const std::vector<std::uint8_t>& b){return {b.data(),b.size()};}struct Reader{std::vector<std::uint8_t> bytes;std::size_t at=0;explicit Reader(const char* path):bytes(read(path)){}unsigned word(){check(at+4<=bytes.size(),"Short combat query corpus");unsigned v;std::memcpy(&v,bytes.data()+at,4);at+=4;return v;}};}
int main(int argc,char** argv){try{
 if(argc!=3)return 2;
 Reader r(argv[1]);check(r.word()==0x31435143,"CQC1 magic differs");const auto count=r.word(),itemcount=r.word(),bankcount=r.word(),seqcount=r.word();std::vector<character::CombatItemRecord164> items(itemcount);for(auto& row:items)row.words[22]=int(r.word());std::vector<character::CombatAnimationBank8> banks(bankcount);for(auto& row:banks)row.attack_sequence=int(r.word());std::vector<std::int32_t> types(seqcount);for(auto& t:types)t=int(r.word());
 unsigned range=0,inventory=0,combo=0;const auto sentinel=INT32_MIN;
 for(unsigned i=0;i<count;++i){const auto op=r.word();const int bank=int(r.word()),prop=int(r.word());const auto current=r.word();const int h0=int(r.word()),h1=int(r.word()),attack=int(r.word()),type=int(r.word());const auto expected=r.word();character::CombatProperties896 properties{};properties.words[2]=bank;properties.words[32]=prop;
  character::CombatItemInstance4 instances[]={{h0},{h1}};const character::CombatItemInstance4* refs[]={&instances[0],&instances[1]};character::CombatEquipSet8 sets[]={{h0<0?nullptr:&refs[0]},{h1<0?nullptr:&refs[1]}};character::CombatInventory16 equipped{sets,2,int(current)};
  const auto selected=bank>=0&&unsigned(bank)<bankcount?unsigned(bank):17u;const auto prior=banks[selected].attack_sequence;if(attack!=sentinel)banks[selected].attack_sequence=attack;const auto target=banks[selected].attack_sequence;int prior_type=0;if(type!=sentinel&&target>=0&&unsigned(target)<seqcount){prior_type=types[target];types[target]=type;}
  const auto before=properties;int result=0;switch(op){case 0:result=dh2_character_can_range_attack(&properties,&equipped,items.data(),itemcount);++range;break;case 1:result=dh2_inventory_has_ranged_weapon(&equipped,items.data(),itemcount);++inventory;break;case 2:result=dh2_character_has_combo_attack(&properties,banks.data(),bankcount,types.data(),seqcount);++combo;break;default:return 3;}
  check(unsigned(result)==expected,"Combat query original record differs: "+std::to_string(i));check(!std::memcmp(&before,&properties,sizeof(before)),"Read-only query wrote properties");if(type!=sentinel&&target>=0&&unsigned(target)<seqcount)types[target]=prior_type;banks[selected].attack_sequence=prior;
 }
 check(r.at==r.bytes.size(),"Trailing query corpus bytes");
 const std::string assets=argv[2];auto raw=read(assets+"/data/character_properties_pyarray.bin"),names=read(assets+"/data/character_properties_pyarraynames.bin"),fields=read(assets+"/data/character_properties_pystructnames.bin");data::CharacterTable properties;std::string error;check(data::load_characters(view(raw),view(names),view(fields),properties,error),error);
 auto dn=read(assets+"/data/animations_dictionary_pyarraynames.bin"),dv=read(assets+"/data/animations_dictionary_pyarray.bin"),ar=read(assets+"/data/animations_pyarray.bin"),an=read(assets+"/data/animations_pyarraynames.bin"),af=read(assets+"/data/animations_pystructnames.bin");data::Dictionary dictionary;data::AnimationTables table;check(data::load_dictionary(view(dn),view(dv),dictionary,error)&&data::load_animation_tables(view(ar),view(an),view(af),dictionary,table,error),error);
 unsigned bridges=0;for(const auto& row:properties.rows){character::CombatProperties896 cached{};std::copy(row.begin(),row.end(),cached.words);check(character::has_combo_attack(cached,table)==dh2_character_has_combo_attack(&cached,banks.data(),bankcount,types.data(),seqcount),"Decoded real table bridge differs");++bridges;}
 unsigned guards=0;auto guard=[&](bool v){check(v,"Native borrowed span guard differs");++guards;};character::CombatProperties896 cached{};cached.words[32]=0;
 guard(dh2_character_can_range_attack(&cached,nullptr,nullptr,0)==1);guard(dh2_character_can_range_attack(nullptr,nullptr,nullptr,0)==-1);cached.words[32]=-1;guard(dh2_character_can_range_attack(&cached,nullptr,nullptr,0)==-1);
 character::CombatEquipSet8 sets[2]{};character::CombatInventory16 equipped{sets,2,0};guard(dh2_inventory_has_ranged_weapon(&equipped,nullptr,0)==0);equipped.current_set=-1;guard(dh2_inventory_has_ranged_weapon(&equipped,items.data(),itemcount)==-1);equipped.current_set=2;guard(dh2_inventory_has_ranged_weapon(&equipped,items.data(),itemcount)==-1);equipped.current_set=0;equipped.count=0;guard(dh2_inventory_has_ranged_weapon(&equipped,items.data(),itemcount)==-1);equipped.count=2;
 const character::CombatItemInstance4* reference=nullptr;sets[0].main_hand=&reference;guard(dh2_inventory_has_ranged_weapon(&equipped,items.data(),itemcount)==-1);character::CombatItemInstance4 instance{-1};reference=&instance;guard(dh2_inventory_has_ranged_weapon(&equipped,items.data(),itemcount)==-1);instance.item_id=itemcount;guard(dh2_inventory_has_ranged_weapon(&equipped,items.data(),itemcount)==-1);instance.item_id=0;guard(dh2_inventory_has_ranged_weapon(&equipped,nullptr,0)==-1);
 guard(dh2_character_has_combo_attack(nullptr,banks.data(),bankcount,types.data(),seqcount)==-1);cached.words[2]=-1;guard(dh2_character_has_combo_attack(&cached,banks.data(),1,types.data(),seqcount)==-1);cached.words[2]=0;guard(dh2_character_has_combo_attack(&cached,nullptr,bankcount,types.data(),seqcount)==-1);banks[0].attack_sequence=0;guard(dh2_character_has_combo_attack(&cached,banks.data(),bankcount,nullptr,seqcount)==-1);
 std::cout<<"{\"validation\":\"PASS\",\"comparisons\":"<<count<<",\"range_queries\":"<<range<<",\"inventory_queries\":"<<inventory<<",\"combo_queries\":"<<combo<<",\"real_table_bridges\":"<<bridges<<",\"native_guards\":"<<guards<<",\"sanitizer_findings\":0,\"mismatches\":0}\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 3;}}
