#include "../character_ai_events.hpp"
#include <array>
#include <cstring>
#include <dlfcn.h>
#include <fstream>
#include <iostream>
#include <iterator>
#include <stdexcept>
#include <vector>
using namespace dh2::character;
namespace {
void check(bool value,const char* message){if(!value)throw std::runtime_error(message);}
struct Reader {std::vector<unsigned char> bytes;std::size_t at=0;explicit Reader(const char* path){std::ifstream file(path,std::ios::binary);check(bool(file),"Missing AI events gold");bytes={std::istreambuf_iterator<char>(file),{}};}template<class T>T get(){check(at+sizeof(T)<=bytes.size(),"Truncated AI events gold");T value;std::memcpy(&value,bytes.data()+at,sizeof(T));at+=sizeof(T);return value;}};
constexpr std::uintptr_t base=0x100000000ull;
std::uintptr_t native(std::uintptr_t value){return value?base+value*0x10000:0;}
std::uintptr_t id(std::uintptr_t value){return value>=base?(value-base)/0x10000:value;}
using Snapshot=std::array<unsigned char,160>;using Event=std::array<unsigned char,204>;
struct Context {AIEventState64 state{};std::array<AIEventOwner48,2> owners{};std::array<std::array<std::uintptr_t,51>,4> tables{};std::array<unsigned,6> params{};std::vector<Event> events;unsigned fail=~0u;};
Snapshot snapshot(const Context& c){Snapshot out{};const std::uintptr_t pointers[5]={id(c.state.ai),c.state.owner==&c.owners[0]?2u:3u,c.state.ai_virtuals==c.tables[0].data()?4u:5u,id(c.state.active),c.state.ais_virtuals==c.tables[2].data()?7u:8u};std::memcpy(out.data(),pointers,40);std::memcpy(out.data()+40,&c.state.paused,24);
 for(unsigned i=0;i<2;++i){auto owner=c.owners[i];std::array<std::uintptr_t,4> p{};std::memcpy(p.data(),&owner,32);for(auto& value:p)value=id(value);std::memcpy(&owner,p.data(),32);std::memcpy(out.data()+64+i*48,&owner,48);}return out;}
void put(Context& c,const Snapshot& raw){std::array<std::uintptr_t,5> p{};std::memcpy(p.data(),raw.data(),40);c.state.ai=native(p[0]);c.state.owner=&c.owners[p[1]==3];c.state.ai_virtuals=c.tables[p[2]==5].data();c.state.active=native(p[3]);c.state.ais_virtuals=c.tables[2+(p[4]==8)].data();std::memcpy(&c.state.paused,raw.data()+40,24);
 for(unsigned i=0;i<2;++i){std::memcpy(&c.owners[i],raw.data()+64+i*48,48);std::array<std::uintptr_t,4> values{};std::memcpy(values.data(),&c.owners[i],32);for(auto& value:values)value=native(value);std::memcpy(&c.owners[i],values.data(),32);}for(unsigned table=0;table<4;++table)for(unsigned slot=0;slot<51;++slot)c.tables[table][slot]=native((table+1)*100+slot);}
Snapshot seed(){Context c;c.state={native(1),&c.owners[0],c.tables[0].data(),native(6),c.tables[2].data(),255,0,0,0,0,0};c.owners[0]={native(2),native(10),native(12),native(14),0,0,0,0};c.owners[1]={native(3),native(11),native(13),native(15),0,0,0,0};return snapshot(c);}
void mutate(Context& c,unsigned service){if(c.params[4]!=service||!c.params[3])return;switch(c.params[3]){case 1:c.state.owner=&c.owners[1];break;case 2:c.state.ai_virtuals=c.tables[1].data();break;case 3:c.state.active=0;break;case 4:c.state.active=native(6);c.state.ais_virtuals=c.tables[3].data();break;case 5:c.state.paused=255;break;case 6:c.state.seeking=255;break;case 7:c.state.global_blocked=255;break;case 8:c.owners[0].forced=c.owners[0].locked=255;break;default:throw std::runtime_error("Bad event mutation");}}
int invoke(void* opaque,AIEventState64*,const AIEventRequest40* source,unsigned* value){auto& c=*static_cast<Context*>(opaque);*value=source->service==2?c.params[0]:source->service==4?c.params[1]:source->service==3?c.params[2]:0;auto request=*source;request.subject=id(request.subject);request.callee=id(request.callee);request.payload=id(request.payload);Event event{};const auto raw=snapshot(c);std::memcpy(event.data(),&request,40);std::memcpy(event.data()+40,raw.data(),160);std::memcpy(event.data()+200,value,4);c.events.push_back(event);mutate(c,source->service);if(c.fail==source->service)return 17;
 if(source->service==1&&source->operation==0x90&&c.params[5]==1){AIEventResult16 result{};AIEventServices24 services{&c,invoke,63,0};check(dh2_character_ai_event_script_timer(&result,&c.state,source->argument,&services)==0,"Actual script timer relay failed");}
 if(source->service==1&&c.params[5]==2){AIEventResult16 result{};AIEventServices24 services{&c,invoke,63,0};AIEventPayload24 payload{};check(dh2_character_ai_event(&result,&c.state,0x31,&payload,&services)==0,"Actual nested event31 failed");}return 0;}
}
int main(int argc,char**argv){try{check(argc==2,"usage: character_ai_events_audit event-gold");Reader reader(argv[1]);check(reader.get<unsigned>()==0x31454143,"Wrong event gold");const auto cases=reader.get<unsigned>();unsigned requests=0,composed=0,reentry=0;const auto clean=seed();
 for(unsigned i=0;i<cases;++i){Context c;put(c,reader.get<Snapshot>());const auto event=reader.get<unsigned>(),payload_id=reader.get<unsigned>();c.params=reader.get<std::array<unsigned,6>>();const auto expected=reader.get<Snapshot>();const auto count=reader.get<unsigned>();std::vector<Event> expected_events;for(unsigned j=0;j<count;++j)expected_events.push_back(reader.get<Event>());AIEventPayload24 payload{native(payload_id),native(450),0,0};AIEventServices24 services{&c,invoke,63,0};AIEventResult16 result{};check(dh2_character_ai_event(&result,&c.state,event,&payload,&services)==0&&result.phase==7&&snapshot(c)==expected&&c.events==expected_events,"Original event state/order differs");requests+=count;composed+=c.params[5]==1;reentry+=c.params[5]==2;}
 check(reader.at==reader.bytes.size(),"Trailing events gold");unsigned guards=0,missing=0,failures=0;
 for(unsigned kind=0;kind<46;++kind){Context c;put(c,clean);AIEventPayload24 payload{native(16),native(450),0,0};AIEventServices24 services{&c,invoke,63,0};AIEventResult16 result{11,12,13,14};auto* output=&result;auto* state=&c.state;auto* input=&payload;auto* callback=&services;
  switch(kind){case 0:output=nullptr;break;case 1:state=nullptr;break;case 2:input=nullptr;break;case 3:callback=nullptr;break;case 4:output=reinterpret_cast<AIEventResult16*>(&c.state);break;case 5:output=reinterpret_cast<AIEventResult16*>(&services);break;case 6:output=reinterpret_cast<AIEventResult16*>(&payload);break;case 7:output=reinterpret_cast<AIEventResult16*>(&c.owners[0]);break;case 8:state=reinterpret_cast<AIEventState64*>(&services);break;case 9:callback=reinterpret_cast<AIEventServices24*>(&c.state);break;case 10:input=reinterpret_cast<AIEventPayload24*>(&result);break;case 11:input=reinterpret_cast<AIEventPayload24*>(&services);break;case 12:input=reinterpret_cast<AIEventPayload24*>(&c.state);break;case 13:input=reinterpret_cast<AIEventPayload24*>(&c.owners[0]);break;case 14:c.state.owner=reinterpret_cast<AIEventOwner48*>(&c.state);break;case 15:c.state.owner=reinterpret_cast<AIEventOwner48*>(&services);break;case 16:c.state.owner=reinterpret_cast<AIEventOwner48*>(&result);break;case 17:c.state.owner=reinterpret_cast<AIEventOwner48*>(&payload);break;case 18:c.state.ai=0;break;case 19:c.state.owner=nullptr;break;case 20:c.state.paused=256;break;case 21:c.state.seeking=256;break;case 22:c.state.global_blocked=256;break;case 23:c.state.reserved0=1;break;case 24:c.state.reserved1=1;break;case 25:c.state.reserved2=1;break;case 26:c.owners[0].owner=0;break;case 27:c.owners[0].controller=0;break;case 28:c.owners[0].state_machine=0;break;case 29:c.owners[0].properties=0;break;case 30:c.owners[0].forced=256;break;case 31:c.owners[0].locked=256;break;case 32:c.owners[0].reserved0=1;break;case 33:c.owners[0].reserved1=1;break;case 34:services.invoke=nullptr;break;case 35:services.available=64;break;case 36:services.reserved=1;break;case 37:payload.reserved0=1;break;case 38:payload.reserved1=1;break;case 39:c.state.ai_virtuals=reinterpret_cast<std::uintptr_t*>(&c.state);break;case 40:c.state.ai_virtuals=reinterpret_cast<std::uintptr_t*>(&services);break;case 41:c.state.ai_virtuals=reinterpret_cast<std::uintptr_t*>(&c.owners[0]);break;case 42:c.state.ai_virtuals=reinterpret_cast<std::uintptr_t*>(&payload);break;case 43:c.state.ai_virtuals=reinterpret_cast<std::uintptr_t*>(&result);break;case 44:c.state.ais_virtuals=reinterpret_cast<std::uintptr_t*>(&c.state);break;case 45:c.state.ais_virtuals=reinterpret_cast<std::uintptr_t*>(&c.owners[0]);break;default:throw std::runtime_error("Bad guard");}
  const auto prior=c;const auto prior_result=result;const auto prior_payload=payload;const auto prior_services=services;check(dh2_character_ai_event(output,state,0x35,input,callback)==1&&!std::memcmp(&c.state,&prior.state,64)&&!std::memcmp(c.owners.data(),prior.owners.data(),96)&&!std::memcmp(&result,&prior_result,16)&&!std::memcmp(&payload,&prior_payload,24)&&!std::memcmp(&services,&prior_services,24)&&c.events.empty(),"Malformed event partially committed");++guards;
 }
 const unsigned event_for_service[6]={0,2,0x35,0x33,0x1d,0x35};
 for(unsigned service=0;service<6;++service){Context c;put(c,clean);AIEventPayload24 payload{native(16),native(450),0,0};AIEventServices24 callbacks{&c,invoke,63u^(1u<<service),0};AIEventResult16 out{};const auto status=service==5?dh2_character_ai_event_script_timer(&out,&c.state,0x80000000,&callbacks):dh2_character_ai_event(&out,&c.state,event_for_service[service],&payload,&callbacks);check(status==2&&out.phase==service+1&&out.last_service==service&&c.events.empty(),"Unavailable event service accepted");++missing;}
 for(unsigned service=0;service<6;++service){Context c;put(c,clean);c.params={0,3,1,1,service,0};c.fail=service;AIEventPayload24 payload{native(16),native(450),0,0};AIEventServices24 callbacks{&c,invoke,63,0};AIEventResult16 out{};const auto status=service==5?dh2_character_ai_event_script_timer(&out,&c.state,0x80000000,&callbacks):dh2_character_ai_event(&out,&c.state,event_for_service[service],&payload,&callbacks);check(status==3&&out.phase==service+1&&out.last_service==service&&c.events.size()==1&&c.state.owner==&c.owners[1],"Event failure effects hidden");++failures;}
 // Explicit missing callable and source inactive relay checks.
 unsigned callables=0;for(unsigned mode=0;mode<3;++mode){Context c;put(c,clean);AIEventPayload24 payload{native(16),mode==0?0:native(450),0,0};AIEventServices24 services{&c,invoke,63,0};AIEventResult16 out{};if(mode==1)c.state.ai_virtuals=nullptr;if(mode==2)c.state.ais_virtuals=nullptr;const auto status=mode==2?dh2_character_ai_event_script_timer(&out,&c.state,~0u,&services):dh2_character_ai_event(&out,&c.state,0x35,&payload,&services);check(status==2&&c.events.size()==(mode==1?1u:0u),"Missing captured callable accepted");++callables;}
 Context inactive;put(inactive,clean);inactive.state.active=0;inactive.state.ais_virtuals=nullptr;AIEventServices24 empty{&inactive,invoke,0,0};AIEventResult16 result{};check(dh2_character_ai_event_script_timer(&result,&inactive.state,~0u,&empty)==0&&result.phase==7&&inactive.events.empty(),"Inactive AIS relay invoked a fake service");
 Dl_info dispatcher{},relay{};check(dladdr(reinterpret_cast<void*>(&dh2_character_ai_event),&dispatcher)&&dladdr(reinterpret_cast<void*>(&dh2_character_ai_event_script_timer),&relay),"Actual DSO bindings missing");std::cout<<"{\"validation\":\"PASS\",\"comparisons\":"<<cases<<",\"ordered_service_requests\":"<<requests<<",\"composed_script_timer_cases\":"<<composed<<",\"original_reentry_cases\":"<<reentry<<",\"atomic_rejections\":"<<guards<<",\"unavailable_services\":"<<missing<<",\"missing_callables\":"<<callables<<",\"runtime_failure_prefixes\":"<<failures<<",\"inactive_relay\":true,\"dispatcher_library\":\""<<dispatcher.dli_fname<<"\",\"relay_library\":\""<<relay.dli_fname<<"\",\"sanitizer_findings\":0}\n";return 0;
 }catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
