#include "../character_scene.hpp"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <fstream>
#include <iostream>
#include <stdexcept>
using namespace dh2::physical;
static void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
template<class T>static T read(std::ifstream& in){T value{};in.read(reinterpret_cast<char*>(&value),sizeof value);require(bool(in),"truncated fixture");return value;}
static bool equal(const void* a,const void* b,std::size_t n){const auto* x=static_cast<const unsigned char*>(a);const auto* y=static_cast<const unsigned char*>(b);for(std::size_t i=0;i<n;i+=4){float p,q;std::memcpy(&p,x+i,4);std::memcpy(&q,y+i,4);if(std::memcmp(x+i,y+i,4)&&!(std::isnan(p)&&std::isnan(q)))return false;}return true;}
int main(int argc,char** argv){try{
 require(argc==3,"character scene audit requires fixture and Prince BRES");std::ifstream in(argv[1],std::ios::binary);require(read<std::uint32_t>(in)==0x31534348,"fixture magic");const auto skins=read<std::uint32_t>(in),meshes=read<std::uint32_t>(in),visual_scales=read<std::uint32_t>(in),owner_bounds=read<std::uint32_t>(in);
 for(unsigned i=0;i<skins;++i){const auto count=read<std::uint32_t>(in),box_count=read<std::uint32_t>(in);std::vector<dh2::math::Matrix4f> matrices(count);std::vector<float> boxes(box_count*6);in.read(reinterpret_cast<char*>(matrices.data()),matrices.size()*68);in.read(reinterpret_cast<char*>(boxes.data()),boxes.size()*4);float expected[6],actual[6];in.read(reinterpret_cast<char*>(expected),24);require(bool(in),"skin fixture");const CharacterSkinBoundsInput input{matrices.data(),boxes.data(),count,box_count};require(dh2_character_skin_bounds(actual,&input)==0&&equal(expected,actual,24),"original joint bounds differ");}
 CharacterMeshEntry prince_expected{};DecorSceneInput prince_placement{};DecorSceneOutput prince_output{};
 for(unsigned i=0;i<meshes;++i){const auto count=read<std::uint32_t>(in);const auto placement=read<DecorSceneInput>(in);std::vector<CharacterMeshEntry> entries(count);in.read(reinterpret_cast<char*>(entries.data()),entries.size()*40);const auto expected=read<DecorSceneOutput>(in);DecorSceneOutput actual{};const CharacterMeshBoxInput input{entries.data(),count,0,placement};require(dh2_character_mesh_box(&actual,&input)==0&&equal(&expected,&actual,sizeof actual),"original GetMeshBox differs");if(i==0){require(count==1,"Prince modular fixture");prince_expected=entries[0];prince_placement=placement;prince_output=expected;}}
 for(unsigned i=0;i<visual_scales;++i){std::int32_t properties[3];float expected[3],actual[3];in.read(reinterpret_cast<char*>(properties),12);in.read(reinterpret_cast<char*>(expected),12);require(bool(in),"visual scale fixture");require(dh2_character_visual_scale(actual,properties)==0&&!std::memcmp(expected,actual,12),"original visual scale differs");}
 for(unsigned i=0;i<owner_bounds;++i){const auto input=read<CharacterOwnerBoundsInput>(in);const auto expected=read<CharacterOwnerBounds>(in);CharacterOwnerBounds actual{};require(dh2_character_owner_bounds(&actual,&input)==0&&equal(&expected,&actual,48)&&!std::memcmp(&expected.flat,&actual.flat,8),"original character owner bounds differ");}
 require(in.peek()==std::char_traits<char>::eof(),"fixture suffix");std::ifstream model(argv[2],std::ios::binary);require(bool(model),"Prince BRES missing");std::vector<std::uint8_t> bytes{std::istreambuf_iterator<char>(model),std::istreambuf_iterator<char>()};dh2::resources::BresView view{};require(dh2_bres_open(&view,bytes.data(),bytes.size())==dh2::resources::BresError::ok,"Prince BRES open");dh2::scene::Scene scene;std::string error;require(dh2::scene::load(view,scene,error),"Prince scene load");const auto prince=std::find_if(scene.graph.begin(),scene.graph.end(),[](const auto& n){return n.id=="prince_modular-node";});require(prince!=scene.graph.end(),"Prince group missing");const auto prince_node=static_cast<unsigned>(prince-scene.graph.begin());scene.instances.clear();
 for(unsigned controller=0;controller<dh2_bres_library_count(&view,dh2::resources::Library::controller);++controller){dh2::skinning::Skin skin;require(dh2::skinning::load(view,controller,scene,skin,error),"Prince skin load");if(skin.id.find("_default_warrior-mesh-skin")==std::string::npos)continue;dh2::scene::Instance instance{prince->id,prince_node,skin.geometry,prince->world,{}};instance.controller=controller;scene.instances.push_back(instance);}
 require(scene.instances.size()==4,"selected warrior controllers differ");std::vector<CharacterMeshEntry> entries;require(character_scene_entries(view,scene,entries,error),error.c_str());require(entries.size()==1&&!std::memcmp(&entries.front(),&prince_expected,sizeof prince_expected),"native selected equipment bounds differ");DecorSceneOutput actual{};CharacterMeshBoxInput input{entries.data(),static_cast<std::uint32_t>(entries.size()),0,prince_placement};require(dh2_character_mesh_box(&actual,&input)==0&&!std::memcmp(&actual,&prince_output,sizeof actual),"native Prince GetMeshBox differs");
 // The native geometry instance belongs to the authored SNode group. That
 // group's scale is the original geometry child's immediate parent scale;
 // the graph group's parent is the provider's grandparent.
 auto altered=scene;dh2::scene::Node grandparent;grandparent.scale[0]=7;grandparent.scale[1]=11;grandparent.scale[2]=13;altered.graph.push_back(grandparent);altered.graph[prince_node].parent=static_cast<int>(altered.graph.size()-1);altered.graph[prince_node].scale[0]=2;altered.graph[prince_node].scale[1]=3;altered.graph[prince_node].scale[2]=4;std::vector<CharacterMeshEntry> changed;require(character_scene_entries(view,altered,changed,error),"different group/grandparent scales");require(changed.size()==1&&changed[0].parent_scale[0]==2&&changed[0].parent_scale[1]==3&&changed[0].parent_scale[2]==4&&!std::memcmp(changed[0].bounds,prince_expected.bounds,24),"provider parent scale mapping differs");
 unsigned negative=0;float bounds[6];std::fill(bounds,bounds+6,123.0f);float before[6];std::copy(bounds,bounds+6,before);CharacterSkinBoundsInput bad{};bad.joint_count=1;require(dh2_character_skin_bounds(bounds,&bad)==-1&&!std::memcmp(bounds,before,24),"missing joint changed output");++negative;dh2::math::Matrix4f matrix{};bad.joints=&matrix;bad.box_count=1;require(dh2_character_skin_bounds(bounds,&bad)==-1,"missing boxes");++negative;bad.box_count=0;bad.joint_count=257;require(dh2_character_skin_bounds(bounds,&bad)==-1,"joint count overflow");++negative;bad.joint_count=1;matrix.identity_hint=2;require(dh2_character_skin_bounds(bounds,&bad)==-1,"identity byte malformed");++negative;require(dh2_character_skin_bounds(nullptr,&bad)==-1&&dh2_character_skin_bounds(bounds,nullptr)==-1,"null bounds arguments");negative+=2;
 const auto output_before=actual;input.reserved=1;require(dh2_character_mesh_box(&actual,&input)==-1&&!std::memcmp(&actual,&output_before,sizeof actual),"reserved metadata changed output");++negative;input.reserved=0;auto malformed=entries.front();malformed.skinned=2;input.entries=&malformed;require(dh2_character_mesh_box(&actual,&input)==-1,"provider kind malformed");++negative;input.entries=nullptr;require(dh2_character_mesh_box(&actual,&input)==-1,"missing providers");++negative;require(dh2_character_mesh_box(nullptr,&input)==-1&&dh2_character_mesh_box(&actual,nullptr)==-1,"null mesh arguments");negative+=2;
 auto missing_joint=scene;missing_joint.graph.clear();const auto entry_before=entries;require(!character_scene_entries(view,missing_joint,entries,error)&&entries.size()==entry_before.size()&&!std::memcmp(entries.data(),entry_before.data(),sizeof prince_expected),"invalid bridge mutated entries");++negative;
 CharacterOwnerBounds owner_out{};const auto owner_before=owner_out;CharacterOwnerBoundsInput owner_input{};owner_input.already_scaled=2;require(dh2_character_owner_bounds(&owner_out,&owner_input)==-1&&!std::memcmp(&owner_out,&owner_before,sizeof owner_out),"invalid owner metadata changed output");++negative;owner_input.already_scaled=0;owner_input.previous_flat=256;require(dh2_character_owner_bounds(&owner_out,&owner_input)==-1,"invalid owner byte");++negative;require(dh2_character_owner_bounds(nullptr,&owner_input)==-1&&dh2_character_owner_bounds(&owner_out,nullptr)==-1,"null owner arguments");negative+=2;float visual[3];std::int32_t properties[3]{};require(dh2_character_visual_scale(nullptr,properties)==-1&&dh2_character_visual_scale(visual,nullptr)==-1,"null visual scale arguments");negative+=2;
 std::cout<<"{\"skin_comparisons\":"<<skins<<",\"mesh_comparisons\":"<<meshes<<",\"visual_scale_comparisons\":"<<visual_scales<<",\"owner_bounds_comparisons\":"<<owner_bounds<<",\"selected_prince_controllers\":4,\"parent_grandparent_scale_mapping_checks\":1,\"malformed_checks\":"<<negative<<",\"mismatches\":0,\"sanitizers\":\"address,undefined\",\"optimization\":\"O1,no fast math,fp-contract off\"}\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
