#include "player_saved_inventory_v1_fixture.hpp"
#include "../player_saved_inventory_v1.hpp"
namespace saved=dh2::player_saved_inventory_v1;
struct ExpectedItem {std::array<std::uint32_t,7> words;std::vector<std::int32_t> powers;};
struct SavedCase {Raw payload;unsigned failure;std::array<std::uint32_t,13> summary;std::vector<ExpectedItem> items;};
struct SavedWorld:World {
 data::PlayerSavegameV1 save;std::unique_ptr<data::ItemInstanceV1> incoming;
 std::unique_ptr<saved::Runtime> reader;Raw active_payload;unsigned failure=0,reentry_checks=0;
 bool saved_reenter=false,mutate_character=false,destructive_probe=false;
 data::ItemTextServicesV5 actual_text{};
 SavedWorld(Tables& t,const std::filesystem::path& cache,const char* name):World(t,cache,name){
  runtime.reset();real_text=true;save.set_character(CHARACTER);hooks.required.invoke=required_saved;
  actual_text=item_text->services();reader=std::make_unique<saved::Runtime>(saved::Bindings{&save,inventory.get(),&view,&effects,t.powers.borrow(),&incoming});
 }
 ~SavedWorld(){reader.reset();if(incoming){std::string e;ck(presentation->forget(*incoming,e),e);incoming.reset();}}
 void probe_saved(){if(saved_reenter){saved_reenter=false;saved::Result out{};out.consumed=991;auto before=out;std::string e="sentinel";ck(reader->load(span(active_payload),&out,e)==saved::Status::busy&&!std::memcmp(&out,&before,sizeof out)&&e=="sentinel","saved inventory callback reentry changed output");++reentry_checks;}}
 static const data::Item* power_metadata(void* p,const data::ItemInstanceV1& i,std::string& e){auto& s=*static_cast<SavedWorld*>(p);return s.actual_text.metadata(s.actual_text.context,i,e);}
 static bool power_text(void* p,data::ItemInstanceV1& i,const data::ItemTextRequestV5& q,data::ItemTextResponseV5& r,std::string& out,std::string& e){auto& s=*static_cast<SavedWorld*>(p);if(s.failure==3){e="explicit reached power localization failure";return false;}return s.actual_text.invoke(s.actual_text.context,i,q,r,out,e);}
 static bool required_saved(void* raw,data::FreshInventoryOwnedV4& i,const data::OwnedInventoryRequestV4& q,data::OwnedInventoryResponseV4& r,std::string& e){auto& s=*static_cast<SavedWorld*>(raw);s.probe_saved();using O=data::OwnedInventoryOperationV4;
  if(s.destructive_probe&&q.source_caller==0x3fbc5c){s.destructive_probe=false;std::string denied;const auto before=i.gold();ck(!i.set_gold(993,s.effects,denied)&&i.gold()==before&&!denied.empty(),"direct Item callback bypassed sole inventory destructive reentry guard");++s.reentry_checks;}
  if(q.operation==O::gold_notifications&&s.failure==1){e="explicit gold notification failure";return false;}
  if(q.operation==O::update_name&&q.source_caller==0x3fbc5c){if(s.mutate_character)s.save.set_character(CHARACTER+16);if(s.failure==2){e="explicit SetValue name failure";return false;}}
  if(q.operation==O::debug_load&&q.source_caller==0x3fe364&&s.failure==4){e="explicit fullness failure after owned Item storage";return false;}
  if(q.operation==O::add_power){ck(q.item&&q.index==UINT32_MAX,"saved AddPower changed source -1 mode");return s.presentation->add_power(*q.item,q.argument,-1,{&s,power_metadata,power_text},e);}
  return World::required(&s,i,q,r,e);
 }
 std::array<std::uint32_t,13> summary(saved::Status status,const saved::Result& r){return {status==saved::Status::failed,r.consumed,std::uint32_t(inventory->gold()),std::uint32_t(inventory->current_equipment()),r.constructors,r.set_values,r.identified_stores,r.add_powers,r.add_items,r.equips,r.completed_items,bool(incoming),std::uint32_t(inventory->items().size())};}
 void compare_item(const data::ItemInstanceV1& actual,const ExpectedItem& expected,const data::OwnedItemSlotV4* slot){const auto& w=expected.words;
  ck(std::uint32_t(actual.id)==w[0]&&actual.quantity==w[1]&&std::uint32_t(actual.value)==w[2]&&actual.identified==w[3]&&actual.powers==expected.powers,"actual owned Item differs from original GEAR prefix");
  if(slot)ck(std::uint32_t(std::int32_t(slot->slots[0]))==w[4]&&std::uint32_t(std::int32_t(slot->slots[1]))==w[5],"actual equipment sets differ from source temporary selection order");
  if(!actual.powers.empty()){const auto* full=presentation->powers(actual);ck(full&&full->size()==actual.powers.size(),"actual ItemPresentation authority did not retain source powers");for(unsigned j=0;j<full->size();++j)ck((*full)[j].id==actual.powers[j],"actual power IDs diverged from full state");}
 }
};
static Raw make_payload(const data::ItemTable& table,std::int32_t id,std::uint32_t qty=1,std::int32_t first=-1,std::int32_t second=-1){Raw b;auto word=[&](std::uint32_t n){for(unsigned j=0;j<4;++j)b.push_back(std::uint8_t(n>>(j*8)));};word(29);word(1);word(1);const auto& name=table.identifiers.at(id);word(name.size()+1);b.insert(b.end(),name.begin(),name.end());b.push_back(0);word(first);word(second);word(qty);word(113);b.push_back(0);word(0);return b;}
int main(int argc,char** argv){try{
 ck(argc==3,"saved inventory needs cache and private original cases");std::filesystem::path cache=argv[1];Tables tables(cache);std::ifstream f(argv[2],std::ios::binary);ck(read_gold<unsigned>(f)==0x31495653,"saved inventory original magic differs");auto n=read_gold<unsigned>(f);std::vector<SavedCase> cases;
 while(n--){SavedCase c;auto size=read_gold<unsigned>(f);c.failure=read_gold<unsigned>(f);c.payload.resize(size);f.read(reinterpret_cast<char*>(c.payload.data()),size);ck(bool(f));c.summary=read_gold<decltype(c.summary)>(f);auto count=c.summary[11]+c.summary[12];while(count--){ExpectedItem i;i.words=read_gold<decltype(i.words)>(f);for(unsigned p=0;p<i.words[6];++p)i.powers.push_back(std::int32_t(read_gold<unsigned>(f)));c.items.push_back(i);}cases.push_back(std::move(c));}
 unsigned original=0,prefixes=0,guards=0,classes=0,read_prefixes=0;
 for(const char* name:{"KnightPlayerBase","MagePlayerBase","RoguePlayerBase"}){for(const auto& c:cases){SavedWorld world(tables,cache,name);world.failure=c.failure;world.active_payload=c.payload;const auto before=world.properties;const auto random=world.random;saved::Result r;std::string e;const auto status=world.reader->load(span(c.payload),&r,e);
  ck(status==(c.failure?saved::Status::failed:saved::Status::complete),"original GEAR status differs: "+e);ck(world.summary(status,r)==c.summary,"original caller read/store/count prefix differs");ck(!std::memcmp(&before,&world.properties,sizeof before)&&!std::memcmp(&random,&world.random,sizeof random)&&!world.updates&&!world.skin_calls&&!world.vitals,"GEAR caller invented RNG/property/Skin/vitals tail");
  for(unsigned j=0;j<world.inventory->items().size();++j)world.compare_item(*world.inventory->items()[j]->item,c.items[j],world.inventory->items()[j].get());
  if(world.incoming)world.compare_item(*world.incoming,c.items.back(),nullptr);
  ck(!r.completed_powers||r.completed_powers==r.declared_powers,"successful source power loop skipped records");if(c.failure){ck(!e.empty(),"source required failure lacked error");++prefixes;}++original;
 }++classes;}
 {SavedWorld world(tables,cache,"KnightPlayerBase");world.active_payload=cases[3].payload;world.saved_reenter=true;world.destructive_probe=true;saved::Result r;std::string e;ck(world.reader->load(span(world.active_payload),&r,e)==saved::Status::complete,e);guards+=world.reentry_checks;
  r.consumed=919;const auto before=r;e="sentinel";for(auto* p:{static_cast<void*>(world.reader.get()),static_cast<void*>(&world.save),static_cast<void*>(world.inventory.get()),static_cast<void*>(&world.properties),static_cast<void*>(&world.view),static_cast<void*>(&world.effects),static_cast<void*>(&world.incoming),static_cast<void*>(world.inventory->items()[0]->item.get())}){ck(world.reader->load(span(world.active_payload),reinterpret_cast<saved::Result*>(p),e)==saved::Status::invalid_argument&&e=="sentinel","saved result aliases borrowed controls");++guards;}
  auto& actual_name=world.inventory->items()[0]->item->name;auto name=actual_name;ck(world.reader->load(span(world.active_payload),&r,actual_name)==saved::Status::invalid_argument&&actual_name==name&&!std::memcmp(&r,&before,sizeof r),"saved error aliases authored Item text");++guards;
  auto bytes=data::Bytes{reinterpret_cast<const std::uint8_t*>(world.properties.base.data()),12};ck(world.reader->load(bytes,&r,e)==saved::Status::invalid_argument&&e=="sentinel"&&!std::memcmp(&r,&before,sizeof r),"saved bytes alias property authority");++guards;
  auto& identifier=const_cast<std::string&>(world.inventory->table().identifiers[world.yes_item]);auto authored=identifier;ck(world.reader->load(span(world.active_payload),&r,identifier)==saved::Status::invalid_argument&&identifier==authored&&!std::memcmp(&r,&before,sizeof r),"saved error aliases authored Item identifier");++guards;
  auto& power=const_cast<std::string&>(tables.powers.borrow().names()[0]);authored=power;ck(world.reader->load(span(world.active_payload),&r,power)==saved::Status::invalid_argument&&power==authored&&!std::memcmp(&r,&before,sizeof r),"saved error aliases authored Power identifier");++guards;
 }
 for(unsigned text_at:{1u,2u,3u}){SavedWorld world(tables,cache,"KnightPlayerBase");world.fail_text=text_at;saved::Result r;std::string e;ck(world.reader->load(span(cases[3].payload),&r,e)==saved::Status::failed&&!world.incoming&&world.inventory->items().empty()&&r.stage==saved::Stage::construct,"existing V4 constructor boundary published a failed local allocation");++prefixes;}
 {SavedWorld world(tables,cache,"KnightPlayerBase");world.mutate_character=true;saved::Result r;std::string e;ck(world.reader->load(span(cases[3].payload),&r,e)==saved::Status::failed&&r.stage==saved::Stage::add_item&&world.incoming&&world.incoming->identified==1&&world.inventory->items().empty(),"fresh Save Character producer ignored retained Item prefix");++prefixes;
  auto before=r;auto text=e;ck(world.reader->load(span(cases[3].payload),&r,e)==saved::Status::invalid_argument&&text==e&&!std::memcmp(&before,&r,sizeof r),"pending incoming failure replayed or destroyed prefix");++guards;}
 {SavedWorld world(tables,cache,"KnightPlayerBase");const auto id=world.yes_item;auto b=make_payload(world.inventory->table(),id,2,1);saved::Result r;std::string e;ck(world.reader->load(span(b),&r,e)==saved::Status::failed&&r.stage==saved::Stage::equip_first&&world.inventory->items().size()==1&&!world.incoming&&world.inventory->current_equipment()==0&&r.selection_stores==2,"failed source Equip restored selection or erased retained Item");++prefixes;}
 const auto& blob=cases[3].payload;for(unsigned size:{0u,3u,4u,8u,12u,16u,unsigned(blob.size()-1)}){SavedWorld world(tables,cache,"KnightPlayerBase");saved::Result r;std::string e;ck(world.reader->load({blob.data(),size},&r,e)==saved::Status::failed&&!e.empty(),"truncated GEAR claimed completion");ck(r.consumed<=size&&!r.constructors&&!world.incoming&&world.inventory->items().empty(),"truncated caller crossed item allocation");if(size<12)ck(!world.inventory->gold()&&!r.selection_stores,"header truncation mutated gold/selection before all source words");if(size==8)ck(r.source_caller==0x46a420,"truncated header failure caller address lost");++read_prefixes;}
 {SavedWorld world(tables,cache,"KnightPlayerBase");auto b=blob;b[12]=0;b[13]=b[14]=b[15]=0;saved::Result r;std::string e;ck(world.reader->load(span(b),&r,e)==saved::Status::failed&&r.stage==saved::Stage::item_name&&r.consumed==16&&world.inventory->gold()==8,"source zero-length assertion lost header prefix");++read_prefixes;}
 {SavedWorld world(tables,cache,"KnightPlayerBase");data::PropertySheet buff=tables.rules.defaults;const std::int32_t* sheets[]{buff.data()};data::PropertyBuffGroup group{sheets,1};world.view.groups=&group;world.view.group_count=1;saved::Result r;std::string e;ck(world.reader->load(span(cases.back().payload),&r,e)==saved::Status::complete&&world.view.groups==&group&&world.view.groups[0].sheets[0]==buff.data(),"GEAR replaced sole grouped PropertyView");++guards;}
 std::cout<<"{\"validation\":\"PASS\",\"original_caller_cases\":"<<cases.size()<<",\"class_caller_comparisons\":"<<original<<",\"actual_player_classes\":"<<classes<<",\"failure_prefix_cases\":"<<prefixes<<",\"read_prefix_cases\":"<<read_prefixes<<",\"guard_cases\":"<<guards<<",\"checks\":"<<checks<<",\"actual_profile_items\":6,\"actual_profile_powers\":1,\"native_SG4_InitPost\":false,\"text_files\":[";bool comma=false;for(const auto& name:text_files){if(comma)std::cout<<',';comma=true;std::cout<<'\"'<<name<<'\"';}std::cout<<"]}\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
