"""Verify packaged combat application, live hits/deaths and renderer retention."""
import argparse,hashlib,json,re,subprocess,zipfile
from pathlib import Path
from emulator_smoke import inspect
from validate_world_checkpoint import digest,read,log,ROOT,REPO
from validate_combat_checkpoint import exports
def main():
 p=argparse.ArgumentParser();p.add_argument('--studio',type=Path,required=True);p.add_argument('--host-build',default='/home/adampalace/dh2-world-build');a=p.parse_args();local=REPO/'.local-inputs';apk=ROOT/'app/build/outputs/apk/debug/app-debug.apk';sha=digest(apk);libraries=inspect(apk);assert len(libraries)==14
 prior=read(ROOT/'reports/build-validation-health.json');states=read(local/'actor-states-tests-combat-application/actor-states-smoke.json');world=read(local/'world-tests-combat-application/world-smoke.json');live=read(local/'combat-application-tests/combat-application-smoke.json');oracle_path=REPO/'port/game-data/reports/combat-application-arm64-differential.json';oracle=read(oracle_path);host=read(local/'combat-application-host-audit.json');health=read(local/'combat-application-health-regression.json')
 assert states['apk_sha256']==world['apk_sha256']==world['installed_apk_sha256']==live['apk_sha256']==live['installed_apk_sha256']==sha
 assert len(states['cases'])==24 and len(world['cases'])==10 and live['native_hits_verified']==18 and len(live['pairs'])==3
 for key in ('authored_animation_events_verified','base_class_snapshots_verified','resolved_property_snapshots_verified','spawn_vitals_verified','independent_idle_instances_verified','state5_attack_event_decisions_verified','frozen_attack_events_absent_verified','packaged_combat_result_probes_verified','packaged_health_probes_verified','combat_execution_implemented','live_combat_health_application_implemented'):assert states[key],key
 assert states['health_probe_count']==22 and states['combat_result_probe_count']==11 and not states['full_combat_or_ai_implemented']
 for key,path in [('original_class_report_sha256','game-data/reports/classes-regression-vitals.json'),('original_property_report_sha256','game-data/reports/properties-arm64-differential.json'),('original_vitals_report_sha256','game-data/reports/vitals-arm64-differential.json'),('original_event_report_sha256','engine-animation/reports/events-arm64-differential.json'),('original_combat_event_report_sha256','game-data/reports/combat-events-application-arm64-differential.json'),('original_combat_result_report_sha256','game-data/reports/combat-result-arm64-differential.json'),('original_health_report_sha256','game-data/reports/health-arm64-differential.json')]:assert states[key]==digest(REPO/'port'/path)
 assert len(states['three_stage_attacks'])==len(states['one_stage_deaths'])==3
 for row in states['three_stage_attacks']:
  assert len(row['animation_events'])==len(row['combat_actions'])==1;event=row['animation_events'][0];action=row['combat_actions'][0];assert event[1]=='attack_mainhand' and event[-1]==1 and action[:2]==event[:2] and action[2]==1 and action[3] in (0,1,2) and action[4:]==[0,0,0,-1]
 assert all(not row['animation_events'] and not row['combat_actions'] for row in states['one_stage_deaths'])
 assert len(world['movement'])==3 and all(world[k] for k in ('frozen_idle_stable','live_idle_changed_pixels','rotation_position_preserved','pause_cancels_movement'))
 assert oracle['comparisons']==6914 and oracle['synthetic_cases']==6000 and oracle['source_cases']==896 and oracle['mismatches']==0 and oracle['all_owner_sheets_result_actor_states_and_requests_compared'] and oracle['original_service_request_order_verified']
 assert oracle['arm64_library_sha256']==digest(local/'combat-application-oracle.so') and oracle['original_sha256']==digest(local/'libDungeonHunter2.so') and oracle['reference_sha256']==digest(local/'combat-application-original.bin') and oracle['spawn_reference_sha256']==digest(local/'vitals-original-spawn.bin')
 assert host['original_application_cases']==6914 and host['owner_words_per_case']==1792 and host['result_and_actor_state_words']==20 and host['application_words']==25 and host['invalid_input_atomic']
 assert host['kill_requests']==oracle['counts']['kills']==oracle['core_kill_death_events'] and host['hit_calls']==oracle['counts']['hits'] and host['status_requests']==oracle['counts']['statuses'] and all(host['status_requests'])
 assert health==prior['health_asan_ubsan']
 event_path=REPO/'port/game-data/reports/combat-events-application-arm64-differential.json';event_oracle=read(event_path);event_host=read(local/'combat-application-event-host-regression.json');assert event_oracle['attack_event_decisions_compared']==6000 and event_oracle['mismatches']==0 and event_oracle['runtime_sequences']==[0,1,2] and len(event_oracle['runtime_cases'])==24 and event_oracle['arm64_library_sha256']==digest(local/'combat-events-application-oracle.so') and event_oracle['native_host_reference_sha256']==digest(local/'combat-events-application-original.bin') and event_oracle['original_sha256']==digest(local/'libDungeonHunter2.so') and event_host['original_attack_event_decisions']==6000 and event_host['original_character_damage_cases']==1792 and event_host['all_damage_words_and_rng_verified']
 assert live['original_application_report_sha256']==digest(oracle_path) and all(live[k] for k in ('frozen_attacks_do_not_hit','dead_target_rejection_verified','automatic_original_death_clips_verified'))
 assert [r['orientation'] for r in live['rotation_preserves_hp_and_does_not_replay_hits']]==[1,0] and all(r['hits']==1 and r['target_hp']==10145 for r in live['rotation_preserves_hp_and_does_not_replay_hits']) and live['inflight_pause_resume_does_not_replay_hits']==[{'case':'inflight_attack_pause_resume','hits':2}]
 for pair,reference in zip(live['pairs'],oracle['live_sequences']):
  assert pair['frozen_no_hit'] and pair['dead_target_rejected'] and len(pair['attacks'])==len(reference['attacks'])==6
  assert pair['death_clip'] in (1251,700,1185) and pair['attacks'][-1]['hp_after']==0 and pair['attacks'][-1]['dead']==1
  for actual,expected in zip(pair['attacks'],reference['attacks']):
   words=expected['application_words'];assert actual['result']==expected['result_after'] and actual['random_after']==expected['random_after'] and actual['hp_before']==words[1] and actual['hp_after']==words[2] and actual['combo']==expected['state_after'][2] and actual['dead']==expected['state_after'][5] and actual['status_requests']==words[16]
 assets=prior['assets_verified'];assert len(assets)==107;required=set(prior['packaged_combat_exports_verified']['arm64-v8a'])|{'dh2_combat_apply_monster'};packaged={}
 with zipfile.ZipFile(apk) as archive:
  names={n.removeprefix('assets/') for n in archive.namelist() if n.startswith('assets/') and not n.endswith('/')};assert names==set(assets)
  for name,row in assets.items():
   raw=archive.read('assets/'+name);assert raw==(ROOT/'app/src/main/assets'/name).read_bytes()==(a.studio/'app/src/main/assets'/name).read_bytes();assert len(raw)==row['bytes'] and hashlib.sha256(raw).hexdigest()==row['sha256'],name
  for abi in ('arm64-v8a','x86_64'):assert required<=exports(archive.read('lib/'+abi+'/libdh2_game_data.so'));packaged[abi]=sorted(required)
 source={}
 for name in prior['studio_source_sha256']:
  file=ROOT/'app/src/main'/name;assert digest(file)==digest(a.studio/'app/src/main'/name);source[name]=digest(file)
 for name,before in prior['module_source_sha256'].items():
  if name not in {'game-data/CMakeLists.txt','game-data/tests/combat_events_differential.py','android-native/tools/actor_states_smoke.py'}:assert digest(REPO/'port'/name)==before,name
 for folder in ('actor-states-tests-combat-application','world-tests-combat-application','combat-application-tests'):
  for file in (local/folder).glob('*.log'):assert not re.search(r'FATAL EXCEPTION|GL error|load failed|sample failed|completion failed|event dispatch failed|combat route failed|probe failed|application failed|death animation failed|Shader failed|Link failed',log(file)),file
 for name in ('combat-application-android-build.log','combat-application-studio-build.log'):assert 'BUILD SUCCESSFUL' in log(local/name)
 assert 'Verification successful' in log(local/'combat-application-zipalign.log')
 cache=subprocess.run(['wsl','cat',a.host_build+'/CMakeCache.txt'],capture_output=True,text=True,check=True).stdout
 for prefix in ('CMAKE_CXX_FLAGS:STRING=','CMAKE_EXE_LINKER_FLAGS:STRING=','CMAKE_SHARED_LINKER_FLAGS:STRING='):assert '-fsanitize=address,undefined' in next(s for s in cache.splitlines() if s.startswith(prefix))
 modules=set(prior['module_source_sha256'])|{'game-data/combat_application.cpp','game-data/combat_application.hpp','game-data/tests/combat_application.cpp','game-data/tests/combat_application_differential.py','game-data/tools/build_combat_application_oracle.ps1','android-native/tools/combat_application_smoke.py','android-native/tools/validate_combat_application_checkpoint.py'}
 modules.update(str(f.relative_to(REPO/'port')).replace('\\','/') for f in (REPO/'port/game-data/reference/combat-application').rglob('*') if f.is_file())
 validation={'apk_sha256':sha,'apk_bytes':apk.stat().st_size,'studio_apk_sha256':digest(a.studio/'app/build/outputs/apk/debug/app-debug.apk'),'source_sync_verified':True,'studio_source_sha256':source,'module_source_sha256':{name:digest(REPO/'port'/name) for name in sorted(modules)},'libraries':libraries,'apk_16k_zip_alignment_verified':True,'assets_verified':assets,'original_input_count':prior['original_input_count'],'cache_sha256':prior['cache_sha256'],'packaged_combat_exports_verified':packaged,'combat_application_asan_ubsan':host,'health_host_regression':health,'combat_application_original_arm64_comparisons':{'cases':6914,'arm64_library_sha256':oracle['arm64_library_sha256'],'report_sha256':digest(oracle_path),'reference_sha256':oracle['reference_sha256']},'actor_state_cases':24,'world_cases':10,'native_live_hits_verified':18,'native_automatic_deaths_verified':3,'native_android_health_probes_verified':22,'native_android_result_probes_verified':11,'combat_rotation_and_pause_checks':3,'prior_health_checkpoint_apk_sha256':prior['apk_sha256'],'prior_unchanged_helper_evidence':prior['prior_unchanged_helper_evidence'],'prior_combat_result_comparisons':prior['prior_combat_result_comparisons'],'combat_result_application_implemented':True,'combat_application_scope':oracle['scope'],'core_kill_dead_and_hp_writes_implemented':True,'original_death_clip_adapter_implemented':True,'full_ai_fsm_or_kill_rewards_implemented':False,'aggro_or_status_services_implemented':False,'target_selection_scope':'Explicit development target indices','automatic_target_selection_or_full_ai_implemented':False,'combat_execution_implemented':True,'physical_arm64_tested':False,'full_cache_bundled':False,'full_game_playable':False,'goal_status':'active'}
 validation['expanded_event_original_comparisons']={'cases':6000,'runtime_sequences':[0,1,2],'runtime_cases':24,'report_sha256':digest(event_path),'arm64_library_sha256':event_oracle['arm64_library_sha256']};validation['damage_and_event_host_regression']=event_host
 for path,result in ((ROOT/'reports/build-validation-combat-application.json',validation),(ROOT/'reports/actor-states-smoke-combat-application.json',states),(ROOT/'reports/world-smoke-combat-application.json',world),(ROOT/'reports/combat-application-smoke.json',live),(REPO/'port/game-data/reports/combat-application-host-audit.json',host),(REPO/'port/game-data/reports/combat-application-damage-event-host-regression.json',event_host)):
  path.parent.mkdir(parents=True,exist_ok=True);path.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8')
 checkpoint=ROOT/'build/checkpoints'/f'dh2-native-combat-application-{sha[:8]}.apk';checkpoint.parent.mkdir(parents=True,exist_ok=True);checkpoint.write_bytes(apk.read_bytes());assert digest(checkpoint)==sha
 print(json.dumps({'apk_sha256':sha,'apk_bytes':apk.stat().st_size,'assets':len(assets),'baseline_emulator_cases':34,'native_live_hits':18,'automatic_deaths':3,'original_application_comparisons':6914,'goal_status':'active'}))
if __name__=='__main__':main()
