"""Bind player damage/death and retained touch combat to one native APK."""
import argparse,hashlib,json,re,subprocess,zipfile
from pathlib import Path
from emulator_smoke import inspect
from validate_world_checkpoint import digest,read,log,ROOT,REPO
from validate_combat_checkpoint import exports
from player_defender_smoke import checksum

def main():
 p=argparse.ArgumentParser();p.add_argument('--studio',type=Path,required=True);p.add_argument('--cache',type=Path,required=True);p.add_argument('--host-build',default='/home/adampalace/dh2-world-build');a=p.parse_args();local=REPO/'.local-inputs';apk=ROOT/'app/build/outputs/apk/debug/app-debug.apk';sha=digest(apk);libraries=inspect(apk);assert len(libraries)==14
 prior=read(ROOT/'reports/build-validation-player-combat.json');states=read(local/'actor-states-tests-player-defender/actor-states-smoke.json');world=read(local/'world-tests-player-defender/world-smoke.json');attacks=read(local/'player-combat-tests-player-defender/player-combat-smoke.json');live=read(local/'player-defender-tests/player-defender-smoke.json')
 assert states['apk_sha256']==world['apk_sha256']==world['installed_apk_sha256']==attacks['apk_sha256']==attacks['installed_apk_sha256']==live['apk_sha256']==live['installed_apk_sha256']==sha
 assert len(states['cases'])==24 and len(world['cases'])==10 and attacks['native_player_attempts_verified']==112 and live['native_player_damage_attempts_verified']==73
 for key in ('authored_animation_events_verified','base_class_snapshots_verified','resolved_property_snapshots_verified','spawn_vitals_verified','independent_idle_instances_verified','state5_attack_event_decisions_verified','frozen_attack_events_absent_verified','packaged_combat_result_probes_verified','packaged_health_probes_verified','combat_execution_implemented','live_combat_health_application_implemented'):assert states[key],key
 assert states['health_probe_count']==22 and states['combat_result_probe_count']==11 and not states['full_combat_or_ai_implemented']
 assert len(world['movement'])==3 and all(world[k] for k in ('frozen_idle_stable','live_idle_changed_pixels','rotation_position_preserved','pause_cancels_movement')) and world['floor_geometry_sha256']==digest(local/'world-floor.json')
 for key,path in [('original_class_report_sha256','game-data/reports/classes-regression-vitals.json'),('original_property_report_sha256','game-data/reports/properties-arm64-differential.json'),('original_vitals_report_sha256','game-data/reports/vitals-arm64-differential.json'),('original_event_report_sha256','engine-animation/reports/events-arm64-differential.json'),('original_combat_event_report_sha256','game-data/reports/combat-events-application-arm64-differential.json'),('original_combat_result_report_sha256','game-data/reports/combat-result-arm64-differential.json'),('original_health_report_sha256','game-data/reports/health-arm64-differential.json')]:assert states[key]==digest(REPO/'port'/path)
 player_path=REPO/'port/game-data/reports/player-application-arm64-differential.json';player=read(player_path);reference=next(r for r in player['live_sequences'] if r['defender']=='Crypt_Skeleton');assert attacks['original_player_application_report_sha256']==digest(player_path) and len(attacks['attempts'])==len(reference['attacks'])==112
 signed=lambda v:v if v<0x80000000 else v-0x100000000
 for number,(actual,expected) in enumerate(zip(attacks['attempts'],reference['attacks']),1):
  words=expected['application_words'];assert actual['attempt']==number and actual['result']==expected['result_after'] and actual['random_after']==expected['random_after'] and actual['hp_before']==signed(words[1]) and actual['hp_after']==signed(words[2]) and actual['combo']==expected['state_after'][2] and actual['dead']==expected['state_after'][5] and actual['status_requests']==words[16]
 for key in ('out_of_reach_rejected','frozen_attack_no_hit','busy_attack_does_not_restart','original_player_sheet_checksum_verified'):assert attacks[key],key
 assert attacks['automatic_original_death_clip']==1185 and len(attacks['rotation_does_not_replay_hits'])==2 and attacks['inflight_pause_resume'] is not None
 oracle_path=REPO/'port/game-data/reports/player-defender-arm64-differential.json';oracle=read(oracle_path);host=read(local/'player-defender-host-audit.json');death=read(local/'player-death-host-audit.json');raw=(local/'player-defender-original.bin').read_bytes()
 assert oracle['player_defender'] and not oracle['player_attacker'] and oracle['comparisons']==2969 and oracle['synthetic_cases']==2000 and oracle['source_cases']==896 and oracle['mismatches']==0 and oracle['original_service_request_order_verified'] and oracle['all_owner_sheets_result_actor_states_and_requests_compared']
 for key,name in [('arm64_library_sha256','player-defender-oracle.so'),('reference_sha256','player-defender-original.bin'),('original_sha256','libDungeonHunter2.so'),('spawn_reference_sha256','vitals-original-spawn.bin')]:assert oracle[key]==digest(local/name)
 assert host['original_application_cases']==2969 and host['owner_words_per_case']==1792 and host['result_and_actor_state_words']==20 and host['application_words']==25 and host['invalid_input_atomic'] and host['kill_requests']==oracle['counts']['kills']==339 and host['hit_calls']==oracle['counts']['hits'] and host['status_requests']==oracle['counts']['statuses']
 assert read(local/'player-defender-player-regression.json')==prior['player_application_asan_ubsan'] and read(local/'player-defender-monster-regression.json')==prior['monster_application_host_regression'] and read(local/'player-defender-attack-pose-regression.json')==prior['player_pose_asan_ubsan']
 assert death['player_row']==263 and death['original_owner_words_compared']==896 and death['warrior_skins']==4 and death['every_millisecond_poses']==1400 and death['melee_event_tracks']==0 and death['finite_skinned_vertices'] and len(death['clips'])==1 and death['clips'][0]['id']==1023 and death['clips'][0]['tracks']==27
 assert live['original_report_sha256']==digest(oracle_path) and live['original_reference_sha256']==digest(local/'player-defender-original.bin') and live['low_health_cues_verified']==live['automatic_player_deaths_verified']==3 and live['death_clip']==1023
 for key in ('hud_health_mana_and_defeated_verified','inflight_pause_resume_verified','dead_player_attack_rejected','dead_player_movement_blocked'):assert live[key],key
 assert [(r['orientation'],r['attempts'],r['hp']) for r in live['rotation_preserves_health_and_death']]==[(1,1,40250),(0,1,40250),(1,24,0),(0,24,0)]
 at=4+(oracle['synthetic_cases']+oracle['source_cases'])*14600
 for pair,reference in zip(live['pairs'],oracle['live_sequences']):
  assert pair['attacker']==reference['attacker'] and pair['defender']=='KnightPlayerBase' and pair['frozen_no_hit'] and pair['dead_player_target_rejected'] and pair['death_clip']==1023 and len(pair['attacks'])==len(reference['attacks'])==24 and sum(r['low_health_cue'] for r in pair['attacks'])==1
  for number,(actual,expected) in enumerate(zip(pair['attacks'],reference['attacks']),1):
   words=expected['application_words'];assert actual['attempt']==number and actual['result']==expected['result_after'] and actual['random_after']==expected['random_after'] and actual['hp_before']==signed(words[1]) and actual['hp_after']==signed(words[2]) and actual['dead']==expected['state_after'][5] and actual['combo']==expected['state_after'][2] and actual['low_health_armed']==words[4] and actual['low_health_cue']==words[5] and actual['status_requests']==words[16] and actual['resolved_checksum']==checksum(raw[at+13520:at+14416]);at+=14600
 expected=oracle['walking_live_case'];actual=live['walking_live_case'];words=expected['application_words'];assert live['walking_damage_verified'] and actual['held_touch_and_walk_clip_verified'] and actual['defender_fsm_state']==13 and actual['result']==expected['result_after'] and actual['random_after']==expected['random_after'] and actual['hp_before']==words[1] and actual['hp_after']==words[2] and actual['dead']==expected['state_after'][5] and actual['combo']==expected['state_after'][2] and actual['low_health_armed']==words[4] and actual['low_health_cue']==words[5] and actual['status_requests']==words[16] and actual['resolved_checksum']==checksum(raw[at+13520:at+14416]);at+=14600
 assert at==len(raw)
 assets=dict(prior['assets_verified']);assert len(assets)==117;provenance_path=ROOT/'app/src/main/assets/player-defender-provenance.json';provenance=read(provenance_path);assert digest(a.cache)==provenance['cache_sha256']==prior['cache_sha256'] and provenance['state']=='Died' and provenance['root_sequence']==259 and len(provenance['inputs'])==1
 with zipfile.ZipFile(a.cache) as cache:
  row=provenance['inputs'][0];assert row['clip_id']==1023;data=cache.read(row['entry']);assert len(data)==row['bytes'] and hashlib.sha256(data).hexdigest()==row['sha256'];assets[row['asset']]={'bytes':row['bytes'],'sha256':row['sha256']}
 assets['player-defender-provenance.json']={'bytes':provenance_path.stat().st_size,'sha256':digest(provenance_path)};assert len(assets)==119;required=set(prior['packaged_combat_exports_verified']['arm64-v8a'])|{'dh2_combat_apply_monster_to_player'};packaged={}
 with zipfile.ZipFile(apk) as z:
  assert {n[7:] for n in z.namelist() if n.startswith('assets/') and not n.endswith('/')}==set(assets)
  for name,row in assets.items():
   data=z.read('assets/'+name);assert data==(ROOT/'app/src/main/assets'/name).read_bytes()==(a.studio/'app/src/main/assets'/name).read_bytes() and len(data)==row['bytes'] and hashlib.sha256(data).hexdigest()==row['sha256'],name
  for abi in ('arm64-v8a','x86_64'):assert required<=exports(z.read('lib/'+abi+'/libdh2_game_data.so'));packaged[abi]=sorted(required)
 source={}
 for name in prior['studio_source_sha256']:assert digest(ROOT/'app/src/main'/name)==digest(a.studio/'app/src/main'/name);source[name]=digest(ROOT/'app/src/main'/name)
 changed={'game-data/CMakeLists.txt','game-data/combat_application.cpp','game-data/combat_application.hpp','game-data/tests/combat_application.cpp','game-data/tests/combat_application_differential.py','level-world/tests/player_combat.cpp'}
 for name,before in prior['module_source_sha256'].items():
  if name not in changed:assert digest(REPO/'port'/name)==before,name
 for folder in ('actor-states-tests-player-defender','world-tests-player-defender','player-combat-tests-player-defender','player-defender-tests'):
  for file in (local/folder).glob('*.log'):assert not re.search(r'FATAL EXCEPTION|GL error|load failed|sample failed|completion failed|event dispatch failed|combat route failed|probe failed|application failed|death animation failed|Shader failed|Link failed',log(file)),file
 for name in ('player-defender-android-build.log','player-defender-studio-build.log'):assert 'BUILD SUCCESSFUL' in log(local/name)
 assert 'Verification successful' in log(local/'player-defender-zipalign.log')
 cache=subprocess.run(['wsl','cat',a.host_build+'/CMakeCache.txt'],capture_output=True,text=True,check=True).stdout
 for prefix in ('CMAKE_CXX_FLAGS:STRING=','CMAKE_EXE_LINKER_FLAGS:STRING=','CMAKE_SHARED_LINKER_FLAGS:STRING='):assert '-fsanitize=address,undefined' in next(s for s in cache.splitlines() if s.startswith(prefix))
 modules=set(prior['module_source_sha256'])|changed|{'level-world/tools/prepare_player_defender.py','android-native/tools/player_defender_smoke.py','android-native/tools/validate_player_defender_checkpoint.py'};modules.update(str(f.relative_to(REPO/'port')).replace('\\','/') for folder in ('player-defender','aggro') for f in (REPO/'port/game-data/reference'/folder).rglob('*') if f.is_file())
 validation={'apk_sha256':sha,'apk_bytes':apk.stat().st_size,'studio_apk_sha256':digest(a.studio/'app/build/outputs/apk/debug/app-debug.apk'),'source_sync_verified':True,'studio_source_sha256':source,'module_source_sha256':{n:digest(REPO/'port'/n) for n in sorted(modules)},'libraries':libraries,'apk_16k_zip_alignment_verified':True,'assets_verified':assets,'original_input_count':prior['original_input_count']+1,'cache_sha256':prior['cache_sha256'],'packaged_combat_exports_verified':packaged,'player_defender_asan_ubsan':host,'player_death_pose_asan_ubsan':death,'player_attacker_host_regression':read(local/'player-defender-player-regression.json'),'monster_application_host_regression':read(local/'player-defender-monster-regression.json'),'player_attack_pose_host_regression':read(local/'player-defender-attack-pose-regression.json'),'player_defender_original_arm64_comparisons':{'cases':2969,'report_sha256':digest(oracle_path),'arm64_library_sha256':oracle['arm64_library_sha256'],'reference_sha256':oracle['reference_sha256']},'actor_state_cases':24,'world_cases':10,'native_player_attack_attempts_verified':112,'native_player_damage_attempts_verified':73,'native_player_deaths_verified':3,'native_monster_deaths_verified':1,'low_health_cues_verified':3,'native_android_health_probes_verified':22,'native_android_result_probes_verified':11,'prior_player_combat_checkpoint_apk_sha256':prior['apk_sha256'],'prior_unchanged_helper_evidence':prior['prior_unchanged_helper_evidence'],'prior_combat_result_comparisons':prior['prior_combat_result_comparisons'],'expanded_event_original_comparisons':prior['expanded_event_original_comparisons'],'player_defender_scope':oracle['scope'],'enemy_target_scope':live['target_scope'],'player_input_scope':prior['player_input_scope'],'hud_scope':'Native property values; new health/mana/defeated display, original HUD reconstruction pending','player_damage_and_death_implemented':True,'full_ai_fsm_or_kill_rewards_implemented':False,'aggro_or_status_services_implemented':False,'physical_arm64_tested':False,'full_cache_bundled':False,'full_game_playable':False,'goal_status':'active'}
 for path,result in ((ROOT/'reports/build-validation-player-defender.json',validation),(ROOT/'reports/actor-states-smoke-player-defender.json',states),(ROOT/'reports/world-smoke-player-defender.json',world),(ROOT/'reports/player-combat-smoke-player-defender.json',attacks),(ROOT/'reports/player-defender-smoke.json',live)):
  path.parent.mkdir(parents=True,exist_ok=True);path.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8')
 checkpoint=ROOT/'build/checkpoints'/f'dh2-native-player-defender-{sha[:8]}.apk';checkpoint.parent.mkdir(parents=True,exist_ok=True);checkpoint.write_bytes(apk.read_bytes());assert digest(checkpoint)==sha
 print(json.dumps({'apk_sha256':sha,'apk_bytes':apk.stat().st_size,'assets':119,'original_inputs':108,'baseline_emulator_cases':34,'player_attack_attempts':112,'player_damage_attempts':73,'automatic_deaths':4,'original_player_defender_cases':2969,'goal_status':'active'}))

if __name__=='__main__':main()
